// Code generated by testkit stub. DO NOT EDIT.
// Source: generator.go:29-29 (testkit stub Generator)

package idtest_test

import (
	"testing"

	"go.thesmos.sh/core/coretest/idtest"
	"go.thesmos.sh/core/id"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestGeneratorStub(t *testing.T) {
	t.Parallel()

	t.Run("Generate default returns zero", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		result := s.Generate()
		testkit.Equal(t, result, id.ID{}, "Generate must return zero")
	})

	t.Run("Generate Func override", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		called := false
		s.OnGenerate.Func(func() id.ID {
			called = true
			return id.ID{}
		})
		result := s.Generate()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, id.ID{}, "Func must return set value")
	})

	t.Run("Generate Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		s.OnGenerate.Returns(id.ID{})
		result := s.Generate()
		testkit.Equal(t, result, id.ID{}, "Returns must return set value")
	})

	t.Run("Generate records calls", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		_ = s.Generate()
		s.OnGenerate.AssertCalledOnce(t, "must record Generate call")
	})

	t.Run("WithGeneratorGenerate constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := idtest.NewGeneratorStub(t, idtest.WithGeneratorGenerate(func() id.ID {
			called = true
			return id.ID{}
		}))
		_ = s.Generate()
		testkit.True(t, called, "WithGeneratorGenerate must be called")
	})

	t.Run("Generate OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		var observed []idtest.GeneratorGenerateCall
		s.OnGenerate.OnRecord(func(c idtest.GeneratorGenerateCall) {
			observed = append(observed, c)
		})
		_ = s.Generate()
		_ = s.Generate()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Generate call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t, idtest.GeneratorStubBenchMode())
		_ = s.Generate()
		testkit.Equal(t, s.OnGenerate.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t, idtest.GeneratorStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := idtest.NewGeneratorStub(f)
		s.OnGenerate.Times(2)
		_ = s.Generate()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := idtest.NewGeneratorStub(f)
		s.OnGenerate.TimesAtLeast(3)
		_ = s.Generate()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		_ = s.Generate()
		s.ResetCalls()
		s.OnGenerate.AssertNotCalled(t, "Generate must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Generate", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := idtest.NewGeneratorStub(f, idtest.GeneratorStubStrict())
		_ = s.Generate()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Generate")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := idtest.NewGeneratorStub(t)
		inner.OnGenerate.Returns(id.ID{})
		s := idtest.NewGeneratorStub(t, idtest.GeneratorStubDelegateTo(inner))
		_ = s.Generate()
		s.OnGenerate.AssertCalledOnce(t, "Generate must delegate")
	})

	t.Run("DelegateTo surfaces Generate return values", func(t *testing.T) {
		t.Parallel()
		inner := idtest.NewGeneratorStub(t)
		inner.OnGenerate.Returns(id.ID{})
		s := idtest.NewGeneratorStub(t, idtest.GeneratorStubDelegateTo(inner))
		result := s.Generate()
		testkit.Equal(t, result, id.ID{}, "Generate must return configured value")
	})

	t.Run("ResetCalls preserves Generate Returns config", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		s.OnGenerate.Returns(id.ID{})
		_ = s.Generate()
		s.ResetCalls()
		s.OnGenerate.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Generate()
		testkit.Equal(t, result, id.ID{}, "Generate must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := idtest.NewGeneratorStub(t)
		_ = s.Generate()
		testkit.Len(t, s.OnGenerate.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnGenerate.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestGeneratorStubBenchModeZeroAlloc(t *testing.T) {
	s := idtest.NewGeneratorStub(nil, idtest.GeneratorStubBenchMode())
	s.OnGenerate.Returns(id.ID{})

	t.Run("Generate", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Generate()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Generate in BenchMode must be 0 alloc")
	})

}
