// Code generated by testkit suite. DO NOT EDIT.
// Source: generator.go:29-29 (testkit suite Generator)

package idtest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/id"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertGeneratorContract runs conformance assertions against
// implementations of [id.Generator] produced by factory.
//
//	Default subtests: 1 across 1 methods
//	Shapes detected:  Pure (Generate)
//	Directives:       none
//	Plug-in points:   GeneratorOnGenerate, GeneratorOnAll, GeneratorCustom
func AssertGeneratorContract(
	t *testing.T,
	factory func() id.Generator,
	opts ...GeneratorOption,
) {
	t.Helper()
	cfg := newGeneratorConfig(opts...)

	runGeneratorGenerate(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[id.Generator]{
			T:             t,
			CrossBindings: bindings.CrossBindings[id.Generator]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runGeneratorGenerate(t *testing.T, factory func() id.Generator, cfg *generatorConfig) {
	t.Helper()

	t.Run("Generate/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Generate panicked on zero-value args (%v) — supply sample values via GeneratorOnGenerate", r)
			}
		}()
		s := factory()
		_ = s.Generate()
	})
	if len(cfg.onGenerate) > 0 {
		t.Run("Generate", func(t *testing.T) {
			prePopFactory := func() id.Generator {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[id.Generator, id.ID]{
				T: t,
				PureBindings: bindings.PureBindings[id.Generator, id.ID]{
					Factory: prePopFactory,
					Call: func(impl id.Generator) id.ID {
						return impl.Generate()
					},
				},
			}
			for _, a := range cfg.onGenerate {
				a(pctx)
			}
		})
	}
}

// GeneratorOption configures [AssertGeneratorContract].
type GeneratorOption func(*generatorConfig)

// GeneratorPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func GeneratorPrePopulate(fn func(ctx context.Context, s id.Generator)) GeneratorOption {
	return func(c *generatorConfig) { c.prePopulate = fn }
}

// GeneratorCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func GeneratorCustom(name string, fn func(*testing.T, id.Generator)) GeneratorOption {
	return func(c *generatorConfig) {
		c.custom = append(c.custom, generatorCustomSubtest{name: name, fn: fn})
	}
}

// GeneratorOnGenerate adds plug-in assertions for the Generate method.
func GeneratorOnGenerate(assertions ...suite.PureAssertion[id.Generator, id.ID]) GeneratorOption {
	return func(c *generatorConfig) {
		c.onGenerate = append(c.onGenerate, assertions...)
	}
}

// GeneratorOnAll adds cross-method assertions that span multiple methods.
func GeneratorOnAll(assertions ...suite.CrossMethodAssertion[id.Generator]) GeneratorOption {
	return func(c *generatorConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type generatorCustomSubtest struct {
	name string
	fn   func(*testing.T, id.Generator)
}

type generatorConfig struct {
	prePopulate func(context.Context, id.Generator)
	custom      []generatorCustomSubtest
	onAll       []suite.CrossMethodAssertion[id.Generator]
	onGenerate  []suite.PureAssertion[id.Generator, id.ID]
}

func newGeneratorConfig(opts ...GeneratorOption) generatorConfig {
	var cfg generatorConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
