// Code generated by kanon. DO NOT EDIT.
// source: policy.go

//kanon:numbers Log URL=1 Key=2
//kanon:numbers Witness Name=1 URL=2 Key=3
//kanon:numbers Group Name=1 Members=2 Threshold=3
//kanon:numbers Policy Quorum=1 Logs=2 Witnesses=3 Groups=4

package checkpoint

import (
	"io"
	"slices"
	"strings"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 3 of the generator.
const (
	_ = kanon.EnforceVersion(3 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 3)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Log]     = (*Log)(nil)
	_ kanon.Cloner[Witness] = (*Witness)(nil)
	_ kanon.Cloner[Group]   = (*Group)(nil)
	_ kanon.Cloner[Policy]  = (*Policy)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Log) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.URL != "" {
		n += 1 + wire.SizeBytes(len(m.URL))
	}
	if s := m.Key.SizeKanon(); s > 0 {
		n += 1 + wire.SizeBytes(s)
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Log) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Log) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if w, err := m.Key.EncodeKanon(buf[:i]); err != nil {
		return 0, err
	} else if w > 0 {
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.URL != "" {
		i = wire.PutRaw(buf, i, m.URL)
		i = wire.PutUvarint(buf, i, uint64(len(m.URL)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Log) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Log) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Log) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It accepts
// only the canonical encoding of a value, the input that EncodeKanon writes for
// it, and returns a *kanon.DecodeError that wraps kanon.ErrNotCanonical for any
// other input that the wire format lets a decoder accept. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Log) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Log) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Log
// call it.
func (m *Log) decodeKanon(data []byte, slab string, off, depth int) error {
	m.URL = ""
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Key.Reset()
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Log call
// it.
func (m *Log) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Log) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	var prior uint64
	i := 0
	if i < len(data) && data[i] == 1<<3|wire.Bytes {
		at := i
		i++
		prior = 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return seen, wire.ReadError(n, "Log.URL", 1, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return seen, wire.LongFormError(n, "Log.URL", 1, off+i)
		}
		i += n
		m.URL = slab[off+i : off+i+int(l)]
		i += int(l)
		if l == 0 {
			return seen, wire.AbsentError("Log.URL", 1, off+at)
		}
	}
	if i < len(data) && data[i] == 2<<3|wire.Bytes {
		at := i
		i++
		prior = 2
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return seen, wire.ReadError(n, "Log.Key", 2, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return seen, wire.LongFormError(n, "Log.Key", 2, off+i)
		}
		i += n
		if depth < 1 {
			return seen, wire.DepthError("note.Key", 0, off+i)
		}
		var err error
		if seen[0]&(1<<0) == 0 {
			seen[0] |= 1 << 0
			err = m.Key.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
		} else {
			err = m.Key.MergeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
		}
		if err != nil {
			return seen, err
		}
		i += int(l)
		if l == 0 {
			return seen, wire.AbsentError("Log.Key", 2, off+at)
		}
	}
	if i != len(data) {
		return seen, _policy_tagLog(data, i, prior, off)
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Log) Reset() {
	if m == nil {
		return
	}
	m.URL = ""
	m.Key.Reset()
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Log) CloneKanon() *Log {
	if m == nil {
		return nil
	}
	c := new(Log)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Log call it.
func (m *Log) cloneKanon(c *Log) {
	c.URL = strings.Clone(m.URL)
	c.Key = *m.Key.CloneKanon()
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Witness) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += 1 + wire.SizeBytes(len(m.Name))
	}
	if m.URL != "" {
		n += 1 + wire.SizeBytes(len(m.URL))
	}
	if s := m.Key.SizeKanon(); s > 0 {
		n += 1 + wire.SizeBytes(s)
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Witness) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Witness) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if w, err := m.Key.EncodeKanon(buf[:i]); err != nil {
		return 0, err
	} else if w > 0 {
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if m.URL != "" {
		i = wire.PutRaw(buf, i, m.URL)
		i = wire.PutUvarint(buf, i, uint64(len(m.URL)))
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Name != "" {
		if err := m.Name.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Witness.Name", 1)
		}
		i = wire.PutRaw(buf, i, m.Name)
		i = wire.PutUvarint(buf, i, uint64(len(m.Name)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Witness) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Witness) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Witness) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It accepts
// only the canonical encoding of a value, the input that EncodeKanon writes for
// it, and returns a *kanon.DecodeError that wraps kanon.ErrNotCanonical for any
// other input that the wire format lets a decoder accept. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Witness) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Witness) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Witness
// call it.
func (m *Witness) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Name = ""
	m.URL = ""
	seen, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{})
	if seen[0]&(1<<0) == 0 {
		m.Key.Reset()
	}
	return err
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Witness
// call it.
func (m *Witness) mergeKanon(data []byte, slab string, off, depth int) error {
	_, err := m.fieldsKanon(data, slab, off, depth, [1]uint64{^uint64(0)})
	return err
}

// fieldsKanon decodes the fields in data into m for decodeKanon and mergeKanon.
// The first occurrence of a tracked field whose bit in seen is clear decodes
// into the memory of the field, and every other occurrence merges. fieldsKanon
// returns seen with the bits of the tracked fields that data contains.
func (m *Witness) fieldsKanon(data []byte, slab string, off, depth int, seen [1]uint64) ([1]uint64, error) {
	var prior uint64
	i := 0
	if i < len(data) && data[i] == 1<<3|wire.Bytes {
		at := i
		i++
		prior = 1
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return seen, wire.ReadError(n, "Witness.Name", 1, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return seen, wire.LongFormError(n, "Witness.Name", 1, off+i)
		}
		i += n
		m.Name = PolicyName(slab[off+i : off+i+int(l)])
		i += int(l)
		if err := m.Name.ValidateKanon(); err != nil {
			return seen, wire.UnmarshalError(err, "Witness.Name", 1, from)
		}
		if l == 0 {
			return seen, wire.AbsentError("Witness.Name", 1, off+at)
		}
	}
	if i < len(data) && data[i] == 2<<3|wire.Bytes {
		at := i
		i++
		prior = 2
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return seen, wire.ReadError(n, "Witness.URL", 2, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return seen, wire.LongFormError(n, "Witness.URL", 2, off+i)
		}
		i += n
		m.URL = slab[off+i : off+i+int(l)]
		i += int(l)
		if l == 0 {
			return seen, wire.AbsentError("Witness.URL", 2, off+at)
		}
	}
	if i < len(data) && data[i] == 3<<3|wire.Bytes {
		at := i
		i++
		prior = 3
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return seen, wire.ReadError(n, "Witness.Key", 3, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return seen, wire.LongFormError(n, "Witness.Key", 3, off+i)
		}
		i += n
		if depth < 1 {
			return seen, wire.DepthError("note.Key", 0, off+i)
		}
		var err error
		if seen[0]&(1<<0) == 0 {
			seen[0] |= 1 << 0
			err = m.Key.DecodeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
		} else {
			err = m.Key.MergeKanon(data[i:i+int(l)], wire.Nested(slab, off+i, depth-1))
		}
		if err != nil {
			return seen, err
		}
		i += int(l)
		if l == 0 {
			return seen, wire.AbsentError("Witness.Key", 3, off+at)
		}
	}
	if i != len(data) {
		return seen, _policy_tagWitness(data, i, prior, off)
	}
	return seen, nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Witness) Reset() {
	if m == nil {
		return
	}
	m.Name = ""
	m.URL = ""
	m.Key.Reset()
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Witness) CloneKanon() *Witness {
	if m == nil {
		return nil
	}
	c := new(Witness)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Witness call it.
func (m *Witness) cloneKanon(c *Witness) {
	c.Name = PolicyName(strings.Clone(string(m.Name)))
	c.URL = strings.Clone(m.URL)
	c.Key = *m.Key.CloneKanon()
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Group) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Name != "" {
		n += 1 + wire.SizeBytes(len(m.Name))
	}
	if len(m.Members) > 0 {
		n += 1 + wire.SizeBytes(_policy_sizeSlicePolicyName(m.Members))
	}
	if m.Threshold != 0 {
		n += 1 + wire.SizeUvarint(wire.Zigzag(int64(m.Threshold)))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Group) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Group) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if m.Threshold != 0 {
		i = wire.PutUvarint(buf, i, wire.Zigzag(int64(m.Threshold)))
		i = wire.PutTag(buf, i, 3<<3|wire.Varint)
	}
	if len(m.Members) > 0 {
		w, err := _policy_putSlicePolicyName(buf[:i], m.Members, "Group.Members", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Name != "" {
		if err := m.Name.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Group.Name", 1)
		}
		i = wire.PutRaw(buf, i, m.Name)
		i = wire.PutUvarint(buf, i, uint64(len(m.Name)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Group) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Group) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Group) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It accepts
// only the canonical encoding of a value, the input that EncodeKanon writes for
// it, and returns a *kanon.DecodeError that wraps kanon.ErrNotCanonical for any
// other input that the wire format lets a decoder accept. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Group) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Group) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Group
// call it.
func (m *Group) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Name = ""
	m.Members = m.Members[:0]
	m.Threshold = 0
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Group
// call it.
func (m *Group) mergeKanon(data []byte, slab string, off, depth int) error {
	var prior uint64
	i := 0
	if i < len(data) && data[i] == 1<<3|wire.Bytes {
		at := i
		i++
		prior = 1
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Group.Name", 1, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Group.Name", 1, off+i)
		}
		i += n
		m.Name = PolicyName(slab[off+i : off+i+int(l)])
		i += int(l)
		if err := m.Name.ValidateKanon(); err != nil {
			return wire.UnmarshalError(err, "Group.Name", 1, from)
		}
		if l == 0 {
			return wire.AbsentError("Group.Name", 1, off+at)
		}
	}
	if i < len(data) && data[i] == 2<<3|wire.Bytes {
		at := i
		i++
		prior = 2
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Group.Members", 2, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Group.Members", 2, off+i)
		}
		i += n
		if err := _policy_readSlicePolicyName(&m.Members, data[i:i+int(l)], slab, off+i, depth-1, "Group.Members", 2); err != nil {
			return err
		}
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Group.Members", 2, off+at)
		}
	}
	if i < len(data) && data[i] == 3<<3|wire.Varint {
		at := i
		i++
		prior = 3
		u, n := wire.Uvarint(data[i:])
		s := wire.Unzigzag(u)
		if n <= 0 || s != int64(int(s)) {
			return wire.VarintError(n, s, "int", "Group.Threshold", 3, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Group.Threshold", 3, off+i)
		}
		m.Threshold = int(s)
		i += n
		if m.Threshold == 0 {
			return wire.AbsentError("Group.Threshold", 3, off+at)
		}
	}
	if i != len(data) {
		return _policy_tagGroup(data, i, prior, off)
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Group) Reset() {
	if m == nil {
		return
	}
	m.Name = ""
	clear(m.Members[:cap(m.Members)])
	m.Members = m.Members[:0]
	m.Threshold = 0
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Group) CloneKanon() *Group {
	if m == nil {
		return nil
	}
	c := new(Group)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Group call it.
func (m *Group) cloneKanon(c *Group) {
	c.Name = PolicyName(strings.Clone(string(m.Name)))
	c.Members = _policy_cloneSlicePolicyName(m.Members)
	c.Threshold = m.Threshold
}

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Policy) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if m.Quorum != "" {
		n += 1 + wire.SizeBytes(len(m.Quorum))
	}
	if len(m.Logs) > 0 {
		n += 1 + wire.SizeBytes(_policy_sizeSliceLog(m.Logs))
	}
	if len(m.Witnesses) > 0 {
		n += 1 + wire.SizeBytes(_policy_sizeSliceWitness(m.Witnesses))
	}
	if len(m.Groups) > 0 {
		n += 1 + wire.SizeBytes(_policy_sizeSliceGroup(m.Groups))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, or a map
// has a key with a NaN component or two keys of one projection.
func (m *Policy) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, or a map has a key with a NaN component or
// two keys of one projection.
func (m *Policy) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Groups) > 0 {
		w, err := _policy_putSliceGroup(buf[:i], m.Groups, "Policy.Groups", 4)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 4<<3|wire.Bytes)
	}
	if len(m.Witnesses) > 0 {
		w, err := _policy_putSliceWitness(buf[:i], m.Witnesses, "Policy.Witnesses", 3)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 3<<3|wire.Bytes)
	}
	if len(m.Logs) > 0 {
		w, err := _policy_putSliceLog(buf[:i], m.Logs, "Policy.Logs", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if m.Quorum != "" {
		if err := m.Quorum.ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, "Policy.Quorum", 1)
		}
		i = wire.PutRaw(buf, i, m.Quorum)
		i = wire.PutUvarint(buf, i, uint64(len(m.Quorum)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, or a map has a key with
// a NaN component or two keys of one projection.
func (m *Policy) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// or a map has a key with a NaN component or two keys of one projection.
func (m *Policy) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Policy) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It accepts
// only the canonical encoding of a value, the input that EncodeKanon writes for
// it, and returns a *kanon.DecodeError that wraps kanon.ErrNotCanonical for any
// other input that the wire format lets a decoder accept. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Policy) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Policy) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Policy
// call it.
func (m *Policy) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Quorum = ""
	m.Logs = m.Logs[:0]
	m.Witnesses = m.Witnesses[:0]
	m.Groups = m.Groups[:0]
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Policy
// call it.
func (m *Policy) mergeKanon(data []byte, slab string, off, depth int) error {
	var prior uint64
	i := 0
	if i < len(data) && data[i] == 1<<3|wire.Bytes {
		at := i
		i++
		prior = 1
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Policy.Quorum", 1, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Policy.Quorum", 1, off+i)
		}
		i += n
		m.Quorum = PolicyName(slab[off+i : off+i+int(l)])
		i += int(l)
		if err := m.Quorum.ValidateKanon(); err != nil {
			return wire.UnmarshalError(err, "Policy.Quorum", 1, from)
		}
		if l == 0 {
			return wire.AbsentError("Policy.Quorum", 1, off+at)
		}
	}
	if i < len(data) && data[i] == 2<<3|wire.Bytes {
		at := i
		i++
		prior = 2
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Policy.Logs", 2, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Policy.Logs", 2, off+i)
		}
		i += n
		if err := _policy_readSliceLog(&m.Logs, data[i:i+int(l)], slab, off+i, depth-1, "Policy.Logs", 2); err != nil {
			return err
		}
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Policy.Logs", 2, off+at)
		}
	}
	if i < len(data) && data[i] == 3<<3|wire.Bytes {
		at := i
		i++
		prior = 3
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Policy.Witnesses", 3, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Policy.Witnesses", 3, off+i)
		}
		i += n
		if err := _policy_readSliceWitness(&m.Witnesses, data[i:i+int(l)], slab, off+i, depth-1, "Policy.Witnesses", 3); err != nil {
			return err
		}
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Policy.Witnesses", 3, off+at)
		}
	}
	if i < len(data) && data[i] == 4<<3|wire.Bytes {
		at := i
		i++
		prior = 4
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Policy.Groups", 4, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Policy.Groups", 4, off+i)
		}
		i += n
		if err := _policy_readSliceGroup(&m.Groups, data[i:i+int(l)], slab, off+i, depth-1, "Policy.Groups", 4); err != nil {
			return err
		}
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Policy.Groups", 4, off+at)
		}
	}
	if i != len(data) {
		return _policy_tagPolicy(data, i, prior, off)
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Policy) Reset() {
	if m == nil {
		return
	}
	m.Quorum = ""
	_policy_resetSliceLog(&m.Logs)
	_policy_resetSliceWitness(&m.Witnesses)
	_policy_resetSliceGroup(&m.Groups)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Policy) CloneKanon() *Policy {
	if m == nil {
		return nil
	}
	c := new(Policy)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Policy call it.
func (m *Policy) cloneKanon(c *Policy) {
	c.Quorum = PolicyName(strings.Clone(string(m.Quorum)))
	c.Logs = _policy_cloneSliceLog(m.Logs)
	c.Witnesses = _policy_cloneSliceWitness(m.Witnesses)
	c.Groups = _policy_cloneSliceGroup(m.Groups)
}

// ValidateKanon returns the error of x.valid. kanon encodes a value of
// PolicyName as a value of its underlying type string and calls ValidateKanon
// on every value of PolicyName that it encodes or decodes.
func (x PolicyName) ValidateKanon() error {
	return x.valid()
}

// _policy_tagLog returns the error of the canonical decode of Log for the tag
// at data[i], which begins no field after the fields that the decode read
// before it. data starts at offset off of the slab.
func _policy_tagLog(data []byte, i int, prior uint64, off int) error {
	tag, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return wire.ReadError(n, "Log", 0, off+i)
	}
	if n > 1 && data[i+n-1] == 0 {
		return wire.LongFormError(n, "Log", 0, off+i)
	}
	if tag>>3 == 0 {
		return wire.TagError(tag, "Log", 0, off+i)
	}
	if tag>>3 <= prior {
		return wire.OrderError(tag>>3, prior, "Log", 0, off+i)
	}
	switch tag >> 3 {
	case 1:
		return wire.FormatError(tag, wire.Bytes, "Log.URL", off+i)
	case 2:
		return wire.FormatError(tag, wire.Bytes, "Log.Key", off+i)
	}
	return wire.UnknownFieldError(tag>>3, "Log", 0, off+i)
}

// _policy_tagWitness returns the error of the canonical decode of Witness for
// the tag at data[i], which begins no field after the fields that the decode
// read before it. data starts at offset off of the slab.
func _policy_tagWitness(data []byte, i int, prior uint64, off int) error {
	tag, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return wire.ReadError(n, "Witness", 0, off+i)
	}
	if n > 1 && data[i+n-1] == 0 {
		return wire.LongFormError(n, "Witness", 0, off+i)
	}
	if tag>>3 == 0 {
		return wire.TagError(tag, "Witness", 0, off+i)
	}
	if tag>>3 <= prior {
		return wire.OrderError(tag>>3, prior, "Witness", 0, off+i)
	}
	switch tag >> 3 {
	case 1:
		return wire.FormatError(tag, wire.Bytes, "Witness.Name", off+i)
	case 2:
		return wire.FormatError(tag, wire.Bytes, "Witness.URL", off+i)
	case 3:
		return wire.FormatError(tag, wire.Bytes, "Witness.Key", off+i)
	}
	return wire.UnknownFieldError(tag>>3, "Witness", 0, off+i)
}

// _policy_sizeSlicePolicyName returns the length of the encoding of the
// elements of x, a []PolicyName.
func _policy_sizeSlicePolicyName(x []PolicyName) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(len(x[k]))
	}
	return n
}

// _policy_putSlicePolicyName writes the encoding of x, a []PolicyName, into the
// end of buf, which has room for it, and returns its length. It fails for a
// value that fails to encode, which loc and num locate.
func _policy_putSlicePolicyName(buf []byte, x []PolicyName, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		if err := x[k].ValidateKanon(); err != nil {
			return 0, wire.MarshalError(err, loc, num)
		}
		i = wire.PutRaw(buf, i, x[k])
		i = wire.PutUvarint(buf, i, uint64(len(x[k])))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _policy_readSlicePolicyName appends the elements that data encodes, a
// []PolicyName without its length, to *dst. data starts at offset off of slab,
// and the decode enters depth levels below the value at most. loc and num
// locate the field in errors.
func _policy_readSlicePolicyName(dst *[]PolicyName, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]PolicyName, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		x = append(x, "")
		last := len(x) - 1
		from := off + i
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, loc, num, off+i)
		}
		i += n
		x[last] = PolicyName(slab[off+i : off+i+int(l)])
		i += int(l)
		if err := x[last].ValidateKanon(); err != nil {
			return wire.UnmarshalError(err, loc, num, from)
		}
	}
	*dst = x
	return nil
}

// _policy_tagGroup returns the error of the canonical decode of Group for the
// tag at data[i], which begins no field after the fields that the decode read
// before it. data starts at offset off of the slab.
func _policy_tagGroup(data []byte, i int, prior uint64, off int) error {
	tag, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return wire.ReadError(n, "Group", 0, off+i)
	}
	if n > 1 && data[i+n-1] == 0 {
		return wire.LongFormError(n, "Group", 0, off+i)
	}
	if tag>>3 == 0 {
		return wire.TagError(tag, "Group", 0, off+i)
	}
	if tag>>3 <= prior {
		return wire.OrderError(tag>>3, prior, "Group", 0, off+i)
	}
	switch tag >> 3 {
	case 1:
		return wire.FormatError(tag, wire.Bytes, "Group.Name", off+i)
	case 2:
		return wire.FormatError(tag, wire.Bytes, "Group.Members", off+i)
	case 3:
		return wire.FormatError(tag, wire.Varint, "Group.Threshold", off+i)
	}
	return wire.UnknownFieldError(tag>>3, "Group", 0, off+i)
}

// _policy_cloneSlicePolicyName returns a copy of x, a []PolicyName, and nil for
// a nil x.
func _policy_cloneSlicePolicyName(x []PolicyName) []PolicyName {
	if x == nil {
		return nil
	}
	c := make([]PolicyName, len(x))
	for k := range x {
		c[k] = PolicyName(strings.Clone(string(x[k])))
	}
	return c
}

// _policy_sizeSliceLog returns the length of the encoding of the elements of x,
// a []Log.
func _policy_sizeSliceLog(x []Log) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(x[k].SizeKanon())
	}
	return n
}

// _policy_sizeSliceWitness returns the length of the encoding of the elements
// of x, a []Witness.
func _policy_sizeSliceWitness(x []Witness) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(x[k].SizeKanon())
	}
	return n
}

// _policy_sizeSliceGroup returns the length of the encoding of the elements of
// x, a []Group.
func _policy_sizeSliceGroup(x []Group) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(x[k].SizeKanon())
	}
	return n
}

// _policy_putSliceGroup writes the encoding of x, a []Group, into the end of
// buf, which has room for it, and returns its length. It fails for a value that
// fails to encode, which loc and num locate.
func _policy_putSliceGroup(buf []byte, x []Group, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := x[k].encodeKanon(buf[:i])
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _policy_putSliceWitness writes the encoding of x, a []Witness, into the end
// of buf, which has room for it, and returns its length. It fails for a value
// that fails to encode, which loc and num locate.
func _policy_putSliceWitness(buf []byte, x []Witness, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := x[k].encodeKanon(buf[:i])
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _policy_putSliceLog writes the encoding of x, a []Log, into the end of buf,
// which has room for it, and returns its length. It fails for a value that
// fails to encode, which loc and num locate.
func _policy_putSliceLog(buf []byte, x []Log, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := x[k].encodeKanon(buf[:i])
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _policy_readSliceLog appends the elements that data encodes, a []Log without
// its length, to *dst. data starts at offset off of slab, and the decode enters
// depth levels below the value at most. loc and num locate the field in errors.
func _policy_readSliceLog(dst *[]Log, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Log, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		if len(x) < cap(x) {
			x = x[:len(x)+1]
		} else {
			x = append(x, Log{})
		}
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, loc, num, off+i)
		}
		i += n
		if depth < 1 {
			return wire.DepthError("Log", 0, off+i)
		}
		if err := x[last].decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
			return err
		}
		i += int(l)
	}
	*dst = x
	return nil
}

// _policy_readSliceWitness appends the elements that data encodes, a []Witness
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _policy_readSliceWitness(dst *[]Witness, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Witness, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		if len(x) < cap(x) {
			x = x[:len(x)+1]
		} else {
			x = append(x, Witness{})
		}
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, loc, num, off+i)
		}
		i += n
		if depth < 1 {
			return wire.DepthError("Witness", 0, off+i)
		}
		if err := x[last].decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
			return err
		}
		i += int(l)
	}
	*dst = x
	return nil
}

// _policy_readSliceGroup appends the elements that data encodes, a []Group
// without its length, to *dst. data starts at offset off of slab, and the
// decode enters depth levels below the value at most. loc and num locate the
// field in errors.
func _policy_readSliceGroup(dst *[]Group, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Group, 0, wire.CountValues(data))
	}
	for i := 0; i < len(data); {
		if len(x) < cap(x) {
			x = x[:len(x)+1]
		} else {
			x = append(x, Group{})
		}
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, loc, num, off+i)
		}
		i += n
		if depth < 1 {
			return wire.DepthError("Group", 0, off+i)
		}
		if err := x[last].decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
			return err
		}
		i += int(l)
	}
	*dst = x
	return nil
}

// _policy_tagPolicy returns the error of the canonical decode of Policy for the
// tag at data[i], which begins no field after the fields that the decode read
// before it. data starts at offset off of the slab.
func _policy_tagPolicy(data []byte, i int, prior uint64, off int) error {
	tag, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return wire.ReadError(n, "Policy", 0, off+i)
	}
	if n > 1 && data[i+n-1] == 0 {
		return wire.LongFormError(n, "Policy", 0, off+i)
	}
	if tag>>3 == 0 {
		return wire.TagError(tag, "Policy", 0, off+i)
	}
	if tag>>3 <= prior {
		return wire.OrderError(tag>>3, prior, "Policy", 0, off+i)
	}
	switch tag >> 3 {
	case 1:
		return wire.FormatError(tag, wire.Bytes, "Policy.Quorum", off+i)
	case 2:
		return wire.FormatError(tag, wire.Bytes, "Policy.Logs", off+i)
	case 3:
		return wire.FormatError(tag, wire.Bytes, "Policy.Witnesses", off+i)
	case 4:
		return wire.FormatError(tag, wire.Bytes, "Policy.Groups", off+i)
	}
	return wire.UnknownFieldError(tag>>3, "Policy", 0, off+i)
}

// _policy_resetSliceLog empties the []Log that x points at and resets every
// element of its capacity, which keeps its memory for the next decode.
func _policy_resetSliceLog(x *[]Log) {
	s := (*x)[:cap(*x)]
	for k := range s {
		s[k].Reset()
	}
	*x = (*x)[:0]
}

// _policy_resetSliceWitness empties the []Witness that x points at and resets
// every element of its capacity, which keeps its memory for the next decode.
func _policy_resetSliceWitness(x *[]Witness) {
	s := (*x)[:cap(*x)]
	for k := range s {
		s[k].Reset()
	}
	*x = (*x)[:0]
}

// _policy_resetSliceGroup empties the []Group that x points at and resets every
// element of its capacity, which keeps its memory for the next decode.
func _policy_resetSliceGroup(x *[]Group) {
	s := (*x)[:cap(*x)]
	for k := range s {
		s[k].Reset()
	}
	*x = (*x)[:0]
}

// _policy_cloneSliceLog returns a copy of x, a []Log, and nil for a nil x.
func _policy_cloneSliceLog(x []Log) []Log {
	if x == nil {
		return nil
	}
	c := make([]Log, len(x))
	for k := range x {
		x[k].cloneKanon(&c[k])
	}
	return c
}

// _policy_cloneSliceWitness returns a copy of x, a []Witness, and nil for a nil
// x.
func _policy_cloneSliceWitness(x []Witness) []Witness {
	if x == nil {
		return nil
	}
	c := make([]Witness, len(x))
	for k := range x {
		x[k].cloneKanon(&c[k])
	}
	return c
}

// _policy_cloneSliceGroup returns a copy of x, a []Group, and nil for a nil x.
func _policy_cloneSliceGroup(x []Group) []Group {
	if x == nil {
		return nil
	}
	c := make([]Group, len(x))
	for k := range x {
		x[k].cloneKanon(&c[k])
	}
	return c
}
