// Code generated by kanon. DO NOT EDIT.
// source: policy.go

package checkpoint

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecLog describes Log to the conformance suite.
var kanonSpecLog = kanontest.Spec[Log]{
	Fields: []kanontest.Field{
		{Name: "URL", Number: 1},
		{Name: "Key", Number: 2},
	},
	Canonical: true,
}

// TestKanonLog runs the conformance suite on Log.
func TestKanonLog(t *testing.T) {
	kanontest.Run(t, kanonSpecLog)
}

// BenchmarkKanonLog measures the codec of Log.
func BenchmarkKanonLog(b *testing.B) {
	kanontest.Bench(b, kanonSpecLog)
}

// FuzzKanonLog fuzzes the decode of Log.
func FuzzKanonLog(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecLog)
}

// kanonSpecWitness describes Witness to the conformance suite.
var kanonSpecWitness = kanontest.Spec[Witness]{
	Fields: []kanontest.Field{
		{Name: "Name", Number: 1},
		{Name: "URL", Number: 2},
		{Name: "Key", Number: 3},
	},
	Canonical: true,
}

// TestKanonWitness runs the conformance suite on Witness.
func TestKanonWitness(t *testing.T) {
	kanontest.Run(t, kanonSpecWitness)
}

// BenchmarkKanonWitness measures the codec of Witness.
func BenchmarkKanonWitness(b *testing.B) {
	kanontest.Bench(b, kanonSpecWitness)
}

// FuzzKanonWitness fuzzes the decode of Witness.
func FuzzKanonWitness(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecWitness)
}

// kanonSpecGroup describes Group to the conformance suite.
var kanonSpecGroup = kanontest.Spec[Group]{
	Fields: []kanontest.Field{
		{Name: "Name", Number: 1},
		{Name: "Members", Number: 2},
		{Name: "Threshold", Number: 3},
	},
	Canonical: true,
}

// TestKanonGroup runs the conformance suite on Group.
func TestKanonGroup(t *testing.T) {
	kanontest.Run(t, kanonSpecGroup)
}

// BenchmarkKanonGroup measures the codec of Group.
func BenchmarkKanonGroup(b *testing.B) {
	kanontest.Bench(b, kanonSpecGroup)
}

// FuzzKanonGroup fuzzes the decode of Group.
func FuzzKanonGroup(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecGroup)
}

// kanonSpecPolicy describes Policy to the conformance suite.
var kanonSpecPolicy = kanontest.Spec[Policy]{
	Fields: []kanontest.Field{
		{Name: "Quorum", Number: 1},
		{Name: "Logs", Number: 2},
		{Name: "Witnesses", Number: 3},
		{Name: "Groups", Number: 4},
	},
	Canonical: true,
}

// TestKanonPolicy runs the conformance suite on Policy.
func TestKanonPolicy(t *testing.T) {
	kanontest.Run(t, kanonSpecPolicy)
}

// BenchmarkKanonPolicy measures the codec of Policy.
func BenchmarkKanonPolicy(b *testing.B) {
	kanontest.Bench(b, kanonSpecPolicy)
}

// FuzzKanonPolicy fuzzes the decode of Policy.
func FuzzKanonPolicy(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecPolicy)
}

// TestKanonPolicyName runs the conformance suite on PolicyName.
func TestKanonPolicyName(t *testing.T) {
	kanontest.RunValue[PolicyName](t)
}
