// Code generated by kanon. DO NOT EDIT.
// source: name.go

package note

import (
	"go.thesmos.sh/kanon"
)

// The file compiles against a runtime that supports version 3 of the generator.
const (
	_ = kanon.EnforceVersion(3 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 3)
)

// ValidateKanon returns the error of x.valid. kanon encodes a value of Name as
// a value of its underlying type string and calls ValidateKanon on every value
// of Name that it encodes or decodes.
func (x Name) ValidateKanon() error {
	return x.valid()
}
