// Code generated by kanon. DO NOT EDIT.
// source: name.go

package note

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// TestKanonName runs the conformance suite on Name.
func TestKanonName(t *testing.T) {
	kanontest.RunValue[Name](t)
}
