// Code generated by kanon. DO NOT EDIT.
// source: note.go

//kanon:numbers Note Text=1 Signatures=2

package note

import (
	"io"
	"slices"

	"go.thesmos.sh/kanon"
	"go.thesmos.sh/kanon/wire"
)

// The file compiles against a runtime that supports version 4 of the generator.
const (
	_ = kanon.EnforceVersion(4 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 4)
)

// The generated types implement kanon.Cloner.
var (
	_ kanon.Cloner[Note] = (*Note)(nil)
)

// SizeKanon returns the length of the encoding of m in bytes, and 0 for a
// nil m.
func (m *Note) SizeKanon() int {
	if m == nil {
		return 0
	}
	n := 0
	if len(m.Text) > 0 {
		n += 1 + wire.SizeBytes(len(m.Text))
	}
	if len(m.Signatures) > 0 {
		n += 1 + wire.SizeBytes(_note_sizeSliceSignature(m.Signatures))
	}
	return n
}

// EncodeKanon writes the encoding of m into the last SizeKanon bytes of buf and
// returns their count. A nil m writes nothing. When buf is shorter than
// SizeKanon bytes, EncodeKanon writes nothing and returns io.ErrShortBuffer. It
// fails when the value of a field fails to encode: a type that encodes itself
// returns an error, ValidateKanon of a type rejects a value, an interface
// stores a type that the tag option types of its field does not list, a map has
// a key with a NaN component or two keys of one projection, or a slice or a map
// has more elements than the tag option max of its field allows.
func (m *Note) EncodeKanon(buf []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	if len(buf) < m.SizeKanon() {
		return 0, io.ErrShortBuffer
	}
	return m.encodeKanon(buf)
}

// encodeKanon writes the encoding of m into the end of buf, which has room for
// it, and returns its length. The encoding methods of m and of the structs of
// the package that contain one call it. It fails when the value of a field
// fails to encode: a type that encodes itself returns an error, ValidateKanon
// of a type rejects a value, an interface stores a type that the tag option
// types of its field does not list, a map has a key with a NaN component or two
// keys of one projection, or a slice or a map has more elements than the tag
// option max of its field allows.
func (m *Note) encodeKanon(buf []byte) (int, error) {
	i := len(buf)
	if len(m.Signatures) > 0 {
		w, err := _note_putSliceSignature(buf[:i], m.Signatures, "Note.Signatures", 2)
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutTag(buf, i, 2<<3|wire.Bytes)
	}
	if len(m.Text) > 0 {
		i = wire.PutRaw(buf, i, m.Text)
		i = wire.PutUvarint(buf, i, uint64(len(m.Text)))
		i = wire.PutTag(buf, i, 1<<3|wire.Bytes)
	}
	return len(buf) - i, nil
}

// AppendBinary appends the encoding of m to b and returns the extended slice.
// It does not allocate when b has SizeKanon bytes of spare capacity. It fails
// when the value of a field fails to encode: a type that encodes itself returns
// an error, ValidateKanon of a type rejects a value, an interface stores a type
// that the tag option types of its field does not list, a map has a key with a
// NaN component or two keys of one projection, or a slice or a map has more
// elements than the tag option max of its field allows.
func (m *Note) AppendBinary(b []byte) ([]byte, error) {
	if m == nil {
		return b, nil
	}
	size := m.SizeKanon()
	out := slices.Grow(b, size)[:len(b)+size]
	if _, err := m.encodeKanon(out); err != nil {
		return b, err
	}
	return out, nil
}

// MarshalBinary returns the encoding of m in a new slice, and nil for an empty
// encoding. It fails when the value of a field fails to encode: a type that
// encodes itself returns an error, ValidateKanon of a type rejects a value, an
// interface stores a type that the tag option types of its field does not list,
// a map has a key with a NaN component or two keys of one projection, or a
// slice or a map has more elements than the tag option max of its field allows.
func (m *Note) MarshalBinary() ([]byte, error) {
	return m.AppendBinary(nil)
}

// UnmarshalBinary sets m to the value encoded in data, as DecodeKanon does with
// the zero Options, which copy data once.
func (m *Note) UnmarshalBinary(data []byte) error {
	return m.DecodeKanon(data, kanon.Options{})
}

// DecodeKanon sets m to the value encoded in data and reuses the memory of m:
// the values that its pointers point at, its nested structs, the capacity of
// its slices and maps, and up to 16 values of each map whose values refer to
// memory. It first clears the fields that the encoding leaves out, as Reset
// does. Every decoded string is a substring of the slab of opts. It accepts
// only the canonical encoding of a value, the input that EncodeKanon writes for
// it, and returns a *kanon.DecodeError that wraps kanon.ErrNotCanonical for any
// other input that the wire format lets a decoder accept. It returns a
// *kanon.DecodeError for malformed input, after which m contains the fields
// decoded before the error.
func (m *Note) DecodeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.decodeKanon(data, slab, off, opts.Limit())
}

// MergeKanon decodes data into m without resetting m first, with the options
// and the errors of DecodeKanon. A slice appends the elements in data, a map
// adds its entries, a nested struct merges, an interface that stores the
// concrete type in data merges as that type merges, a union member replaces the
// union, and any other field takes the value in data. The fields that the
// encoding leaves out keep their values.
func (m *Note) MergeKanon(data []byte, opts kanon.Options) error {
	slab, off := opts.Source(data)
	return m.mergeKanon(data, slab, off, opts.Limit())
}

// decodeKanon sets m to the value encoded in data, which starts at offset off
// of slab, as DecodeKanon does. The decode enters depth levels below m at most.
// DecodeKanon and the decode of the structs of the package that contain Note
// call it.
func (m *Note) decodeKanon(data []byte, slab string, off, depth int) error {
	m.Text = m.Text[:0]
	m.Signatures = m.Signatures[:0]
	return m.mergeKanon(data, slab, off, depth)
}

// mergeKanon merges the encoding in data, which starts at offset off of slab,
// into m, as MergeKanon does. The decode enters depth levels below m at most.
// MergeKanon and the decode of the structs of the package that contain Note
// call it.
func (m *Note) mergeKanon(data []byte, slab string, off, depth int) error {
	var prior uint64
	i := 0
	if i < len(data) && data[i] == 1<<3|wire.Bytes {
		at := i
		i++
		prior = 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Note.Text", 1, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Note.Text", 1, off+i)
		}
		i += n
		m.Text = append(m.Text[:0], data[i:i+int(l)]...)
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Note.Text", 1, off+at)
		}
	}
	if i < len(data) && data[i] == 2<<3|wire.Bytes {
		at := i
		i++
		prior = 2
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, "Note.Signatures", 2, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, "Note.Signatures", 2, off+i)
		}
		i += n
		if err := _note_readSliceSignature(&m.Signatures, data[i:i+int(l)], slab, off+i, depth-1, "Note.Signatures", 2); err != nil {
			return err
		}
		i += int(l)
		if l == 0 {
			return wire.AbsentError("Note.Signatures", 2, off+at)
		}
	}
	if i != len(data) {
		return _note_tagNote(data, i, prior, off)
	}
	return nil
}

// Reset clears every field of m, the fields that the encoding leaves out
// included. An encoded pointer or interface becomes nil. An encoded slice or
// map becomes empty and keeps its storage for a decode to reuse, with every
// element in the capacity of a slice reset, so that no decoded content remains
// in m or in the storage that it keeps.
func (m *Note) Reset() {
	if m == nil {
		return
	}
	clear(m.Text[:cap(m.Text)])
	m.Text = m.Text[:0]
	_note_resetSliceSignature(&m.Signatures)
}

// CloneKanon returns a copy of m that shares no memory with m or with the slab
// that m decoded from: its strings, slices, maps and the values of its pointers
// and interfaces are copies. The copy has the fields of the encoding, the union
// discriminators and the unknown fields of m, and the zero value in every other
// field, map keys included. A nil m returns nil.
func (m *Note) CloneKanon() *Note {
	if m == nil {
		return nil
	}
	c := new(Note)
	m.cloneKanon(c)
	return c
}

// cloneKanon copies m into c, as CloneKanon does. The fields of c that the copy
// does not set keep their values. CloneKanon and the clone of the structs of
// the package that contain Note call it.
func (m *Note) cloneKanon(c *Note) {
	c.Text = slices.Clone(m.Text)
	c.Signatures = _note_cloneSliceSignature(m.Signatures)
}

// _note_sizeSliceSignature returns the length of the encoding of the elements
// of x, a []Signature.
func _note_sizeSliceSignature(x []Signature) int {
	n := 0
	for k := range x {
		n += wire.SizeBytes(x[k].SizeKanon())
	}
	return n
}

// _note_putSliceSignature writes the encoding of x, a []Signature, into the end
// of buf, which has room for it, and returns its length. It fails for a value
// that fails to encode, which loc and num locate.
func _note_putSliceSignature(buf []byte, x []Signature, loc string, num int) (int, error) {
	i := len(buf)
	for k := len(x) - 1; k >= 0; k-- {
		w, err := x[k].encodeKanon(buf[:i])
		if err != nil {
			return 0, err
		}
		i -= w
		i = wire.PutUvarint(buf, i, uint64(w))
	}
	i = wire.PutUvarint(buf, i, uint64(len(buf)-i))
	return len(buf) - i, nil
}

// _note_readSliceSignature appends the elements that data encodes, a
// []Signature without its length, to *dst. data starts at offset off of slab,
// and the decode enters depth levels below the value at most. loc and num
// locate the field in errors.
func _note_readSliceSignature(dst *[]Signature, data []byte, slab string, off, depth int, loc string, num int) error {
	if depth < 0 {
		return wire.DepthError(loc, num, off)
	}
	x := *dst
	if x == nil && len(data) > 0 {
		x = make([]Signature, 0, wire.SliceCap[Signature](wire.CountValues(data)))
	}
	for i := 0; i < len(data); {
		if len(x) < cap(x) {
			x = x[:len(x)+1]
		} else {
			x = append(x, Signature{})
		}
		last := len(x) - 1
		l, n := wire.Uvarint(data[i:])
		if n <= 0 || uint64(len(data)-i-n) < l {
			return wire.ReadError(n, loc, num, off+i)
		}
		if n > 1 && data[i+n-1] == 0 {
			return wire.LongFormError(n, loc, num, off+i)
		}
		i += n
		if depth < 1 {
			return wire.DepthError("Signature", 0, off+i)
		}
		if err := x[last].decodeKanon(data[i:i+int(l)], slab, off+i, depth-1); err != nil {
			return err
		}
		i += int(l)
	}
	*dst = x
	return nil
}

// _note_tagNote returns the error of the canonical decode of Note for the tag
// at data[i], which begins no field after the fields that the decode read
// before it. data starts at offset off of the slab.
func _note_tagNote(data []byte, i int, prior uint64, off int) error {
	tag, n := wire.Uvarint(data[i:])
	if n <= 0 {
		return wire.ReadError(n, "Note", 0, off+i)
	}
	if n > 1 && data[i+n-1] == 0 {
		return wire.LongFormError(n, "Note", 0, off+i)
	}
	if tag>>3 == 0 {
		return wire.TagError(tag, "Note", 0, off+i)
	}
	if tag>>3 <= prior {
		return wire.OrderError(tag>>3, prior, "Note", 0, off+i)
	}
	switch tag >> 3 {
	case 1:
		return wire.FormatError(tag, wire.Bytes, "Note.Text", off+i)
	case 2:
		return wire.FormatError(tag, wire.Bytes, "Note.Signatures", off+i)
	}
	return wire.UnknownFieldError(tag>>3, "Note", 0, off+i)
}

// _note_resetSliceSignature empties the []Signature that x points at and resets
// every element of its capacity, which keeps its memory for the next decode.
func _note_resetSliceSignature(x *[]Signature) {
	s := (*x)[:cap(*x)]
	for k := range s {
		s[k].Reset()
	}
	*x = (*x)[:0]
}

// _note_cloneSliceSignature returns a copy of x, a []Signature, and nil for a
// nil x.
func _note_cloneSliceSignature(x []Signature) []Signature {
	if x == nil {
		return nil
	}
	c := make([]Signature, len(x))
	for k := range x {
		x[k].cloneKanon(&c[k])
	}
	return c
}
