// Code generated by kanon. DO NOT EDIT.
// source: type.go

package note

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// TestKanonType runs the conformance suite on Type.
func TestKanonType(t *testing.T) {
	kanontest.RunValue[Type](t)
}
