// Code generated by kanon. DO NOT EDIT.
// source: class.go

package errs

import (
	"go.thesmos.sh/kanon"
)

// The file compiles against a runtime that supports version 2 of the generator.
const (
	_ = kanon.EnforceVersion(2 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 2)
)

// ValidateKanon returns the error of x.valid. kanon encodes a value of Class as
// a value of its underlying type uint8, ahead of the text methods of Class, and
// calls ValidateKanon on every value of Class that it encodes or decodes.
func (x Class) ValidateKanon() error {
	return x.valid()
}
