// Code generated by kanon. DO NOT EDIT.
// source: binary.go

package epoch

import (
	"go.thesmos.sh/kanon"
)

// The file compiles against a runtime that supports version 3 of the generator.
const (
	_ = kanon.EnforceVersion(3 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 3)
)

// ValidateKanon returns nil, since every value of Epoch is valid. kanon encodes
// a value of Epoch as a value of its underlying type uint64, ahead of the
// binary methods of Epoch, and does not call ValidateKanon on a value of Epoch
// that it encodes or decodes.
func (Epoch) ValidateKanon() error {
	return nil
}
