// Code generated by kanon. DO NOT EDIT.
// source: binary.go

package fixed

import (
	"go.thesmos.sh/kanon"
)

// The file compiles against a runtime that supports version 1 of the generator.
const (
	_ = kanon.EnforceVersion(1 - kanon.MinVersion)
	_ = kanon.EnforceVersion(kanon.MaxVersion - 1)
)

// ValidateKanon returns the error of x.valid. kanon encodes a value of Fixed64
// as a value of its underlying type int64, ahead of the binary methods of
// Fixed64, and calls ValidateKanon on every value of Fixed64 that it encodes or
// decodes.
func (x Fixed64) ValidateKanon() error {
	return x.valid()
}
