// Code generated by testkit stub. DO NOT EDIT.
// Source: rand.go:35-48 (testkit stub Rand)

package randtest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/randtest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestRandStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("Rand-stub-test")

	t.Run("Read default returns zero", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		n, err := s.Read(nil)
		testkit.Equal(t, n, 0, "Read must return zero")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("Read fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnRead.Faults(errTest, 1)
		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Read Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnRead.Func(func([]byte) (int, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnRead.Faults(errTest, 1)
		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Read counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnRead.Faults(errTest, 3)
		_, err1 := s.Read(nil)
		_, err2 := s.Read(nil)
		_, err3 := s.Read(nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Read Func override", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		called := false
		s.OnRead.Func(func([]byte) (int, error) {
			called = true
			return 42, nil
		})
		n, err := s.Read(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, n, 42, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Read Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnRead.Returns(42, nil)
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Read records calls", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		_, _ = s.Read(nil)
		s.OnRead.AssertCalledOnce(t, "must record Read call")
	})

	t.Run("WithRandRead constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := randtest.NewRandStub(t, randtest.WithRandRead(func([]byte) (int, error) {
			called = true
			return 0, nil
		}))
		_, _ = s.Read(nil)
		testkit.True(t, called, "WithRandRead must be called")
	})

	t.Run("Read records call args", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		_, _ = s.Read([]byte{42})
		call := s.OnRead.LastCall(t)
		testkit.Equal(t, call.P, []byte{42}, "P must be recorded")
	})

	t.Run("Read OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		var observed []randtest.RandReadCall
		s.OnRead.OnRecord(func(c randtest.RandReadCall) {
			observed = append(observed, c)
		})
		_, _ = s.Read(nil)
		_, _ = s.Read(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Read call")
	})

	t.Run("Uint64 default returns zero", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		result := s.Uint64()
		testkit.Equal(t, result, 0, "Uint64 must return zero")
	})

	t.Run("Uint64 Func override", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		called := false
		s.OnUint64.Func(func() uint64 {
			called = true
			return 42
		})
		result := s.Uint64()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, 42, "Func must return set value")
	})

	t.Run("Uint64 Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnUint64.Returns(42)
		result := s.Uint64()
		testkit.Equal(t, result, 42, "Returns must return set value")
	})

	t.Run("Uint64 records calls", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		_ = s.Uint64()
		s.OnUint64.AssertCalledOnce(t, "must record Uint64 call")
	})

	t.Run("WithRandUint64 constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := randtest.NewRandStub(t, randtest.WithRandUint64(func() uint64 {
			called = true
			return 0
		}))
		_ = s.Uint64()
		testkit.True(t, called, "WithRandUint64 must be called")
	})

	t.Run("Uint64 OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		var observed []randtest.RandUint64Call
		s.OnUint64.OnRecord(func(c randtest.RandUint64Call) {
			observed = append(observed, c)
		})
		_ = s.Uint64()
		_ = s.Uint64()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Uint64 call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t, randtest.RandStubBenchMode())
		_, _ = s.Read(nil)
		testkit.Equal(t, s.OnRead.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t, randtest.RandStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := randtest.NewRandStub(f)
		s.OnRead.Times(2)
		_, _ = s.Read(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := randtest.NewRandStub(f)
		s.OnRead.TimesAtLeast(3)
		_, _ = s.Read(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		_, _ = s.Read(nil)
		_ = s.Uint64()
		s.ResetCalls()
		s.OnRead.AssertNotCalled(t, "Read must be cleared after ResetCalls")
		s.OnUint64.AssertNotCalled(t, "Uint64 must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Read", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := randtest.NewRandStub(f, randtest.RandStubStrict())
		_, _ = s.Read(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Read")
	})

	t.Run("Strict mode fails on unconfigured Uint64", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := randtest.NewRandStub(f, randtest.RandStubStrict())
		_ = s.Uint64()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Uint64")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := randtest.NewRandStub(t)
		inner.OnRead.Returns(0, nil)
		inner.OnUint64.Returns(0)
		s := randtest.NewRandStub(t, randtest.RandStubDelegateTo(inner))
		_, _ = s.Read(nil)
		_ = s.Uint64()
		s.OnRead.AssertCalledOnce(t, "Read must delegate")
		s.OnUint64.AssertCalledOnce(t, "Uint64 must delegate")
	})

	t.Run("DelegateTo surfaces Read return values", func(t *testing.T) {
		t.Parallel()
		inner := randtest.NewRandStub(t)
		inner.OnRead.Returns(42, nil)
		s := randtest.NewRandStub(t, randtest.RandStubDelegateTo(inner))
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Read must return configured value")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("DelegateTo surfaces Uint64 return values", func(t *testing.T) {
		t.Parallel()
		inner := randtest.NewRandStub(t)
		inner.OnUint64.Returns(42)
		s := randtest.NewRandStub(t, randtest.RandStubDelegateTo(inner))
		result := s.Uint64()
		testkit.Equal(t, result, 42, "Uint64 must return configured value")
	})

	t.Run("ResetCalls preserves Read Returns config", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnRead.Returns(42, nil)
		_, _ = s.Read(nil)
		s.ResetCalls()
		s.OnRead.AssertNotCalled(t, "ResetCalls must clear recordings")
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Read must return configured value")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("ResetCalls preserves Uint64 Returns config", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		s.OnUint64.Returns(42)
		_ = s.Uint64()
		s.ResetCalls()
		s.OnUint64.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Uint64()
		testkit.Equal(t, result, 42, "Uint64 must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := randtest.NewRandStub(t)
		_, _ = s.Read(nil)
		testkit.Len(t, s.OnRead.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnRead.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("Read FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := randtest.NewRandStub(t, randtest.RandStubWithClock(clk))
		s.OnRead.FaultsFor(5*time.Second, errTest)

		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, err = s.Read(nil)
		testkit.NoError(t, err, "Read must succeed after window expires")
	})
}

func TestRandStubBenchModeZeroAlloc(t *testing.T) {
	s := randtest.NewRandStub(nil, randtest.RandStubBenchMode())
	s.OnRead.Returns(0, nil)
	s.OnUint64.Returns(0)

	t.Run("Read", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Read(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Read in BenchMode must be 0 alloc")
	})

	t.Run("Uint64", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Uint64()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Uint64 in BenchMode must be 0 alloc")
	})

}
