// Code generated by testkit stub. DO NOT EDIT.
// Source: rand.go:35-48 (testkit stub Rand)

package randtest

import (
	"testing"

	rand2 "go.thesmos.sh/core/rand"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ rand2.Rand = (*RandStub)(nil)

// --- Call types ---

// RandReadCall records one invocation of rand2.Rand.Read.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type RandReadCall struct {
	P   []byte
	N   int
	Err error
}

// RandUint64Call records one invocation of rand2.Rand.Uint64.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type RandUint64Call struct {
	Result uint64
}

// --- Per-method stubs ---

// RandReadStub controls behavior and records calls for Read.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type RandReadStub struct {
	*stub.MethodStub[RandReadCall]
	fn       func([]byte) (int, error)
	fallback *randReadReturn
}

type randReadReturn struct {
	N   int
	Err error
}

// Returns sets a fixed return value for Read.
func (s *RandReadStub) Returns(n int, err error) *RandReadStub {
	s.fallback = &randReadReturn{N: n, Err: err}
	return s
}

// Func sets a function override for Read.
func (s *RandReadStub) Func(fn func([]byte) (int, error)) *RandReadStub {
	s.fn = fn
	return s
}

// RandUint64Stub controls behavior and records calls for Uint64.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type RandUint64Stub struct {
	*stub.MethodStub[RandUint64Call]
	fn       func() uint64
	fallback *randUint64Return
}

type randUint64Return struct {
	Result uint64
}

// Returns sets a fixed return value for Uint64.
func (s *RandUint64Stub) Returns(result uint64) *RandUint64Stub {
	s.fallback = &randUint64Return{Result: result}
	return s
}

// Func sets a function override for Uint64.
func (s *RandUint64Stub) Func(fn func() uint64) *RandUint64Stub {
	s.fn = fn
	return s
}

// --- RandStub ---

// RandStubOption configures a [RandStub] at construction time.
type RandStubOption func(*RandStub)

// RandStubStrict enables strict mode — unconfigured methods fail the test.
func RandStubStrict() RandStubOption {
	return func(s *RandStub) { s.strict = true }
}

// RandStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func RandStubDelegateTo(impl rand2.Rand) RandStubOption {
	return func(s *RandStub) {
		s.OnRead.Func(impl.Read)
		s.OnUint64.Func(impl.Uint64)
	}
}

// RandStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func RandStubWithClock(clk clock.Clock) RandStubOption {
	return func(s *RandStub) {
		s.OnRead.WithClock(clk)
		s.OnUint64.WithClock(clk)
	}
}

// RandStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func RandStubWithRandSource(src rand.Source) RandStubOption {
	return func(s *RandStub) {
		s.OnRead.WithRandSource(src)
		s.OnUint64.WithRandSource(src)
	}
}

// RandStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func RandStubBenchMode() RandStubOption {
	return func(s *RandStub) {
		s.OnRead.BenchMode()
		s.OnUint64.BenchMode()
	}
}

// WithRandRead sets a function override at construction time.
func WithRandRead(fn func([]byte) (int, error)) RandStubOption {
	return func(s *RandStub) { s.OnRead.Func(fn) }
}

// WithRandUint64 sets a function override at construction time.
func WithRandUint64(fn func() uint64) RandStubOption {
	return func(s *RandStub) { s.OnUint64.Func(fn) }
}

// RandStub is a configurable test double for [rand2.Rand].
type RandStub struct {
	OnRead   *RandReadStub
	OnUint64 *RandUint64Stub
	strict   bool
}

// NewRandStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewRandStub(tb testing.TB, opts ...RandStubOption) *RandStub {
	s := &RandStub{
		OnRead:   &RandReadStub{MethodStub: stub.NewMethodStub[RandReadCall](tb, "Rand.Read")},
		OnUint64: &RandUint64Stub{MethodStub: stub.NewMethodStub[RandUint64Call](tb, "Rand.Uint64")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnRead.Strict()
		s.OnUint64.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnRead.Verify()
				s.OnUint64.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *RandStub) ResetCalls() {
	s.OnRead.Reset()
	s.OnUint64.Reset()
}

// --- Interface method implementations ---

func (s *RandStub) Read(p []byte) (int, error) {
	s.OnRead.SleepLatency()
	call := RandReadCall{P: p}
	if fired, faultErr := s.OnRead.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnRead.Record(call)
		return 0, faultErr
	}
	if s.OnRead.fn != nil {
		r0, r1 := s.OnRead.fn(p)
		call.N = r0
		call.Err = r1
		s.OnRead.Record(call)
		return r0, r1
	}
	if s.OnRead.fallback != nil {
		f := s.OnRead.fallback
		call.N = f.N
		call.Err = f.Err
		s.OnRead.Record(call)
		return f.N, f.Err
	}
	s.OnRead.FailUnexpectedCall(call)
	s.OnRead.Record(call)
	return 0, nil
}

func (s *RandStub) Uint64() uint64 {
	s.OnUint64.SleepLatency()
	call := RandUint64Call{}
	if s.OnUint64.fn != nil {
		r0 := s.OnUint64.fn()
		call.Result = r0
		s.OnUint64.Record(call)
		return r0
	}
	if s.OnUint64.fallback != nil {
		f := s.OnUint64.fallback
		call.Result = f.Result
		s.OnUint64.Record(call)
		return f.Result
	}
	s.OnUint64.FailUnexpectedCall(call)
	s.OnUint64.Record(call)
	return 0
}
