// Code generated by testkit suite. DO NOT EDIT.
// Source: rand.go:35-48 (testkit suite Rand)

package randtest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/rand"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertRandContract runs conformance assertions against
// implementations of [rand.Rand] produced by factory.
//
//	Default subtests: 3 across 2 methods
//	Shapes detected:  Pure (Uint64), Unknown (Read)
//	Directives:       none
//	Plug-in points:   RandOnRead, RandOnUint64, RandOnAll, RandCustom
func AssertRandContract(
	t *testing.T,
	factory func() rand.Rand,
	opts ...RandOption,
) {
	t.Helper()
	cfg := newRandConfig(opts...)

	runRandRead(t, factory, &cfg)
	runRandUint64(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[rand.Rand]{
			T:             t,
			CrossBindings: bindings.CrossBindings[rand.Rand]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runRandRead(t *testing.T, factory func() rand.Rand, cfg *randConfig) {
	t.Helper()

	t.Run("Read/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Read panicked on zero-value args (%v) — supply sample values via RandOnRead", r)
			}
		}()
		s := factory()
		_, _ = s.Read(nil)
	})

	t.Run("Read/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Read(nil)
		})
	})
	if len(cfg.onRead) > 0 {
		t.Run("Read", func(t *testing.T) {
			for _, fn := range cfg.onRead {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runRandUint64(t *testing.T, factory func() rand.Rand, cfg *randConfig) {
	t.Helper()

	t.Run("Uint64/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Uint64 panicked on zero-value args (%v) — supply sample values via RandOnUint64", r)
			}
		}()
		s := factory()
		_ = s.Uint64()
	})
	if len(cfg.onUint64) > 0 {
		t.Run("Uint64", func(t *testing.T) {
			prePopFactory := func() rand.Rand {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[rand.Rand, uint64]{
				T: t,
				PureBindings: bindings.PureBindings[rand.Rand, uint64]{
					Factory: prePopFactory,
					Call: func(impl rand.Rand) uint64 {
						return impl.Uint64()
					},
				},
			}
			for _, a := range cfg.onUint64 {
				a(pctx)
			}
		})
	}
}

// RandOption configures [AssertRandContract].
type RandOption func(*randConfig)

// RandPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func RandPrePopulate(fn func(ctx context.Context, s rand.Rand)) RandOption {
	return func(c *randConfig) { c.prePopulate = fn }
}

// RandCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func RandCustom(name string, fn func(*testing.T, rand.Rand)) RandOption {
	return func(c *randConfig) {
		c.custom = append(c.custom, randCustomSubtest{name: name, fn: fn})
	}
}

// RandOnRead adds plug-in assertions for the Read method.
func RandOnRead(assertions ...func(*testing.T, rand.Rand)) RandOption {
	return func(c *randConfig) {
		c.onRead = append(c.onRead, assertions...)
	}
}

// RandOnUint64 adds plug-in assertions for the Uint64 method.
func RandOnUint64(assertions ...suite.PureAssertion[rand.Rand, uint64]) RandOption {
	return func(c *randConfig) {
		c.onUint64 = append(c.onUint64, assertions...)
	}
}

// RandOnAll adds cross-method assertions that span multiple methods.
func RandOnAll(assertions ...suite.CrossMethodAssertion[rand.Rand]) RandOption {
	return func(c *randConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type randCustomSubtest struct {
	name string
	fn   func(*testing.T, rand.Rand)
}

type randConfig struct {
	prePopulate func(context.Context, rand.Rand)
	custom      []randCustomSubtest
	onAll       []suite.CrossMethodAssertion[rand.Rand]
	onRead      []func(*testing.T, rand.Rand)
	onUint64    []suite.PureAssertion[rand.Rand, uint64]
}

func newRandConfig(opts ...RandOption) randConfig {
	var cfg randConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
