// Code generated by testkit stub. DO NOT EDIT.
// Source: aead.go:47-97 (testkit stub AEAD)

package cryptotest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestAEADStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("AEAD-stub-test")

	t.Run("Algorithm default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result := s.Algorithm()
		testkit.Equal(t, result, "", "Algorithm must return zero")
	})

	t.Run("Algorithm Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnAlgorithm.Func(func() crypto.Algorithm {
			called = true
			return crypto.Algorithm("test-result")
		})
		result := s.Algorithm()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Func must return set value")
	})

	t.Run("Algorithm Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Returns must return set value")
	})

	t.Run("Algorithm records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Algorithm()
		s.OnAlgorithm.AssertCalledOnce(t, "must record Algorithm call")
	})

	t.Run("WithAEADAlgorithm constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADAlgorithm(func() crypto.Algorithm {
			called = true
			return ""
		}))
		_ = s.Algorithm()
		testkit.True(t, called, "WithAEADAlgorithm must be called")
	})

	t.Run("Algorithm OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADAlgorithmCall
		s.OnAlgorithm.OnRecord(func(c cryptotest.AEADAlgorithmCall) {
			observed = append(observed, c)
		})
		_ = s.Algorithm()
		_ = s.Algorithm()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Algorithm call")
	})

	t.Run("ID default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result := s.ID()
		testkit.Equal(t, result, crypto.ID{}, "ID must return zero")
	})

	t.Run("ID Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnID.Func(func() crypto.ID {
			called = true
			return [16]byte{1}
		})
		result := s.ID()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, [16]byte{1}, "Func must return set value")
	})

	t.Run("ID Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnID.Returns([16]byte{1})
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "Returns must return set value")
	})

	t.Run("ID records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.ID()
		s.OnID.AssertCalledOnce(t, "must record ID call")
	})

	t.Run("WithAEADID constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADID(func() crypto.ID {
			called = true
			return crypto.ID{}
		}))
		_ = s.ID()
		testkit.True(t, called, "WithAEADID must be called")
	})

	t.Run("ID OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADIDCall
		s.OnID.OnRecord(func(c cryptotest.AEADIDCall) {
			observed = append(observed, c)
		})
		_ = s.ID()
		_ = s.ID()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every ID call")
	})

	t.Run("NonceSize default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result := s.NonceSize()
		testkit.Equal(t, result, 0, "NonceSize must return zero")
	})

	t.Run("NonceSize Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnNonceSize.Func(func() int {
			called = true
			return 42
		})
		result := s.NonceSize()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, 42, "Func must return set value")
	})

	t.Run("NonceSize Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnNonceSize.Returns(42)
		result := s.NonceSize()
		testkit.Equal(t, result, 42, "Returns must return set value")
	})

	t.Run("NonceSize records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.NonceSize()
		s.OnNonceSize.AssertCalledOnce(t, "must record NonceSize call")
	})

	t.Run("WithAEADNonceSize constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADNonceSize(func() int {
			called = true
			return 0
		}))
		_ = s.NonceSize()
		testkit.True(t, called, "WithAEADNonceSize must be called")
	})

	t.Run("NonceSize OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADNonceSizeCall
		s.OnNonceSize.OnRecord(func(c cryptotest.AEADNonceSizeCall) {
			observed = append(observed, c)
		})
		_ = s.NonceSize()
		_ = s.NonceSize()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every NonceSize call")
	})

	t.Run("Open default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result, err := s.Open(nil, nil, nil, nil)
		testkit.Equal(t, result, nil, "Open must return zero")
		testkit.NoError(t, err, "Open must not error")
	})

	t.Run("Open fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOpen.Faults(errTest, 1)
		_, err := s.Open(nil, nil, nil, nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Open Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOpen.Func(func([]byte, []byte, []byte, []byte) ([]byte, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnOpen.Faults(errTest, 1)
		_, err := s.Open(nil, nil, nil, nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Open counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOpen.Faults(errTest, 3)
		_, err1 := s.Open(nil, nil, nil, nil)
		_, err2 := s.Open(nil, nil, nil, nil)
		_, err3 := s.Open(nil, nil, nil, nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Open Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnOpen.Func(func([]byte, []byte, []byte, []byte) ([]byte, error) {
			called = true
			return []byte{42}, nil
		})
		result, err := s.Open(nil, nil, nil, nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, []byte{42}, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Open Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOpen.Returns([]byte{42}, nil)
		result, err := s.Open(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Open records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_, _ = s.Open(nil, nil, nil, nil)
		s.OnOpen.AssertCalledOnce(t, "must record Open call")
	})

	t.Run("WithAEADOpen constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADOpen(func([]byte, []byte, []byte, []byte) ([]byte, error) {
			called = true
			return nil, nil
		}))
		_, _ = s.Open(nil, nil, nil, nil)
		testkit.True(t, called, "WithAEADOpen must be called")
	})

	t.Run("Open records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_, _ = s.Open([]byte{42}, []byte{42}, []byte{42}, []byte{42})
		call := s.OnOpen.LastCall(t)
		testkit.Equal(t, call.Dst, []byte{42}, "Dst must be recorded")
		testkit.Equal(t, call.Nonce, []byte{42}, "Nonce must be recorded")
		testkit.Equal(t, call.Ciphertext, []byte{42}, "Ciphertext must be recorded")
		testkit.Equal(t, call.AdditionalData, []byte{42}, "AdditionalData must be recorded")
	})

	t.Run("Open OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADOpenCall
		s.OnOpen.OnRecord(func(c cryptotest.AEADOpenCall) {
			observed = append(observed, c)
		})
		_, _ = s.Open(nil, nil, nil, nil)
		_, _ = s.Open(nil, nil, nil, nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Open call")
	})

	t.Run("Overhead default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result := s.Overhead()
		testkit.Equal(t, result, 0, "Overhead must return zero")
	})

	t.Run("Overhead Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnOverhead.Func(func() int {
			called = true
			return 42
		})
		result := s.Overhead()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, 42, "Func must return set value")
	})

	t.Run("Overhead Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOverhead.Returns(42)
		result := s.Overhead()
		testkit.Equal(t, result, 42, "Returns must return set value")
	})

	t.Run("Overhead records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Overhead()
		s.OnOverhead.AssertCalledOnce(t, "must record Overhead call")
	})

	t.Run("WithAEADOverhead constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADOverhead(func() int {
			called = true
			return 0
		}))
		_ = s.Overhead()
		testkit.True(t, called, "WithAEADOverhead must be called")
	})

	t.Run("Overhead OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADOverheadCall
		s.OnOverhead.OnRecord(func(c cryptotest.AEADOverheadCall) {
			observed = append(observed, c)
		})
		_ = s.Overhead()
		_ = s.Overhead()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Overhead call")
	})

	t.Run("Seal default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		result := s.Seal(nil, nil, nil, nil)
		testkit.Equal(t, result, nil, "Seal must return zero")
	})

	t.Run("Seal Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		called := false
		s.OnSeal.Func(func([]byte, []byte, []byte, []byte) []byte {
			called = true
			return []byte{42}
		})
		result := s.Seal(nil, nil, nil, nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, []byte{42}, "Func must return set value")
	})

	t.Run("Seal Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnSeal.Returns([]byte{42})
		result := s.Seal(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Returns must return set value")
	})

	t.Run("Seal records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Seal(nil, nil, nil, nil)
		s.OnSeal.AssertCalledOnce(t, "must record Seal call")
	})

	t.Run("WithAEADSeal constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewAEADStub(t, cryptotest.WithAEADSeal(func([]byte, []byte, []byte, []byte) []byte {
			called = true
			return nil
		}))
		_ = s.Seal(nil, nil, nil, nil)
		testkit.True(t, called, "WithAEADSeal must be called")
	})

	t.Run("Seal records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Seal([]byte{42}, []byte{42}, []byte{42}, []byte{42})
		call := s.OnSeal.LastCall(t)
		testkit.Equal(t, call.Dst, []byte{42}, "Dst must be recorded")
		testkit.Equal(t, call.Nonce, []byte{42}, "Nonce must be recorded")
		testkit.Equal(t, call.Plaintext, []byte{42}, "Plaintext must be recorded")
		testkit.Equal(t, call.AdditionalData, []byte{42}, "AdditionalData must be recorded")
	})

	t.Run("Seal OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		var observed []cryptotest.AEADSealCall
		s.OnSeal.OnRecord(func(c cryptotest.AEADSealCall) {
			observed = append(observed, c)
		})
		_ = s.Seal(nil, nil, nil, nil)
		_ = s.Seal(nil, nil, nil, nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Seal call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubBenchMode())
		_ = s.Algorithm()
		testkit.Equal(t, s.OnAlgorithm.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f)
		s.OnAlgorithm.Times(2)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f)
		s.OnAlgorithm.TimesAtLeast(3)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Algorithm()
		_ = s.ID()
		_ = s.NonceSize()
		_, _ = s.Open(nil, nil, nil, nil)
		_ = s.Overhead()
		_ = s.Seal(nil, nil, nil, nil)
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "Algorithm must be cleared after ResetCalls")
		s.OnID.AssertNotCalled(t, "ID must be cleared after ResetCalls")
		s.OnNonceSize.AssertNotCalled(t, "NonceSize must be cleared after ResetCalls")
		s.OnOpen.AssertNotCalled(t, "Open must be cleared after ResetCalls")
		s.OnOverhead.AssertNotCalled(t, "Overhead must be cleared after ResetCalls")
		s.OnSeal.AssertNotCalled(t, "Seal must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Algorithm", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_ = s.Algorithm()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Algorithm")
	})

	t.Run("Strict mode fails on unconfigured ID", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_ = s.ID()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured ID")
	})

	t.Run("Strict mode fails on unconfigured NonceSize", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_ = s.NonceSize()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured NonceSize")
	})

	t.Run("Strict mode fails on unconfigured Open", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_, _ = s.Open(nil, nil, nil, nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Open")
	})

	t.Run("Strict mode fails on unconfigured Overhead", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_ = s.Overhead()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Overhead")
	})

	t.Run("Strict mode fails on unconfigured Seal", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewAEADStub(f, cryptotest.AEADStubStrict())
		_ = s.Seal(nil, nil, nil, nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Seal")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnAlgorithm.Returns("")
		inner.OnID.Returns(crypto.ID{})
		inner.OnNonceSize.Returns(0)
		inner.OnOpen.Returns(nil, nil)
		inner.OnOverhead.Returns(0)
		inner.OnSeal.Returns(nil)
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		_ = s.Algorithm()
		_ = s.ID()
		_ = s.NonceSize()
		_, _ = s.Open(nil, nil, nil, nil)
		_ = s.Overhead()
		_ = s.Seal(nil, nil, nil, nil)
		s.OnAlgorithm.AssertCalledOnce(t, "Algorithm must delegate")
		s.OnID.AssertCalledOnce(t, "ID must delegate")
		s.OnNonceSize.AssertCalledOnce(t, "NonceSize must delegate")
		s.OnOpen.AssertCalledOnce(t, "Open must delegate")
		s.OnOverhead.AssertCalledOnce(t, "Overhead must delegate")
		s.OnSeal.AssertCalledOnce(t, "Seal must delegate")
	})

	t.Run("DelegateTo surfaces Algorithm return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("DelegateTo surfaces ID return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnID.Returns([16]byte{1})
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("DelegateTo surfaces NonceSize return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnNonceSize.Returns(42)
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result := s.NonceSize()
		testkit.Equal(t, result, 42, "NonceSize must return configured value")
	})

	t.Run("DelegateTo surfaces Open return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnOpen.Returns([]byte{42}, nil)
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result, err := s.Open(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Open must return configured value")
		testkit.NoError(t, err, "Open must not error")
	})

	t.Run("DelegateTo surfaces Overhead return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnOverhead.Returns(42)
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result := s.Overhead()
		testkit.Equal(t, result, 42, "Overhead must return configured value")
	})

	t.Run("DelegateTo surfaces Seal return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewAEADStub(t)
		inner.OnSeal.Returns([]byte{42})
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubDelegateTo(inner))
		result := s.Seal(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Seal must return configured value")
	})

	t.Run("ResetCalls preserves Algorithm Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		_ = s.Algorithm()
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("ResetCalls preserves ID Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnID.Returns([16]byte{1})
		_ = s.ID()
		s.ResetCalls()
		s.OnID.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("ResetCalls preserves NonceSize Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnNonceSize.Returns(42)
		_ = s.NonceSize()
		s.ResetCalls()
		s.OnNonceSize.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.NonceSize()
		testkit.Equal(t, result, 42, "NonceSize must return configured value")
	})

	t.Run("ResetCalls preserves Open Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOpen.Returns([]byte{42}, nil)
		_, _ = s.Open(nil, nil, nil, nil)
		s.ResetCalls()
		s.OnOpen.AssertNotCalled(t, "ResetCalls must clear recordings")
		result, err := s.Open(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Open must return configured value")
		testkit.NoError(t, err, "Open must not error")
	})

	t.Run("ResetCalls preserves Overhead Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnOverhead.Returns(42)
		_ = s.Overhead()
		s.ResetCalls()
		s.OnOverhead.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Overhead()
		testkit.Equal(t, result, 42, "Overhead must return configured value")
	})

	t.Run("ResetCalls preserves Seal Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		s.OnSeal.Returns([]byte{42})
		_ = s.Seal(nil, nil, nil, nil)
		s.ResetCalls()
		s.OnSeal.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Seal(nil, nil, nil, nil)
		testkit.Equal(t, result, []byte{42}, "Seal must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewAEADStub(t)
		_ = s.Algorithm()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("Open FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewAEADStub(t, cryptotest.AEADStubWithClock(clk))
		s.OnOpen.FaultsFor(5*time.Second, errTest)

		_, err := s.Open(nil, nil, nil, nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, err = s.Open(nil, nil, nil, nil)
		testkit.NoError(t, err, "Open must succeed after window expires")
	})
}

func TestAEADStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewAEADStub(nil, cryptotest.AEADStubBenchMode())
	s.OnAlgorithm.Returns("")
	s.OnID.Returns(crypto.ID{})
	s.OnNonceSize.Returns(0)
	s.OnOpen.Returns(nil, nil)
	s.OnOverhead.Returns(0)
	s.OnSeal.Returns(nil)

	t.Run("Algorithm", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Algorithm()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Algorithm in BenchMode must be 0 alloc")
	})

	t.Run("ID", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.ID()
		})
		testkit.Equal(t, int(avgAllocs), 0, "ID in BenchMode must be 0 alloc")
	})

	t.Run("NonceSize", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.NonceSize()
		})
		testkit.Equal(t, int(avgAllocs), 0, "NonceSize in BenchMode must be 0 alloc")
	})

	t.Run("Open", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Open(nil, nil, nil, nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Open in BenchMode must be 0 alloc")
	})

	t.Run("Overhead", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Overhead()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Overhead in BenchMode must be 0 alloc")
	})

	t.Run("Seal", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Seal(nil, nil, nil, nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Seal in BenchMode must be 0 alloc")
	})

}
