// Code generated by testkit stub. DO NOT EDIT.
// Source: aead.go:47-97 (testkit stub AEAD)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ crypto.AEAD = (*AEADStub)(nil)

// --- Call types ---

// AEADAlgorithmCall records one invocation of crypto.AEAD.Algorithm.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADAlgorithmCall struct {
	Result crypto.Algorithm
}

// AEADIDCall records one invocation of crypto.AEAD.ID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADIDCall struct {
	Result crypto.ID
}

// AEADNonceSizeCall records one invocation of crypto.AEAD.NonceSize.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADNonceSizeCall struct {
	Result int
}

// AEADOpenCall records one invocation of crypto.AEAD.Open.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADOpenCall struct {
	Dst            []byte
	Nonce          []byte
	Ciphertext     []byte
	AdditionalData []byte
	Result         []byte
	Err            error
}

// AEADOverheadCall records one invocation of crypto.AEAD.Overhead.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADOverheadCall struct {
	Result int
}

// AEADSealCall records one invocation of crypto.AEAD.Seal.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type AEADSealCall struct {
	Dst            []byte
	Nonce          []byte
	Plaintext      []byte
	AdditionalData []byte
	Result         []byte
}

// --- Per-method stubs ---

// AEADAlgorithmStub controls behavior and records calls for Algorithm.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADAlgorithmStub struct {
	*stub.MethodStub[AEADAlgorithmCall]
	fn       func() crypto.Algorithm
	fallback *aEADAlgorithmReturn
}

type aEADAlgorithmReturn struct {
	Result crypto.Algorithm
}

// Returns sets a fixed return value for Algorithm.
func (s *AEADAlgorithmStub) Returns(result crypto.Algorithm) *AEADAlgorithmStub {
	s.fallback = &aEADAlgorithmReturn{Result: result}
	return s
}

// Func sets a function override for Algorithm.
func (s *AEADAlgorithmStub) Func(fn func() crypto.Algorithm) *AEADAlgorithmStub {
	s.fn = fn
	return s
}

// AEADIDStub controls behavior and records calls for ID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADIDStub struct {
	*stub.MethodStub[AEADIDCall]
	fn       func() crypto.ID
	fallback *aEADIDReturn
}

type aEADIDReturn struct {
	Result crypto.ID
}

// Returns sets a fixed return value for ID.
func (s *AEADIDStub) Returns(result crypto.ID) *AEADIDStub {
	s.fallback = &aEADIDReturn{Result: result}
	return s
}

// Func sets a function override for ID.
func (s *AEADIDStub) Func(fn func() crypto.ID) *AEADIDStub {
	s.fn = fn
	return s
}

// AEADNonceSizeStub controls behavior and records calls for NonceSize.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADNonceSizeStub struct {
	*stub.MethodStub[AEADNonceSizeCall]
	fn       func() int
	fallback *aEADNonceSizeReturn
}

type aEADNonceSizeReturn struct {
	Result int
}

// Returns sets a fixed return value for NonceSize.
func (s *AEADNonceSizeStub) Returns(result int) *AEADNonceSizeStub {
	s.fallback = &aEADNonceSizeReturn{Result: result}
	return s
}

// Func sets a function override for NonceSize.
func (s *AEADNonceSizeStub) Func(fn func() int) *AEADNonceSizeStub {
	s.fn = fn
	return s
}

// AEADOpenStub controls behavior and records calls for Open.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADOpenStub struct {
	*stub.MethodStub[AEADOpenCall]
	fn       func([]byte, []byte, []byte, []byte) ([]byte, error)
	fallback *aEADOpenReturn
}

type aEADOpenReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Open.
func (s *AEADOpenStub) Returns(result []byte, err error) *AEADOpenStub {
	s.fallback = &aEADOpenReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Open.
func (s *AEADOpenStub) Func(fn func([]byte, []byte, []byte, []byte) ([]byte, error)) *AEADOpenStub {
	s.fn = fn
	return s
}

// AEADOverheadStub controls behavior and records calls for Overhead.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADOverheadStub struct {
	*stub.MethodStub[AEADOverheadCall]
	fn       func() int
	fallback *aEADOverheadReturn
}

type aEADOverheadReturn struct {
	Result int
}

// Returns sets a fixed return value for Overhead.
func (s *AEADOverheadStub) Returns(result int) *AEADOverheadStub {
	s.fallback = &aEADOverheadReturn{Result: result}
	return s
}

// Func sets a function override for Overhead.
func (s *AEADOverheadStub) Func(fn func() int) *AEADOverheadStub {
	s.fn = fn
	return s
}

// AEADSealStub controls behavior and records calls for Seal.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type AEADSealStub struct {
	*stub.MethodStub[AEADSealCall]
	fn       func([]byte, []byte, []byte, []byte) []byte
	fallback *aEADSealReturn
}

type aEADSealReturn struct {
	Result []byte
}

// Returns sets a fixed return value for Seal.
func (s *AEADSealStub) Returns(result []byte) *AEADSealStub {
	s.fallback = &aEADSealReturn{Result: result}
	return s
}

// Func sets a function override for Seal.
func (s *AEADSealStub) Func(fn func([]byte, []byte, []byte, []byte) []byte) *AEADSealStub {
	s.fn = fn
	return s
}

// --- AEADStub ---

// AEADStubOption configures a [AEADStub] at construction time.
type AEADStubOption func(*AEADStub)

// AEADStubStrict enables strict mode — unconfigured methods fail the test.
func AEADStubStrict() AEADStubOption {
	return func(s *AEADStub) { s.strict = true }
}

// AEADStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func AEADStubDelegateTo(impl crypto.AEAD) AEADStubOption {
	return func(s *AEADStub) {
		s.OnAlgorithm.Func(impl.Algorithm)
		s.OnID.Func(impl.ID)
		s.OnNonceSize.Func(impl.NonceSize)
		s.OnOpen.Func(impl.Open)
		s.OnOverhead.Func(impl.Overhead)
		s.OnSeal.Func(impl.Seal)
	}
}

// AEADStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func AEADStubWithClock(clk clock.Clock) AEADStubOption {
	return func(s *AEADStub) {
		s.OnAlgorithm.WithClock(clk)
		s.OnID.WithClock(clk)
		s.OnNonceSize.WithClock(clk)
		s.OnOpen.WithClock(clk)
		s.OnOverhead.WithClock(clk)
		s.OnSeal.WithClock(clk)
	}
}

// AEADStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func AEADStubWithRandSource(src rand.Source) AEADStubOption {
	return func(s *AEADStub) {
		s.OnAlgorithm.WithRandSource(src)
		s.OnID.WithRandSource(src)
		s.OnNonceSize.WithRandSource(src)
		s.OnOpen.WithRandSource(src)
		s.OnOverhead.WithRandSource(src)
		s.OnSeal.WithRandSource(src)
	}
}

// AEADStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func AEADStubBenchMode() AEADStubOption {
	return func(s *AEADStub) {
		s.OnAlgorithm.BenchMode()
		s.OnID.BenchMode()
		s.OnNonceSize.BenchMode()
		s.OnOpen.BenchMode()
		s.OnOverhead.BenchMode()
		s.OnSeal.BenchMode()
	}
}

// WithAEADAlgorithm sets a function override at construction time.
func WithAEADAlgorithm(fn func() crypto.Algorithm) AEADStubOption {
	return func(s *AEADStub) { s.OnAlgorithm.Func(fn) }
}

// WithAEADID sets a function override at construction time.
func WithAEADID(fn func() crypto.ID) AEADStubOption {
	return func(s *AEADStub) { s.OnID.Func(fn) }
}

// WithAEADNonceSize sets a function override at construction time.
func WithAEADNonceSize(fn func() int) AEADStubOption {
	return func(s *AEADStub) { s.OnNonceSize.Func(fn) }
}

// WithAEADOpen sets a function override at construction time.
func WithAEADOpen(fn func([]byte, []byte, []byte, []byte) ([]byte, error)) AEADStubOption {
	return func(s *AEADStub) { s.OnOpen.Func(fn) }
}

// WithAEADOverhead sets a function override at construction time.
func WithAEADOverhead(fn func() int) AEADStubOption {
	return func(s *AEADStub) { s.OnOverhead.Func(fn) }
}

// WithAEADSeal sets a function override at construction time.
func WithAEADSeal(fn func([]byte, []byte, []byte, []byte) []byte) AEADStubOption {
	return func(s *AEADStub) { s.OnSeal.Func(fn) }
}

// AEADStub is a configurable test double for [crypto.AEAD].
type AEADStub struct {
	OnAlgorithm *AEADAlgorithmStub
	OnID        *AEADIDStub
	OnNonceSize *AEADNonceSizeStub
	OnOpen      *AEADOpenStub
	OnOverhead  *AEADOverheadStub
	OnSeal      *AEADSealStub
	strict      bool
}

// NewAEADStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewAEADStub(tb testing.TB, opts ...AEADStubOption) *AEADStub {
	s := &AEADStub{
		OnAlgorithm: &AEADAlgorithmStub{MethodStub: stub.NewMethodStub[AEADAlgorithmCall](tb, "AEAD.Algorithm")},
		OnID:        &AEADIDStub{MethodStub: stub.NewMethodStub[AEADIDCall](tb, "AEAD.ID")},
		OnNonceSize: &AEADNonceSizeStub{MethodStub: stub.NewMethodStub[AEADNonceSizeCall](tb, "AEAD.NonceSize")},
		OnOpen:      &AEADOpenStub{MethodStub: stub.NewMethodStub[AEADOpenCall](tb, "AEAD.Open")},
		OnOverhead:  &AEADOverheadStub{MethodStub: stub.NewMethodStub[AEADOverheadCall](tb, "AEAD.Overhead")},
		OnSeal:      &AEADSealStub{MethodStub: stub.NewMethodStub[AEADSealCall](tb, "AEAD.Seal")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnAlgorithm.Strict()
		s.OnID.Strict()
		s.OnNonceSize.Strict()
		s.OnOpen.Strict()
		s.OnOverhead.Strict()
		s.OnSeal.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnAlgorithm.Verify()
				s.OnID.Verify()
				s.OnNonceSize.Verify()
				s.OnOpen.Verify()
				s.OnOverhead.Verify()
				s.OnSeal.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *AEADStub) ResetCalls() {
	s.OnAlgorithm.Reset()
	s.OnID.Reset()
	s.OnNonceSize.Reset()
	s.OnOpen.Reset()
	s.OnOverhead.Reset()
	s.OnSeal.Reset()
}

// --- Interface method implementations ---

func (s *AEADStub) Algorithm() crypto.Algorithm {
	s.OnAlgorithm.SleepLatency()
	call := AEADAlgorithmCall{}
	if s.OnAlgorithm.fn != nil {
		r0 := s.OnAlgorithm.fn()
		call.Result = r0
		s.OnAlgorithm.Record(call)
		return r0
	}
	if s.OnAlgorithm.fallback != nil {
		f := s.OnAlgorithm.fallback
		call.Result = f.Result
		s.OnAlgorithm.Record(call)
		return f.Result
	}
	s.OnAlgorithm.FailUnexpectedCall(call)
	s.OnAlgorithm.Record(call)
	return ""
}

func (s *AEADStub) ID() crypto.ID {
	s.OnID.SleepLatency()
	call := AEADIDCall{}
	if s.OnID.fn != nil {
		r0 := s.OnID.fn()
		call.Result = r0
		s.OnID.Record(call)
		return r0
	}
	if s.OnID.fallback != nil {
		f := s.OnID.fallback
		call.Result = f.Result
		s.OnID.Record(call)
		return f.Result
	}
	s.OnID.FailUnexpectedCall(call)
	s.OnID.Record(call)
	return crypto.ID{}
}

func (s *AEADStub) NonceSize() int {
	s.OnNonceSize.SleepLatency()
	call := AEADNonceSizeCall{}
	if s.OnNonceSize.fn != nil {
		r0 := s.OnNonceSize.fn()
		call.Result = r0
		s.OnNonceSize.Record(call)
		return r0
	}
	if s.OnNonceSize.fallback != nil {
		f := s.OnNonceSize.fallback
		call.Result = f.Result
		s.OnNonceSize.Record(call)
		return f.Result
	}
	s.OnNonceSize.FailUnexpectedCall(call)
	s.OnNonceSize.Record(call)
	return 0
}

func (s *AEADStub) Open(dst []byte, nonce []byte, ciphertext []byte, additionalData []byte) ([]byte, error) {
	s.OnOpen.SleepLatency()
	call := AEADOpenCall{Dst: dst, Nonce: nonce, Ciphertext: ciphertext, AdditionalData: additionalData}
	if fired, faultErr := s.OnOpen.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnOpen.Record(call)
		return nil, faultErr
	}
	if s.OnOpen.fn != nil {
		r0, r1 := s.OnOpen.fn(dst, nonce, ciphertext, additionalData)
		call.Result = r0
		call.Err = r1
		s.OnOpen.Record(call)
		return r0, r1
	}
	if s.OnOpen.fallback != nil {
		f := s.OnOpen.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnOpen.Record(call)
		return f.Result, f.Err
	}
	s.OnOpen.FailUnexpectedCall(call)
	s.OnOpen.Record(call)
	return nil, nil
}

func (s *AEADStub) Overhead() int {
	s.OnOverhead.SleepLatency()
	call := AEADOverheadCall{}
	if s.OnOverhead.fn != nil {
		r0 := s.OnOverhead.fn()
		call.Result = r0
		s.OnOverhead.Record(call)
		return r0
	}
	if s.OnOverhead.fallback != nil {
		f := s.OnOverhead.fallback
		call.Result = f.Result
		s.OnOverhead.Record(call)
		return f.Result
	}
	s.OnOverhead.FailUnexpectedCall(call)
	s.OnOverhead.Record(call)
	return 0
}

func (s *AEADStub) Seal(dst []byte, nonce []byte, plaintext []byte, additionalData []byte) []byte {
	s.OnSeal.SleepLatency()
	call := AEADSealCall{Dst: dst, Nonce: nonce, Plaintext: plaintext, AdditionalData: additionalData}
	if s.OnSeal.fn != nil {
		r0 := s.OnSeal.fn(dst, nonce, plaintext, additionalData)
		call.Result = r0
		s.OnSeal.Record(call)
		return r0
	}
	if s.OnSeal.fallback != nil {
		f := s.OnSeal.fallback
		call.Result = f.Result
		s.OnSeal.Record(call)
		return f.Result
	}
	s.OnSeal.FailUnexpectedCall(call)
	s.OnSeal.Record(call)
	return nil
}
