// Code generated by testkit stub. DO NOT EDIT.
// Source: keeper.go:38-75 (testkit stub Destroyer)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ crypto.Destroyer = (*DestroyerStub)(nil)

// --- Call types ---

// DestroyerDestroyCall records one invocation of crypto.Destroyer.Destroy.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type DestroyerDestroyCall struct {
	Ctx   context.Context
	KeyID string
	Err   error
}

// DestroyerKeyIDCall records one invocation of crypto.Destroyer.KeyID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type DestroyerKeyIDCall struct {
	Result string
}

// DestroyerUnwrapCall records one invocation of crypto.Destroyer.Unwrap.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type DestroyerUnwrapCall struct {
	Ctx     context.Context
	Wrapped []byte
	Result  []byte
	Err     error
}

// DestroyerWrapCall records one invocation of crypto.Destroyer.Wrap.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type DestroyerWrapCall struct {
	Ctx    context.Context
	Dek    []byte
	Result []byte
	Err    error
}

// --- Per-method stubs ---

// DestroyerDestroyStub controls behavior and records calls for Destroy.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type DestroyerDestroyStub struct {
	*stub.MethodStub[DestroyerDestroyCall]
	fn       func(context.Context, string) error
	fallback *destroyerDestroyReturn
}

type destroyerDestroyReturn struct {
	Err error
}

// Returns sets a fixed return value for Destroy.
func (s *DestroyerDestroyStub) Returns(err error) *DestroyerDestroyStub {
	s.fallback = &destroyerDestroyReturn{Err: err}
	return s
}

// Func sets a function override for Destroy.
func (s *DestroyerDestroyStub) Func(fn func(context.Context, string) error) *DestroyerDestroyStub {
	s.fn = fn
	return s
}

// DestroyerKeyIDStub controls behavior and records calls for KeyID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type DestroyerKeyIDStub struct {
	*stub.MethodStub[DestroyerKeyIDCall]
	fn       func() string
	fallback *destroyerKeyIDReturn
}

type destroyerKeyIDReturn struct {
	Result string
}

// Returns sets a fixed return value for KeyID.
func (s *DestroyerKeyIDStub) Returns(result string) *DestroyerKeyIDStub {
	s.fallback = &destroyerKeyIDReturn{Result: result}
	return s
}

// Func sets a function override for KeyID.
func (s *DestroyerKeyIDStub) Func(fn func() string) *DestroyerKeyIDStub {
	s.fn = fn
	return s
}

// DestroyerUnwrapStub controls behavior and records calls for Unwrap.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type DestroyerUnwrapStub struct {
	*stub.MethodStub[DestroyerUnwrapCall]
	fn       func(context.Context, []byte) ([]byte, error)
	fallback *destroyerUnwrapReturn
}

type destroyerUnwrapReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Unwrap.
func (s *DestroyerUnwrapStub) Returns(result []byte, err error) *DestroyerUnwrapStub {
	s.fallback = &destroyerUnwrapReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Unwrap.
func (s *DestroyerUnwrapStub) Func(fn func(context.Context, []byte) ([]byte, error)) *DestroyerUnwrapStub {
	s.fn = fn
	return s
}

// DestroyerWrapStub controls behavior and records calls for Wrap.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type DestroyerWrapStub struct {
	*stub.MethodStub[DestroyerWrapCall]
	fn       func(context.Context, []byte) ([]byte, error)
	fallback *destroyerWrapReturn
}

type destroyerWrapReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Wrap.
func (s *DestroyerWrapStub) Returns(result []byte, err error) *DestroyerWrapStub {
	s.fallback = &destroyerWrapReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Wrap.
func (s *DestroyerWrapStub) Func(fn func(context.Context, []byte) ([]byte, error)) *DestroyerWrapStub {
	s.fn = fn
	return s
}

// --- DestroyerStub ---

// DestroyerStubOption configures a [DestroyerStub] at construction time.
type DestroyerStubOption func(*DestroyerStub)

// DestroyerStubStrict enables strict mode — unconfigured methods fail the test.
func DestroyerStubStrict() DestroyerStubOption {
	return func(s *DestroyerStub) { s.strict = true }
}

// DestroyerStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func DestroyerStubDelegateTo(impl crypto.Destroyer) DestroyerStubOption {
	return func(s *DestroyerStub) {
		s.OnDestroy.Func(impl.Destroy)
		s.OnKeyID.Func(impl.KeyID)
		s.OnUnwrap.Func(impl.Unwrap)
		s.OnWrap.Func(impl.Wrap)
	}
}

// DestroyerStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func DestroyerStubWithClock(clk clock.Clock) DestroyerStubOption {
	return func(s *DestroyerStub) {
		s.OnDestroy.WithClock(clk)
		s.OnKeyID.WithClock(clk)
		s.OnUnwrap.WithClock(clk)
		s.OnWrap.WithClock(clk)
	}
}

// DestroyerStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func DestroyerStubWithRandSource(src rand.Source) DestroyerStubOption {
	return func(s *DestroyerStub) {
		s.OnDestroy.WithRandSource(src)
		s.OnKeyID.WithRandSource(src)
		s.OnUnwrap.WithRandSource(src)
		s.OnWrap.WithRandSource(src)
	}
}

// DestroyerStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func DestroyerStubBenchMode() DestroyerStubOption {
	return func(s *DestroyerStub) {
		s.OnDestroy.BenchMode()
		s.OnKeyID.BenchMode()
		s.OnUnwrap.BenchMode()
		s.OnWrap.BenchMode()
	}
}

// WithDestroyerDestroy sets a function override at construction time.
func WithDestroyerDestroy(fn func(context.Context, string) error) DestroyerStubOption {
	return func(s *DestroyerStub) { s.OnDestroy.Func(fn) }
}

// WithDestroyerKeyID sets a function override at construction time.
func WithDestroyerKeyID(fn func() string) DestroyerStubOption {
	return func(s *DestroyerStub) { s.OnKeyID.Func(fn) }
}

// WithDestroyerUnwrap sets a function override at construction time.
func WithDestroyerUnwrap(fn func(context.Context, []byte) ([]byte, error)) DestroyerStubOption {
	return func(s *DestroyerStub) { s.OnUnwrap.Func(fn) }
}

// WithDestroyerWrap sets a function override at construction time.
func WithDestroyerWrap(fn func(context.Context, []byte) ([]byte, error)) DestroyerStubOption {
	return func(s *DestroyerStub) { s.OnWrap.Func(fn) }
}

// DestroyerStub is a configurable test double for [crypto.Destroyer].
type DestroyerStub struct {
	OnDestroy *DestroyerDestroyStub
	OnKeyID   *DestroyerKeyIDStub
	OnUnwrap  *DestroyerUnwrapStub
	OnWrap    *DestroyerWrapStub
	strict    bool
}

// NewDestroyerStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewDestroyerStub(tb testing.TB, opts ...DestroyerStubOption) *DestroyerStub {
	s := &DestroyerStub{
		OnDestroy: &DestroyerDestroyStub{MethodStub: stub.NewMethodStub[DestroyerDestroyCall](tb, "Destroyer.Destroy")},
		OnKeyID:   &DestroyerKeyIDStub{MethodStub: stub.NewMethodStub[DestroyerKeyIDCall](tb, "Destroyer.KeyID")},
		OnUnwrap:  &DestroyerUnwrapStub{MethodStub: stub.NewMethodStub[DestroyerUnwrapCall](tb, "Destroyer.Unwrap")},
		OnWrap:    &DestroyerWrapStub{MethodStub: stub.NewMethodStub[DestroyerWrapCall](tb, "Destroyer.Wrap")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnDestroy.Strict()
		s.OnKeyID.Strict()
		s.OnUnwrap.Strict()
		s.OnWrap.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnDestroy.Verify()
				s.OnKeyID.Verify()
				s.OnUnwrap.Verify()
				s.OnWrap.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *DestroyerStub) ResetCalls() {
	s.OnDestroy.Reset()
	s.OnKeyID.Reset()
	s.OnUnwrap.Reset()
	s.OnWrap.Reset()
}

// --- Interface method implementations ---

func (s *DestroyerStub) Destroy(ctx context.Context, keyID string) error {
	s.OnDestroy.SleepLatency()
	call := DestroyerDestroyCall{Ctx: ctx, KeyID: keyID}
	if fired, faultErr := s.OnDestroy.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnDestroy.Record(call)
		return faultErr
	}
	if s.OnDestroy.fn != nil {
		r0 := s.OnDestroy.fn(ctx, keyID)
		call.Err = r0
		s.OnDestroy.Record(call)
		return r0
	}
	if s.OnDestroy.fallback != nil {
		f := s.OnDestroy.fallback
		call.Err = f.Err
		s.OnDestroy.Record(call)
		return f.Err
	}
	s.OnDestroy.FailUnexpectedCall(call)
	s.OnDestroy.Record(call)
	return nil
}

func (s *DestroyerStub) KeyID() string {
	s.OnKeyID.SleepLatency()
	call := DestroyerKeyIDCall{}
	if s.OnKeyID.fn != nil {
		r0 := s.OnKeyID.fn()
		call.Result = r0
		s.OnKeyID.Record(call)
		return r0
	}
	if s.OnKeyID.fallback != nil {
		f := s.OnKeyID.fallback
		call.Result = f.Result
		s.OnKeyID.Record(call)
		return f.Result
	}
	s.OnKeyID.FailUnexpectedCall(call)
	s.OnKeyID.Record(call)
	return ""
}

func (s *DestroyerStub) Unwrap(ctx context.Context, wrapped []byte) ([]byte, error) {
	s.OnUnwrap.SleepLatency()
	call := DestroyerUnwrapCall{Ctx: ctx, Wrapped: wrapped}
	if fired, faultErr := s.OnUnwrap.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnUnwrap.Record(call)
		return nil, faultErr
	}
	if s.OnUnwrap.fn != nil {
		r0, r1 := s.OnUnwrap.fn(ctx, wrapped)
		call.Result = r0
		call.Err = r1
		s.OnUnwrap.Record(call)
		return r0, r1
	}
	if s.OnUnwrap.fallback != nil {
		f := s.OnUnwrap.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnUnwrap.Record(call)
		return f.Result, f.Err
	}
	s.OnUnwrap.FailUnexpectedCall(call)
	s.OnUnwrap.Record(call)
	return nil, nil
}

func (s *DestroyerStub) Wrap(ctx context.Context, dek []byte) ([]byte, error) {
	s.OnWrap.SleepLatency()
	call := DestroyerWrapCall{Ctx: ctx, Dek: dek}
	if fired, faultErr := s.OnWrap.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnWrap.Record(call)
		return nil, faultErr
	}
	if s.OnWrap.fn != nil {
		r0, r1 := s.OnWrap.fn(ctx, dek)
		call.Result = r0
		call.Err = r1
		s.OnWrap.Record(call)
		return r0, r1
	}
	if s.OnWrap.fallback != nil {
		f := s.OnWrap.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnWrap.Record(call)
		return f.Result, f.Err
	}
	s.OnWrap.FailUnexpectedCall(call)
	s.OnWrap.Record(call)
	return nil, nil
}
