// Code generated by testkit stub. DO NOT EDIT.
// Source: keeper.go:38-94 (testkit stub KeyGenerator)

package cryptotest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestKeyGeneratorStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("KeyGenerator-stub-test")

	t.Run("GenerateKey default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		plaintext, wrapped, err := s.GenerateKey(t.Context(), 0)
		testkit.Equal(t, plaintext, nil, "GenerateKey must return zero")
		testkit.Equal(t, wrapped, nil, "GenerateKey must return zero")
		testkit.NoError(t, err, "GenerateKey must not error")
	})

	t.Run("GenerateKey fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnGenerateKey.Faults(errTest, 1)
		_, _, err := s.GenerateKey(t.Context(), 0)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("GenerateKey Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnGenerateKey.Func(func(context.Context, int) ([]byte, []byte, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnGenerateKey.Faults(errTest, 1)
		_, _, err := s.GenerateKey(t.Context(), 0)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("GenerateKey counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnGenerateKey.Faults(errTest, 3)
		_, _, err1 := s.GenerateKey(t.Context(), 0)
		_, _, err2 := s.GenerateKey(t.Context(), 0)
		_, _, err3 := s.GenerateKey(t.Context(), 0)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("GenerateKey Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		called := false
		s.OnGenerateKey.Func(func(context.Context, int) ([]byte, []byte, error) {
			called = true
			return []byte{42}, []byte{42}, nil
		})
		plaintext, wrapped, err := s.GenerateKey(t.Context(), 0)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, plaintext, []byte{42}, "Func must return set value")
		testkit.Equal(t, wrapped, []byte{42}, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("GenerateKey Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnGenerateKey.Returns([]byte{42}, []byte{42}, nil)
		plaintext, wrapped, err := s.GenerateKey(t.Context(), 0)
		testkit.Equal(t, plaintext, []byte{42}, "Returns must return set value")
		testkit.Equal(t, wrapped, []byte{42}, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("GenerateKey records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		s.OnGenerateKey.AssertCalledOnce(t, "must record GenerateKey call")
	})

	t.Run("WithKeyGeneratorGenerateKey constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.WithKeyGeneratorGenerateKey(func(context.Context, int) ([]byte, []byte, error) {
			called = true
			return nil, nil, nil
		}))
		_, _, _ = s.GenerateKey(t.Context(), 0)
		testkit.True(t, called, "WithKeyGeneratorGenerateKey must be called")
	})

	t.Run("GenerateKey records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _, _ = s.GenerateKey(t.Context(), 42)
		call := s.OnGenerateKey.LastCall(t)
		testkit.Equal(t, call.Size, 42, "Size must be recorded")
	})

	t.Run("GenerateKey OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		var observed []cryptotest.KeyGeneratorGenerateKeyCall
		s.OnGenerateKey.OnRecord(func(c cryptotest.KeyGeneratorGenerateKeyCall) {
			observed = append(observed, c)
		})
		_, _, _ = s.GenerateKey(t.Context(), 0)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every GenerateKey call")
	})

	t.Run("KeyID default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		result := s.KeyID()
		testkit.Equal(t, result, "", "KeyID must return zero")
	})

	t.Run("KeyID Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		called := false
		s.OnKeyID.Func(func() string {
			called = true
			return "test-result"
		})
		result := s.KeyID()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, "test-result", "Func must return set value")
	})

	t.Run("KeyID Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnKeyID.Returns("test-result")
		result := s.KeyID()
		testkit.Equal(t, result, "test-result", "Returns must return set value")
	})

	t.Run("KeyID records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_ = s.KeyID()
		s.OnKeyID.AssertCalledOnce(t, "must record KeyID call")
	})

	t.Run("WithKeyGeneratorKeyID constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.WithKeyGeneratorKeyID(func() string {
			called = true
			return ""
		}))
		_ = s.KeyID()
		testkit.True(t, called, "WithKeyGeneratorKeyID must be called")
	})

	t.Run("KeyID OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		var observed []cryptotest.KeyGeneratorKeyIDCall
		s.OnKeyID.OnRecord(func(c cryptotest.KeyGeneratorKeyIDCall) {
			observed = append(observed, c)
		})
		_ = s.KeyID()
		_ = s.KeyID()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every KeyID call")
	})

	t.Run("Unwrap default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		result, err := s.Unwrap(t.Context(), nil)
		testkit.Equal(t, result, nil, "Unwrap must return zero")
		testkit.NoError(t, err, "Unwrap must not error")
	})

	t.Run("Unwrap fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnUnwrap.Faults(errTest, 1)
		_, err := s.Unwrap(t.Context(), nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Unwrap Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnUnwrap.Func(func(context.Context, []byte) ([]byte, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnUnwrap.Faults(errTest, 1)
		_, err := s.Unwrap(t.Context(), nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Unwrap counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnUnwrap.Faults(errTest, 3)
		_, err1 := s.Unwrap(t.Context(), nil)
		_, err2 := s.Unwrap(t.Context(), nil)
		_, err3 := s.Unwrap(t.Context(), nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Unwrap Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		called := false
		s.OnUnwrap.Func(func(context.Context, []byte) ([]byte, error) {
			called = true
			return []byte{42}, nil
		})
		result, err := s.Unwrap(t.Context(), nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, []byte{42}, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Unwrap Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnUnwrap.Returns([]byte{42}, nil)
		result, err := s.Unwrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Unwrap records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _ = s.Unwrap(t.Context(), nil)
		s.OnUnwrap.AssertCalledOnce(t, "must record Unwrap call")
	})

	t.Run("WithKeyGeneratorUnwrap constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.WithKeyGeneratorUnwrap(func(context.Context, []byte) ([]byte, error) {
			called = true
			return nil, nil
		}))
		_, _ = s.Unwrap(t.Context(), nil)
		testkit.True(t, called, "WithKeyGeneratorUnwrap must be called")
	})

	t.Run("Unwrap records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _ = s.Unwrap(t.Context(), []byte{42})
		call := s.OnUnwrap.LastCall(t)
		testkit.Equal(t, call.Wrapped, []byte{42}, "Wrapped must be recorded")
	})

	t.Run("Unwrap OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		var observed []cryptotest.KeyGeneratorUnwrapCall
		s.OnUnwrap.OnRecord(func(c cryptotest.KeyGeneratorUnwrapCall) {
			observed = append(observed, c)
		})
		_, _ = s.Unwrap(t.Context(), nil)
		_, _ = s.Unwrap(t.Context(), nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Unwrap call")
	})

	t.Run("Wrap default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		result, err := s.Wrap(t.Context(), nil)
		testkit.Equal(t, result, nil, "Wrap must return zero")
		testkit.NoError(t, err, "Wrap must not error")
	})

	t.Run("Wrap fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnWrap.Faults(errTest, 1)
		_, err := s.Wrap(t.Context(), nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Wrap Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnWrap.Func(func(context.Context, []byte) ([]byte, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnWrap.Faults(errTest, 1)
		_, err := s.Wrap(t.Context(), nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Wrap counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnWrap.Faults(errTest, 3)
		_, err1 := s.Wrap(t.Context(), nil)
		_, err2 := s.Wrap(t.Context(), nil)
		_, err3 := s.Wrap(t.Context(), nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Wrap Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		called := false
		s.OnWrap.Func(func(context.Context, []byte) ([]byte, error) {
			called = true
			return []byte{42}, nil
		})
		result, err := s.Wrap(t.Context(), nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, []byte{42}, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Wrap Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnWrap.Returns([]byte{42}, nil)
		result, err := s.Wrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Wrap records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _ = s.Wrap(t.Context(), nil)
		s.OnWrap.AssertCalledOnce(t, "must record Wrap call")
	})

	t.Run("WithKeyGeneratorWrap constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.WithKeyGeneratorWrap(func(context.Context, []byte) ([]byte, error) {
			called = true
			return nil, nil
		}))
		_, _ = s.Wrap(t.Context(), nil)
		testkit.True(t, called, "WithKeyGeneratorWrap must be called")
	})

	t.Run("Wrap records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _ = s.Wrap(t.Context(), []byte{42})
		call := s.OnWrap.LastCall(t)
		testkit.Equal(t, call.Dek, []byte{42}, "Dek must be recorded")
	})

	t.Run("Wrap OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		var observed []cryptotest.KeyGeneratorWrapCall
		s.OnWrap.OnRecord(func(c cryptotest.KeyGeneratorWrapCall) {
			observed = append(observed, c)
		})
		_, _ = s.Wrap(t.Context(), nil)
		_, _ = s.Wrap(t.Context(), nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Wrap call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubBenchMode())
		_, _, _ = s.GenerateKey(t.Context(), 0)
		testkit.Equal(t, s.OnGenerateKey.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f)
		s.OnGenerateKey.Times(2)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f)
		s.OnGenerateKey.TimesAtLeast(3)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		_ = s.KeyID()
		_, _ = s.Unwrap(t.Context(), nil)
		_, _ = s.Wrap(t.Context(), nil)
		s.ResetCalls()
		s.OnGenerateKey.AssertNotCalled(t, "GenerateKey must be cleared after ResetCalls")
		s.OnKeyID.AssertNotCalled(t, "KeyID must be cleared after ResetCalls")
		s.OnUnwrap.AssertNotCalled(t, "Unwrap must be cleared after ResetCalls")
		s.OnWrap.AssertNotCalled(t, "Wrap must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured GenerateKey", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f, cryptotest.KeyGeneratorStubStrict())
		_, _, _ = s.GenerateKey(t.Context(), 0)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured GenerateKey")
	})

	t.Run("Strict mode fails on unconfigured KeyID", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f, cryptotest.KeyGeneratorStubStrict())
		_ = s.KeyID()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured KeyID")
	})

	t.Run("Strict mode fails on unconfigured Unwrap", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f, cryptotest.KeyGeneratorStubStrict())
		_, _ = s.Unwrap(t.Context(), nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Unwrap")
	})

	t.Run("Strict mode fails on unconfigured Wrap", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewKeyGeneratorStub(f, cryptotest.KeyGeneratorStubStrict())
		_, _ = s.Wrap(t.Context(), nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Wrap")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnGenerateKey.Returns(nil, nil, nil)
		inner.OnKeyID.Returns("")
		inner.OnUnwrap.Returns(nil, nil)
		inner.OnWrap.Returns(nil, nil)
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubDelegateTo(inner))
		_, _, _ = s.GenerateKey(t.Context(), 0)
		_ = s.KeyID()
		_, _ = s.Unwrap(t.Context(), nil)
		_, _ = s.Wrap(t.Context(), nil)
		s.OnGenerateKey.AssertCalledOnce(t, "GenerateKey must delegate")
		s.OnKeyID.AssertCalledOnce(t, "KeyID must delegate")
		s.OnUnwrap.AssertCalledOnce(t, "Unwrap must delegate")
		s.OnWrap.AssertCalledOnce(t, "Wrap must delegate")
	})

	t.Run("DelegateTo surfaces GenerateKey return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnGenerateKey.Returns([]byte{42}, []byte{42}, nil)
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubDelegateTo(inner))
		plaintext, wrapped, err := s.GenerateKey(t.Context(), 0)
		testkit.Equal(t, plaintext, []byte{42}, "GenerateKey must return configured value")
		testkit.Equal(t, wrapped, []byte{42}, "GenerateKey must return configured value")
		testkit.NoError(t, err, "GenerateKey must not error")
	})

	t.Run("DelegateTo surfaces KeyID return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnKeyID.Returns("test-result")
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubDelegateTo(inner))
		result := s.KeyID()
		testkit.Equal(t, result, "test-result", "KeyID must return configured value")
	})

	t.Run("DelegateTo surfaces Unwrap return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnUnwrap.Returns([]byte{42}, nil)
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubDelegateTo(inner))
		result, err := s.Unwrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Unwrap must return configured value")
		testkit.NoError(t, err, "Unwrap must not error")
	})

	t.Run("DelegateTo surfaces Wrap return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnWrap.Returns([]byte{42}, nil)
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubDelegateTo(inner))
		result, err := s.Wrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Wrap must return configured value")
		testkit.NoError(t, err, "Wrap must not error")
	})

	t.Run("ResetCalls preserves GenerateKey Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnGenerateKey.Returns([]byte{42}, []byte{42}, nil)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		s.ResetCalls()
		s.OnGenerateKey.AssertNotCalled(t, "ResetCalls must clear recordings")
		plaintext, wrapped, err := s.GenerateKey(t.Context(), 0)
		testkit.Equal(t, plaintext, []byte{42}, "GenerateKey must return configured value")
		testkit.Equal(t, wrapped, []byte{42}, "GenerateKey must return configured value")
		testkit.NoError(t, err, "GenerateKey must not error")
	})

	t.Run("ResetCalls preserves KeyID Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnKeyID.Returns("test-result")
		_ = s.KeyID()
		s.ResetCalls()
		s.OnKeyID.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.KeyID()
		testkit.Equal(t, result, "test-result", "KeyID must return configured value")
	})

	t.Run("ResetCalls preserves Unwrap Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnUnwrap.Returns([]byte{42}, nil)
		_, _ = s.Unwrap(t.Context(), nil)
		s.ResetCalls()
		s.OnUnwrap.AssertNotCalled(t, "ResetCalls must clear recordings")
		result, err := s.Unwrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Unwrap must return configured value")
		testkit.NoError(t, err, "Unwrap must not error")
	})

	t.Run("ResetCalls preserves Wrap Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		s.OnWrap.Returns([]byte{42}, nil)
		_, _ = s.Wrap(t.Context(), nil)
		s.ResetCalls()
		s.OnWrap.AssertNotCalled(t, "ResetCalls must clear recordings")
		result, err := s.Wrap(t.Context(), nil)
		testkit.Equal(t, result, []byte{42}, "Wrap must return configured value")
		testkit.NoError(t, err, "Wrap must not error")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewKeyGeneratorStub(t)
		_, _, _ = s.GenerateKey(t.Context(), 0)
		testkit.Len(t, s.OnGenerateKey.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnGenerateKey.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("GenerateKey Latency honors virtual clock", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubWithClock(clk))
		s.OnGenerateKey.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _, _ = s.GenerateKey(t.Context(), 0)
			close(done)
		}()

		clk.AwaitWaiters(1)
		start := time.Now()
		clk.Advance(6 * time.Second)
		<-done
		testkit.True(t, time.Since(start) < 100*time.Millisecond,
			"Latency must use virtual clock, not real time")
	})

	t.Run("GenerateKey Latency happens before Record", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubWithClock(clk))
		s.OnGenerateKey.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _, _ = s.GenerateKey(t.Context(), 0)
			close(done)
		}()

		clk.AwaitWaiters(1)
		testkit.Equal(t, s.OnGenerateKey.CallCount(), 0,
			"call must not record until latency completes")
		clk.Advance(6 * time.Second)
		<-done
		testkit.Equal(t, s.OnGenerateKey.CallCount(), 1,
			"call records after latency")
	})

	t.Run("GenerateKey Latency applies on DelegateTo path", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		inner := cryptotest.NewKeyGeneratorStub(t)
		inner.OnGenerateKey.Returns(nil, nil, nil)
		inner.OnKeyID.Returns("")
		inner.OnUnwrap.Returns(nil, nil)
		inner.OnWrap.Returns(nil, nil)
		s := cryptotest.NewKeyGeneratorStub(t,
			cryptotest.KeyGeneratorStubWithClock(clk),
			cryptotest.KeyGeneratorStubDelegateTo(inner))
		s.OnGenerateKey.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _, _ = s.GenerateKey(t.Context(), 0)
			close(done)
		}()

		clk.AwaitWaiters(1)
		start := time.Now()
		clk.Advance(6 * time.Second)
		<-done
		testkit.True(t, time.Since(start) < 100*time.Millisecond,
			"DelegateTo path must honor Latency with virtual clock")
	})

	t.Run("GenerateKey FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewKeyGeneratorStub(t, cryptotest.KeyGeneratorStubWithClock(clk))
		s.OnGenerateKey.FaultsFor(5*time.Second, errTest)

		_, _, err := s.GenerateKey(t.Context(), 0)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, _, err = s.GenerateKey(t.Context(), 0)
		testkit.NoError(t, err, "GenerateKey must succeed after window expires")
	})
}

func TestKeyGeneratorStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewKeyGeneratorStub(nil, cryptotest.KeyGeneratorStubBenchMode())
	s.OnGenerateKey.Returns(nil, nil, nil)
	s.OnKeyID.Returns("")
	s.OnUnwrap.Returns(nil, nil)
	s.OnWrap.Returns(nil, nil)

	t.Run("GenerateKey", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _, _ = s.GenerateKey(t.Context(), 0)
		})
		testkit.Equal(t, int(avgAllocs), 0, "GenerateKey in BenchMode must be 0 alloc")
	})

	t.Run("KeyID", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.KeyID()
		})
		testkit.Equal(t, int(avgAllocs), 0, "KeyID in BenchMode must be 0 alloc")
	})

	t.Run("Unwrap", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Unwrap(t.Context(), nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Unwrap in BenchMode must be 0 alloc")
	})

	t.Run("Wrap", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Wrap(t.Context(), nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Wrap in BenchMode must be 0 alloc")
	})

}
