// Code generated by testkit stub. DO NOT EDIT.
// Source: keeper.go:38-94 (testkit stub KeyGenerator)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ crypto.KeyGenerator = (*KeyGeneratorStub)(nil)

// --- Call types ---

// KeyGeneratorGenerateKeyCall records one invocation of crypto.KeyGenerator.GenerateKey.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type KeyGeneratorGenerateKeyCall struct {
	Ctx       context.Context
	Size      int
	Plaintext []byte
	Wrapped   []byte
	Err       error
}

// KeyGeneratorKeyIDCall records one invocation of crypto.KeyGenerator.KeyID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type KeyGeneratorKeyIDCall struct {
	Result string
}

// KeyGeneratorUnwrapCall records one invocation of crypto.KeyGenerator.Unwrap.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type KeyGeneratorUnwrapCall struct {
	Ctx     context.Context
	Wrapped []byte
	Result  []byte
	Err     error
}

// KeyGeneratorWrapCall records one invocation of crypto.KeyGenerator.Wrap.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type KeyGeneratorWrapCall struct {
	Ctx    context.Context
	Dek    []byte
	Result []byte
	Err    error
}

// --- Per-method stubs ---

// KeyGeneratorGenerateKeyStub controls behavior and records calls for GenerateKey.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type KeyGeneratorGenerateKeyStub struct {
	*stub.MethodStub[KeyGeneratorGenerateKeyCall]
	fn       func(context.Context, int) ([]byte, []byte, error)
	fallback *keyGeneratorGenerateKeyReturn
}

type keyGeneratorGenerateKeyReturn struct {
	Plaintext []byte
	Wrapped   []byte
	Err       error
}

// Returns sets a fixed return value for GenerateKey.
func (s *KeyGeneratorGenerateKeyStub) Returns(plaintext []byte, wrapped []byte, err error) *KeyGeneratorGenerateKeyStub {
	s.fallback = &keyGeneratorGenerateKeyReturn{Plaintext: plaintext, Wrapped: wrapped, Err: err}
	return s
}

// Func sets a function override for GenerateKey.
func (s *KeyGeneratorGenerateKeyStub) Func(fn func(context.Context, int) ([]byte, []byte, error)) *KeyGeneratorGenerateKeyStub {
	s.fn = fn
	return s
}

// KeyGeneratorKeyIDStub controls behavior and records calls for KeyID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type KeyGeneratorKeyIDStub struct {
	*stub.MethodStub[KeyGeneratorKeyIDCall]
	fn       func() string
	fallback *keyGeneratorKeyIDReturn
}

type keyGeneratorKeyIDReturn struct {
	Result string
}

// Returns sets a fixed return value for KeyID.
func (s *KeyGeneratorKeyIDStub) Returns(result string) *KeyGeneratorKeyIDStub {
	s.fallback = &keyGeneratorKeyIDReturn{Result: result}
	return s
}

// Func sets a function override for KeyID.
func (s *KeyGeneratorKeyIDStub) Func(fn func() string) *KeyGeneratorKeyIDStub {
	s.fn = fn
	return s
}

// KeyGeneratorUnwrapStub controls behavior and records calls for Unwrap.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type KeyGeneratorUnwrapStub struct {
	*stub.MethodStub[KeyGeneratorUnwrapCall]
	fn       func(context.Context, []byte) ([]byte, error)
	fallback *keyGeneratorUnwrapReturn
}

type keyGeneratorUnwrapReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Unwrap.
func (s *KeyGeneratorUnwrapStub) Returns(result []byte, err error) *KeyGeneratorUnwrapStub {
	s.fallback = &keyGeneratorUnwrapReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Unwrap.
func (s *KeyGeneratorUnwrapStub) Func(fn func(context.Context, []byte) ([]byte, error)) *KeyGeneratorUnwrapStub {
	s.fn = fn
	return s
}

// KeyGeneratorWrapStub controls behavior and records calls for Wrap.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type KeyGeneratorWrapStub struct {
	*stub.MethodStub[KeyGeneratorWrapCall]
	fn       func(context.Context, []byte) ([]byte, error)
	fallback *keyGeneratorWrapReturn
}

type keyGeneratorWrapReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Wrap.
func (s *KeyGeneratorWrapStub) Returns(result []byte, err error) *KeyGeneratorWrapStub {
	s.fallback = &keyGeneratorWrapReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Wrap.
func (s *KeyGeneratorWrapStub) Func(fn func(context.Context, []byte) ([]byte, error)) *KeyGeneratorWrapStub {
	s.fn = fn
	return s
}

// --- KeyGeneratorStub ---

// KeyGeneratorStubOption configures a [KeyGeneratorStub] at construction time.
type KeyGeneratorStubOption func(*KeyGeneratorStub)

// KeyGeneratorStubStrict enables strict mode — unconfigured methods fail the test.
func KeyGeneratorStubStrict() KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) { s.strict = true }
}

// KeyGeneratorStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func KeyGeneratorStubDelegateTo(impl crypto.KeyGenerator) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) {
		s.OnGenerateKey.Func(impl.GenerateKey)
		s.OnKeyID.Func(impl.KeyID)
		s.OnUnwrap.Func(impl.Unwrap)
		s.OnWrap.Func(impl.Wrap)
	}
}

// KeyGeneratorStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func KeyGeneratorStubWithClock(clk clock.Clock) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) {
		s.OnGenerateKey.WithClock(clk)
		s.OnKeyID.WithClock(clk)
		s.OnUnwrap.WithClock(clk)
		s.OnWrap.WithClock(clk)
	}
}

// KeyGeneratorStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func KeyGeneratorStubWithRandSource(src rand.Source) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) {
		s.OnGenerateKey.WithRandSource(src)
		s.OnKeyID.WithRandSource(src)
		s.OnUnwrap.WithRandSource(src)
		s.OnWrap.WithRandSource(src)
	}
}

// KeyGeneratorStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func KeyGeneratorStubBenchMode() KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) {
		s.OnGenerateKey.BenchMode()
		s.OnKeyID.BenchMode()
		s.OnUnwrap.BenchMode()
		s.OnWrap.BenchMode()
	}
}

// WithKeyGeneratorGenerateKey sets a function override at construction time.
func WithKeyGeneratorGenerateKey(fn func(context.Context, int) ([]byte, []byte, error)) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) { s.OnGenerateKey.Func(fn) }
}

// WithKeyGeneratorKeyID sets a function override at construction time.
func WithKeyGeneratorKeyID(fn func() string) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) { s.OnKeyID.Func(fn) }
}

// WithKeyGeneratorUnwrap sets a function override at construction time.
func WithKeyGeneratorUnwrap(fn func(context.Context, []byte) ([]byte, error)) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) { s.OnUnwrap.Func(fn) }
}

// WithKeyGeneratorWrap sets a function override at construction time.
func WithKeyGeneratorWrap(fn func(context.Context, []byte) ([]byte, error)) KeyGeneratorStubOption {
	return func(s *KeyGeneratorStub) { s.OnWrap.Func(fn) }
}

// KeyGeneratorStub is a configurable test double for [crypto.KeyGenerator].
type KeyGeneratorStub struct {
	OnGenerateKey *KeyGeneratorGenerateKeyStub
	OnKeyID       *KeyGeneratorKeyIDStub
	OnUnwrap      *KeyGeneratorUnwrapStub
	OnWrap        *KeyGeneratorWrapStub
	strict        bool
}

// NewKeyGeneratorStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewKeyGeneratorStub(tb testing.TB, opts ...KeyGeneratorStubOption) *KeyGeneratorStub {
	s := &KeyGeneratorStub{
		OnGenerateKey: &KeyGeneratorGenerateKeyStub{MethodStub: stub.NewMethodStub[KeyGeneratorGenerateKeyCall](tb, "KeyGenerator.GenerateKey")},
		OnKeyID:       &KeyGeneratorKeyIDStub{MethodStub: stub.NewMethodStub[KeyGeneratorKeyIDCall](tb, "KeyGenerator.KeyID")},
		OnUnwrap:      &KeyGeneratorUnwrapStub{MethodStub: stub.NewMethodStub[KeyGeneratorUnwrapCall](tb, "KeyGenerator.Unwrap")},
		OnWrap:        &KeyGeneratorWrapStub{MethodStub: stub.NewMethodStub[KeyGeneratorWrapCall](tb, "KeyGenerator.Wrap")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnGenerateKey.Strict()
		s.OnKeyID.Strict()
		s.OnUnwrap.Strict()
		s.OnWrap.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnGenerateKey.Verify()
				s.OnKeyID.Verify()
				s.OnUnwrap.Verify()
				s.OnWrap.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *KeyGeneratorStub) ResetCalls() {
	s.OnGenerateKey.Reset()
	s.OnKeyID.Reset()
	s.OnUnwrap.Reset()
	s.OnWrap.Reset()
}

// --- Interface method implementations ---

func (s *KeyGeneratorStub) GenerateKey(ctx context.Context, size int) ([]byte, []byte, error) {
	s.OnGenerateKey.SleepLatency()
	call := KeyGeneratorGenerateKeyCall{Ctx: ctx, Size: size}
	if fired, faultErr := s.OnGenerateKey.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnGenerateKey.Record(call)
		return nil, nil, faultErr
	}
	if s.OnGenerateKey.fn != nil {
		r0, r1, r2 := s.OnGenerateKey.fn(ctx, size)
		call.Plaintext = r0
		call.Wrapped = r1
		call.Err = r2
		s.OnGenerateKey.Record(call)
		return r0, r1, r2
	}
	if s.OnGenerateKey.fallback != nil {
		f := s.OnGenerateKey.fallback
		call.Plaintext = f.Plaintext
		call.Wrapped = f.Wrapped
		call.Err = f.Err
		s.OnGenerateKey.Record(call)
		return f.Plaintext, f.Wrapped, f.Err
	}
	s.OnGenerateKey.FailUnexpectedCall(call)
	s.OnGenerateKey.Record(call)
	return nil, nil, nil
}

func (s *KeyGeneratorStub) KeyID() string {
	s.OnKeyID.SleepLatency()
	call := KeyGeneratorKeyIDCall{}
	if s.OnKeyID.fn != nil {
		r0 := s.OnKeyID.fn()
		call.Result = r0
		s.OnKeyID.Record(call)
		return r0
	}
	if s.OnKeyID.fallback != nil {
		f := s.OnKeyID.fallback
		call.Result = f.Result
		s.OnKeyID.Record(call)
		return f.Result
	}
	s.OnKeyID.FailUnexpectedCall(call)
	s.OnKeyID.Record(call)
	return ""
}

func (s *KeyGeneratorStub) Unwrap(ctx context.Context, wrapped []byte) ([]byte, error) {
	s.OnUnwrap.SleepLatency()
	call := KeyGeneratorUnwrapCall{Ctx: ctx, Wrapped: wrapped}
	if fired, faultErr := s.OnUnwrap.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnUnwrap.Record(call)
		return nil, faultErr
	}
	if s.OnUnwrap.fn != nil {
		r0, r1 := s.OnUnwrap.fn(ctx, wrapped)
		call.Result = r0
		call.Err = r1
		s.OnUnwrap.Record(call)
		return r0, r1
	}
	if s.OnUnwrap.fallback != nil {
		f := s.OnUnwrap.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnUnwrap.Record(call)
		return f.Result, f.Err
	}
	s.OnUnwrap.FailUnexpectedCall(call)
	s.OnUnwrap.Record(call)
	return nil, nil
}

func (s *KeyGeneratorStub) Wrap(ctx context.Context, dek []byte) ([]byte, error) {
	s.OnWrap.SleepLatency()
	call := KeyGeneratorWrapCall{Ctx: ctx, Dek: dek}
	if fired, faultErr := s.OnWrap.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnWrap.Record(call)
		return nil, faultErr
	}
	if s.OnWrap.fn != nil {
		r0, r1 := s.OnWrap.fn(ctx, dek)
		call.Result = r0
		call.Err = r1
		s.OnWrap.Record(call)
		return r0, r1
	}
	if s.OnWrap.fallback != nil {
		f := s.OnWrap.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnWrap.Record(call)
		return f.Result, f.Err
	}
	s.OnWrap.FailUnexpectedCall(call)
	s.OnWrap.Record(call)
	return nil, nil
}
