// Code generated by testkit stub. DO NOT EDIT.
// Source: mac.go:93-128 (testkit stub MAC)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ crypto.MAC = (*MACStub)(nil)

// --- Call types ---

// MACAlgorithmCall records one invocation of crypto.MAC.Algorithm.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACAlgorithmCall struct {
	Result crypto.Algorithm
}

// MACIDCall records one invocation of crypto.MAC.ID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACIDCall struct {
	Result crypto.ID
}

// MACNewStreamCall records one invocation of crypto.MAC.NewStream.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACNewStreamCall struct {
	Result crypto.Stream
}

// MACSignCall records one invocation of crypto.MAC.Sign.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACSignCall struct {
	Data   []byte
	Result crypto.Digest
}

// MACSizeCall records one invocation of crypto.MAC.Size.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACSizeCall struct {
	Result int
}

// MACVerifyCall records one invocation of crypto.MAC.Verify.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type MACVerifyCall struct {
	Data     []byte
	Expected []byte
	Result   bool
}

// --- Per-method stubs ---

// MACAlgorithmStub controls behavior and records calls for Algorithm.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACAlgorithmStub struct {
	*stub.MethodStub[MACAlgorithmCall]
	fn       func() crypto.Algorithm
	fallback *mACAlgorithmReturn
}

type mACAlgorithmReturn struct {
	Result crypto.Algorithm
}

// Returns sets a fixed return value for Algorithm.
func (s *MACAlgorithmStub) Returns(result crypto.Algorithm) *MACAlgorithmStub {
	s.fallback = &mACAlgorithmReturn{Result: result}
	return s
}

// Func sets a function override for Algorithm.
func (s *MACAlgorithmStub) Func(fn func() crypto.Algorithm) *MACAlgorithmStub {
	s.fn = fn
	return s
}

// MACIDStub controls behavior and records calls for ID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACIDStub struct {
	*stub.MethodStub[MACIDCall]
	fn       func() crypto.ID
	fallback *mACIDReturn
}

type mACIDReturn struct {
	Result crypto.ID
}

// Returns sets a fixed return value for ID.
func (s *MACIDStub) Returns(result crypto.ID) *MACIDStub {
	s.fallback = &mACIDReturn{Result: result}
	return s
}

// Func sets a function override for ID.
func (s *MACIDStub) Func(fn func() crypto.ID) *MACIDStub {
	s.fn = fn
	return s
}

// MACNewStreamStub controls behavior and records calls for NewStream.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACNewStreamStub struct {
	*stub.MethodStub[MACNewStreamCall]
	fn       func() crypto.Stream
	fallback *mACNewStreamReturn
}

type mACNewStreamReturn struct {
	Result crypto.Stream
}

// Returns sets a fixed return value for NewStream.
func (s *MACNewStreamStub) Returns(result crypto.Stream) *MACNewStreamStub {
	s.fallback = &mACNewStreamReturn{Result: result}
	return s
}

// Func sets a function override for NewStream.
func (s *MACNewStreamStub) Func(fn func() crypto.Stream) *MACNewStreamStub {
	s.fn = fn
	return s
}

// MACSignStub controls behavior and records calls for Sign.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACSignStub struct {
	*stub.MethodStub[MACSignCall]
	fn       func([]byte) crypto.Digest
	fallback *mACSignReturn
}

type mACSignReturn struct {
	Result crypto.Digest
}

// Returns sets a fixed return value for Sign.
func (s *MACSignStub) Returns(result crypto.Digest) *MACSignStub {
	s.fallback = &mACSignReturn{Result: result}
	return s
}

// Func sets a function override for Sign.
func (s *MACSignStub) Func(fn func([]byte) crypto.Digest) *MACSignStub {
	s.fn = fn
	return s
}

// MACSizeStub controls behavior and records calls for Size.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACSizeStub struct {
	*stub.MethodStub[MACSizeCall]
	fn       func() int
	fallback *mACSizeReturn
}

type mACSizeReturn struct {
	Result int
}

// Returns sets a fixed return value for Size.
func (s *MACSizeStub) Returns(result int) *MACSizeStub {
	s.fallback = &mACSizeReturn{Result: result}
	return s
}

// Func sets a function override for Size.
func (s *MACSizeStub) Func(fn func() int) *MACSizeStub {
	s.fn = fn
	return s
}

// MACVerifyStub controls behavior and records calls for Verify.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type MACVerifyStub struct {
	*stub.MethodStub[MACVerifyCall]
	fn       func([]byte, []byte) bool
	fallback *mACVerifyReturn
}

type mACVerifyReturn struct {
	Result bool
}

// Returns sets a fixed return value for Verify.
func (s *MACVerifyStub) Returns(result bool) *MACVerifyStub {
	s.fallback = &mACVerifyReturn{Result: result}
	return s
}

// Func sets a function override for Verify.
func (s *MACVerifyStub) Func(fn func([]byte, []byte) bool) *MACVerifyStub {
	s.fn = fn
	return s
}

// --- MACStub ---

// MACStubOption configures a [MACStub] at construction time.
type MACStubOption func(*MACStub)

// MACStubStrict enables strict mode — unconfigured methods fail the test.
func MACStubStrict() MACStubOption {
	return func(s *MACStub) { s.strict = true }
}

// MACStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func MACStubDelegateTo(impl crypto.MAC) MACStubOption {
	return func(s *MACStub) {
		s.OnAlgorithm.Func(impl.Algorithm)
		s.OnID.Func(impl.ID)
		s.OnNewStream.Func(impl.NewStream)
		s.OnSign.Func(impl.Sign)
		s.OnSize.Func(impl.Size)
		s.OnVerify.Func(impl.Verify)
	}
}

// MACStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func MACStubWithClock(clk clock.Clock) MACStubOption {
	return func(s *MACStub) {
		s.OnAlgorithm.WithClock(clk)
		s.OnID.WithClock(clk)
		s.OnNewStream.WithClock(clk)
		s.OnSign.WithClock(clk)
		s.OnSize.WithClock(clk)
		s.OnVerify.WithClock(clk)
	}
}

// MACStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func MACStubWithRandSource(src rand.Source) MACStubOption {
	return func(s *MACStub) {
		s.OnAlgorithm.WithRandSource(src)
		s.OnID.WithRandSource(src)
		s.OnNewStream.WithRandSource(src)
		s.OnSign.WithRandSource(src)
		s.OnSize.WithRandSource(src)
		s.OnVerify.WithRandSource(src)
	}
}

// MACStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func MACStubBenchMode() MACStubOption {
	return func(s *MACStub) {
		s.OnAlgorithm.BenchMode()
		s.OnID.BenchMode()
		s.OnNewStream.BenchMode()
		s.OnSign.BenchMode()
		s.OnSize.BenchMode()
		s.OnVerify.BenchMode()
	}
}

// WithMACAlgorithm sets a function override at construction time.
func WithMACAlgorithm(fn func() crypto.Algorithm) MACStubOption {
	return func(s *MACStub) { s.OnAlgorithm.Func(fn) }
}

// WithMACID sets a function override at construction time.
func WithMACID(fn func() crypto.ID) MACStubOption {
	return func(s *MACStub) { s.OnID.Func(fn) }
}

// WithMACNewStream sets a function override at construction time.
func WithMACNewStream(fn func() crypto.Stream) MACStubOption {
	return func(s *MACStub) { s.OnNewStream.Func(fn) }
}

// WithMACSign sets a function override at construction time.
func WithMACSign(fn func([]byte) crypto.Digest) MACStubOption {
	return func(s *MACStub) { s.OnSign.Func(fn) }
}

// WithMACSize sets a function override at construction time.
func WithMACSize(fn func() int) MACStubOption {
	return func(s *MACStub) { s.OnSize.Func(fn) }
}

// WithMACVerify sets a function override at construction time.
func WithMACVerify(fn func([]byte, []byte) bool) MACStubOption {
	return func(s *MACStub) { s.OnVerify.Func(fn) }
}

// MACStub is a configurable test double for [crypto.MAC].
type MACStub struct {
	OnAlgorithm *MACAlgorithmStub
	OnID        *MACIDStub
	OnNewStream *MACNewStreamStub
	OnSign      *MACSignStub
	OnSize      *MACSizeStub
	OnVerify    *MACVerifyStub
	strict      bool
}

// NewMACStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewMACStub(tb testing.TB, opts ...MACStubOption) *MACStub {
	s := &MACStub{
		OnAlgorithm: &MACAlgorithmStub{MethodStub: stub.NewMethodStub[MACAlgorithmCall](tb, "MAC.Algorithm")},
		OnID:        &MACIDStub{MethodStub: stub.NewMethodStub[MACIDCall](tb, "MAC.ID")},
		OnNewStream: &MACNewStreamStub{MethodStub: stub.NewMethodStub[MACNewStreamCall](tb, "MAC.NewStream")},
		OnSign:      &MACSignStub{MethodStub: stub.NewMethodStub[MACSignCall](tb, "MAC.Sign")},
		OnSize:      &MACSizeStub{MethodStub: stub.NewMethodStub[MACSizeCall](tb, "MAC.Size")},
		OnVerify:    &MACVerifyStub{MethodStub: stub.NewMethodStub[MACVerifyCall](tb, "MAC.Verify")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnAlgorithm.Strict()
		s.OnID.Strict()
		s.OnNewStream.Strict()
		s.OnSign.Strict()
		s.OnSize.Strict()
		s.OnVerify.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnAlgorithm.Verify()
				s.OnID.Verify()
				s.OnNewStream.Verify()
				s.OnSign.Verify()
				s.OnSize.Verify()
				s.OnVerify.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *MACStub) ResetCalls() {
	s.OnAlgorithm.Reset()
	s.OnID.Reset()
	s.OnNewStream.Reset()
	s.OnSign.Reset()
	s.OnSize.Reset()
	s.OnVerify.Reset()
}

// --- Interface method implementations ---

func (s *MACStub) Algorithm() crypto.Algorithm {
	s.OnAlgorithm.SleepLatency()
	call := MACAlgorithmCall{}
	if s.OnAlgorithm.fn != nil {
		r0 := s.OnAlgorithm.fn()
		call.Result = r0
		s.OnAlgorithm.Record(call)
		return r0
	}
	if s.OnAlgorithm.fallback != nil {
		f := s.OnAlgorithm.fallback
		call.Result = f.Result
		s.OnAlgorithm.Record(call)
		return f.Result
	}
	s.OnAlgorithm.FailUnexpectedCall(call)
	s.OnAlgorithm.Record(call)
	return ""
}

func (s *MACStub) ID() crypto.ID {
	s.OnID.SleepLatency()
	call := MACIDCall{}
	if s.OnID.fn != nil {
		r0 := s.OnID.fn()
		call.Result = r0
		s.OnID.Record(call)
		return r0
	}
	if s.OnID.fallback != nil {
		f := s.OnID.fallback
		call.Result = f.Result
		s.OnID.Record(call)
		return f.Result
	}
	s.OnID.FailUnexpectedCall(call)
	s.OnID.Record(call)
	return crypto.ID{}
}

func (s *MACStub) NewStream() crypto.Stream {
	s.OnNewStream.SleepLatency()
	call := MACNewStreamCall{}
	if s.OnNewStream.fn != nil {
		r0 := s.OnNewStream.fn()
		call.Result = r0
		s.OnNewStream.Record(call)
		return r0
	}
	if s.OnNewStream.fallback != nil {
		f := s.OnNewStream.fallback
		call.Result = f.Result
		s.OnNewStream.Record(call)
		return f.Result
	}
	s.OnNewStream.FailUnexpectedCall(call)
	s.OnNewStream.Record(call)
	return nil
}

func (s *MACStub) Sign(data []byte) crypto.Digest {
	s.OnSign.SleepLatency()
	call := MACSignCall{Data: data}
	if s.OnSign.fn != nil {
		r0 := s.OnSign.fn(data)
		call.Result = r0
		s.OnSign.Record(call)
		return r0
	}
	if s.OnSign.fallback != nil {
		f := s.OnSign.fallback
		call.Result = f.Result
		s.OnSign.Record(call)
		return f.Result
	}
	s.OnSign.FailUnexpectedCall(call)
	s.OnSign.Record(call)
	return crypto.Digest{}
}

func (s *MACStub) Size() int {
	s.OnSize.SleepLatency()
	call := MACSizeCall{}
	if s.OnSize.fn != nil {
		r0 := s.OnSize.fn()
		call.Result = r0
		s.OnSize.Record(call)
		return r0
	}
	if s.OnSize.fallback != nil {
		f := s.OnSize.fallback
		call.Result = f.Result
		s.OnSize.Record(call)
		return f.Result
	}
	s.OnSize.FailUnexpectedCall(call)
	s.OnSize.Record(call)
	return 0
}

func (s *MACStub) Verify(data []byte, expected []byte) bool {
	s.OnVerify.SleepLatency()
	call := MACVerifyCall{Data: data, Expected: expected}
	if s.OnVerify.fn != nil {
		r0 := s.OnVerify.fn(data, expected)
		call.Result = r0
		s.OnVerify.Record(call)
		return r0
	}
	if s.OnVerify.fallback != nil {
		f := s.OnVerify.fallback
		call.Result = f.Result
		s.OnVerify.Record(call)
		return f.Result
	}
	s.OnVerify.FailUnexpectedCall(call)
	s.OnVerify.Record(call)
	return false
}
