// Code generated by testkit suite. DO NOT EDIT.
// Source: mac.go:93-128 (testkit suite MAC)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertMACContract runs conformance assertions against
// implementations of [crypto.MAC] produced by factory.
//
//	Default subtests: 9 across 6 methods
//	Shapes detected:  Pure (Algorithm, ID, NewStream, Sign, Size), Predicate (Verify)
//	Directives:       none
//	Plug-in points:   MACOnAlgorithm, MACOnID, MACOnNewStream, MACOnSign, MACOnSize, MACOnVerify, MACOnAll, MACCustom
func AssertMACContract(
	t *testing.T,
	factory func() crypto.MAC,
	opts ...MACOption,
) {
	t.Helper()
	cfg := newMACConfig(opts...)

	runMACAlgorithm(t, factory, &cfg)
	runMACID(t, factory, &cfg)
	runMACNewStream(t, factory, &cfg)
	runMACSign(t, factory, &cfg)
	runMACSize(t, factory, &cfg)
	runMACVerify(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[crypto.MAC]{
			T:             t,
			CrossBindings: bindings.CrossBindings[crypto.MAC]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runMACAlgorithm(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("Algorithm/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Algorithm panicked on zero-value args (%v) — supply sample values via MACOnAlgorithm", r)
			}
		}()
		s := factory()
		_ = s.Algorithm()
	})
	if len(cfg.onAlgorithm) > 0 {
		t.Run("Algorithm", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.MAC, crypto.Algorithm]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.MAC, crypto.Algorithm]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) crypto.Algorithm {
						return impl.Algorithm()
					},
				},
			}
			for _, a := range cfg.onAlgorithm {
				a(pctx)
			}
		})
	}
}

func runMACID(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("ID/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: ID panicked on zero-value args (%v) — supply sample values via MACOnID", r)
			}
		}()
		s := factory()
		_ = s.ID()
	})
	if len(cfg.onID) > 0 {
		t.Run("ID", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.MAC, crypto.ID]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.MAC, crypto.ID]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) crypto.ID {
						return impl.ID()
					},
				},
			}
			for _, a := range cfg.onID {
				a(pctx)
			}
		})
	}
}

func runMACNewStream(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("NewStream/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: NewStream panicked on zero-value args (%v) — supply sample values via MACOnNewStream", r)
			}
		}()
		s := factory()
		_ = s.NewStream()
	})
	if len(cfg.onNewStream) > 0 {
		t.Run("NewStream", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.MAC, crypto.Stream]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.MAC, crypto.Stream]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) crypto.Stream {
						return impl.NewStream()
					},
				},
			}
			for _, a := range cfg.onNewStream {
				a(pctx)
			}
		})
	}
}

func runMACSign(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("Sign/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Sign panicked on zero-value args (%v) — supply sample values via MACOnSign", r)
			}
		}()
		s := factory()
		_ = s.Sign(nil)
	})

	t.Run("Sign/nil data", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Sign(nil)
		})
	})
	if len(cfg.onSign) > 0 {
		t.Run("Sign", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.MAC, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.MAC, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) crypto.Digest {
						return impl.Sign(nil)
					},
				},
			}
			for _, a := range cfg.onSign {
				a(pctx)
			}
		})
	}
}

func runMACSize(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("Size/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Size panicked on zero-value args (%v) — supply sample values via MACOnSize", r)
			}
		}()
		s := factory()
		_ = s.Size()
	})
	if len(cfg.onSize) > 0 {
		t.Run("Size", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.MAC, int]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.MAC, int]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) int {
						return impl.Size()
					},
				},
			}
			for _, a := range cfg.onSize {
				a(pctx)
			}
		})
	}
}

func runMACVerify(t *testing.T, factory func() crypto.MAC, cfg *mACConfig) {
	t.Helper()

	t.Run("Verify/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Verify panicked on zero-value args (%v) — supply sample values via MACOnVerify", r)
			}
		}()
		s := factory()
		_ = s.Verify(nil, nil)
	})

	t.Run("Verify/nil data", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Verify(nil, nil)
		})
	})

	t.Run("Verify/nil expected", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Verify(nil, nil)
		})
	})
	if len(cfg.onVerify) > 0 {
		t.Run("Verify", func(t *testing.T) {
			prePopFactory := func() crypto.MAC {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PredicateContext[crypto.MAC]{
				T: t,
				PredicateBindings: bindings.PredicateBindings[crypto.MAC]{
					Factory: prePopFactory,
					Call: func(impl crypto.MAC) bool {
						return impl.Verify(nil, nil)
					},
				},
			}
			for _, a := range cfg.onVerify {
				a(pctx)
			}
		})
	}
}

// MACOption configures [AssertMACContract].
type MACOption func(*mACConfig)

// MACPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func MACPrePopulate(fn func(ctx context.Context, s crypto.MAC)) MACOption {
	return func(c *mACConfig) { c.prePopulate = fn }
}

// MACCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func MACCustom(name string, fn func(*testing.T, crypto.MAC)) MACOption {
	return func(c *mACConfig) {
		c.custom = append(c.custom, mACCustomSubtest{name: name, fn: fn})
	}
}

// MACOnAlgorithm adds plug-in assertions for the Algorithm method.
func MACOnAlgorithm(assertions ...suite.PureAssertion[crypto.MAC, crypto.Algorithm]) MACOption {
	return func(c *mACConfig) {
		c.onAlgorithm = append(c.onAlgorithm, assertions...)
	}
}

// MACOnID adds plug-in assertions for the ID method.
func MACOnID(assertions ...suite.PureAssertion[crypto.MAC, crypto.ID]) MACOption {
	return func(c *mACConfig) {
		c.onID = append(c.onID, assertions...)
	}
}

// MACOnNewStream adds plug-in assertions for the NewStream method.
func MACOnNewStream(assertions ...suite.PureAssertion[crypto.MAC, crypto.Stream]) MACOption {
	return func(c *mACConfig) {
		c.onNewStream = append(c.onNewStream, assertions...)
	}
}

// MACOnSign adds plug-in assertions for the Sign method.
func MACOnSign(assertions ...suite.PureAssertion[crypto.MAC, crypto.Digest]) MACOption {
	return func(c *mACConfig) {
		c.onSign = append(c.onSign, assertions...)
	}
}

// MACOnSize adds plug-in assertions for the Size method.
func MACOnSize(assertions ...suite.PureAssertion[crypto.MAC, int]) MACOption {
	return func(c *mACConfig) {
		c.onSize = append(c.onSize, assertions...)
	}
}

// MACOnVerify adds plug-in assertions for the Verify method.
func MACOnVerify(assertions ...suite.PredicateAssertion[crypto.MAC]) MACOption {
	return func(c *mACConfig) {
		c.onVerify = append(c.onVerify, assertions...)
	}
}

// MACOnAll adds cross-method assertions that span multiple methods.
func MACOnAll(assertions ...suite.CrossMethodAssertion[crypto.MAC]) MACOption {
	return func(c *mACConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type mACCustomSubtest struct {
	name string
	fn   func(*testing.T, crypto.MAC)
}

type mACConfig struct {
	prePopulate func(context.Context, crypto.MAC)
	custom      []mACCustomSubtest
	onAll       []suite.CrossMethodAssertion[crypto.MAC]
	onAlgorithm []suite.PureAssertion[crypto.MAC, crypto.Algorithm]
	onID        []suite.PureAssertion[crypto.MAC, crypto.ID]
	onNewStream []suite.PureAssertion[crypto.MAC, crypto.Stream]
	onSign      []suite.PureAssertion[crypto.MAC, crypto.Digest]
	onSize      []suite.PureAssertion[crypto.MAC, int]
	onVerify    []suite.PredicateAssertion[crypto.MAC]
}

func newMACConfig(opts ...MACOption) mACConfig {
	var cfg mACConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
