// Code generated by testkit suite. DO NOT EDIT.
// Source: sign.go:93-185 (testkit suite Signer)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/core/crypto/sign"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertSignerContract runs conformance assertions against
// implementations of [sign.Signer] produced by factory.
//
//	Default subtests: 8 across 5 methods
//	Shapes detected:  Pure (Algorithm, KeyID, PublicKey), Predicate (Verify), Unknown (Sign)
//	Directives:       none
//	Plug-in points:   SignerOnAlgorithm, SignerOnKeyID, SignerOnPublicKey, SignerOnSign, SignerOnVerify, SignerOnAll, SignerCustom
func AssertSignerContract(
	t *testing.T,
	factory func() sign.Signer,
	opts ...SignerOption,
) {
	t.Helper()
	cfg := newSignerConfig(opts...)

	runSignerAlgorithm(t, factory, &cfg)
	runSignerKeyID(t, factory, &cfg)
	runSignerPublicKey(t, factory, &cfg)
	runSignerSign(t, factory, &cfg)
	runSignerVerify(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[sign.Signer]{
			T:             t,
			CrossBindings: bindings.CrossBindings[sign.Signer]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runSignerAlgorithm(t *testing.T, factory func() sign.Signer, cfg *signerConfig) {
	t.Helper()

	t.Run("Algorithm/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Algorithm panicked on zero-value args (%v) — supply sample values via SignerOnAlgorithm", r)
			}
		}()
		s := factory()
		_ = s.Algorithm()
	})
	if len(cfg.onAlgorithm) > 0 {
		t.Run("Algorithm", func(t *testing.T) {
			prePopFactory := func() sign.Signer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[sign.Signer, crypto.Algorithm]{
				T: t,
				PureBindings: bindings.PureBindings[sign.Signer, crypto.Algorithm]{
					Factory: prePopFactory,
					Call: func(impl sign.Signer) crypto.Algorithm {
						return impl.Algorithm()
					},
				},
			}
			for _, a := range cfg.onAlgorithm {
				a(pctx)
			}
		})
	}
}

func runSignerKeyID(t *testing.T, factory func() sign.Signer, cfg *signerConfig) {
	t.Helper()

	t.Run("KeyID/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: KeyID panicked on zero-value args (%v) — supply sample values via SignerOnKeyID", r)
			}
		}()
		s := factory()
		_ = s.KeyID()
	})
	if len(cfg.onKeyID) > 0 {
		t.Run("KeyID", func(t *testing.T) {
			prePopFactory := func() sign.Signer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[sign.Signer, sign.KeyID]{
				T: t,
				PureBindings: bindings.PureBindings[sign.Signer, sign.KeyID]{
					Factory: prePopFactory,
					Call: func(impl sign.Signer) sign.KeyID {
						return impl.KeyID()
					},
				},
			}
			for _, a := range cfg.onKeyID {
				a(pctx)
			}
		})
	}
}

func runSignerPublicKey(t *testing.T, factory func() sign.Signer, cfg *signerConfig) {
	t.Helper()

	t.Run("PublicKey/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: PublicKey panicked on zero-value args (%v) — supply sample values via SignerOnPublicKey", r)
			}
		}()
		s := factory()
		_ = s.PublicKey()
	})
	if len(cfg.onPublicKey) > 0 {
		t.Run("PublicKey", func(t *testing.T) {
			prePopFactory := func() sign.Signer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[sign.Signer, []byte]{
				T: t,
				PureBindings: bindings.PureBindings[sign.Signer, []byte]{
					Factory: prePopFactory,
					Call: func(impl sign.Signer) []byte {
						return impl.PublicKey()
					},
				},
			}
			for _, a := range cfg.onPublicKey {
				a(pctx)
			}
		})
	}
}

func runSignerSign(t *testing.T, factory func() sign.Signer, cfg *signerConfig) {
	t.Helper()

	t.Run("Sign/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Sign panicked on zero-value args (%v) — supply sample values via SignerOnSign", r)
			}
		}()
		s := factory()
		_, _ = s.Sign(nil)
	})

	t.Run("Sign/nil message", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Sign(nil)
		})
	})
	if len(cfg.onSign) > 0 {
		t.Run("Sign", func(t *testing.T) {
			for _, fn := range cfg.onSign {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runSignerVerify(t *testing.T, factory func() sign.Signer, cfg *signerConfig) {
	t.Helper()

	t.Run("Verify/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Verify panicked on zero-value args (%v) — supply sample values via SignerOnVerify", r)
			}
		}()
		s := factory()
		_ = s.Verify(nil, nil)
	})

	t.Run("Verify/nil message", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Verify(nil, nil)
		})
	})

	t.Run("Verify/nil signature", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Verify(nil, nil)
		})
	})
	if len(cfg.onVerify) > 0 {
		t.Run("Verify", func(t *testing.T) {
			prePopFactory := func() sign.Signer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PredicateContext[sign.Signer]{
				T: t,
				PredicateBindings: bindings.PredicateBindings[sign.Signer]{
					Factory: prePopFactory,
					Call: func(impl sign.Signer) bool {
						return impl.Verify(nil, nil)
					},
				},
			}
			for _, a := range cfg.onVerify {
				a(pctx)
			}
		})
	}
}

// SignerOption configures [AssertSignerContract].
type SignerOption func(*signerConfig)

// SignerPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func SignerPrePopulate(fn func(ctx context.Context, s sign.Signer)) SignerOption {
	return func(c *signerConfig) { c.prePopulate = fn }
}

// SignerCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func SignerCustom(name string, fn func(*testing.T, sign.Signer)) SignerOption {
	return func(c *signerConfig) {
		c.custom = append(c.custom, signerCustomSubtest{name: name, fn: fn})
	}
}

// SignerOnAlgorithm adds plug-in assertions for the Algorithm method.
func SignerOnAlgorithm(assertions ...suite.PureAssertion[sign.Signer, crypto.Algorithm]) SignerOption {
	return func(c *signerConfig) {
		c.onAlgorithm = append(c.onAlgorithm, assertions...)
	}
}

// SignerOnKeyID adds plug-in assertions for the KeyID method.
func SignerOnKeyID(assertions ...suite.PureAssertion[sign.Signer, sign.KeyID]) SignerOption {
	return func(c *signerConfig) {
		c.onKeyID = append(c.onKeyID, assertions...)
	}
}

// SignerOnPublicKey adds plug-in assertions for the PublicKey method.
func SignerOnPublicKey(assertions ...suite.PureAssertion[sign.Signer, []byte]) SignerOption {
	return func(c *signerConfig) {
		c.onPublicKey = append(c.onPublicKey, assertions...)
	}
}

// SignerOnSign adds plug-in assertions for the Sign method.
func SignerOnSign(assertions ...func(*testing.T, sign.Signer)) SignerOption {
	return func(c *signerConfig) {
		c.onSign = append(c.onSign, assertions...)
	}
}

// SignerOnVerify adds plug-in assertions for the Verify method.
func SignerOnVerify(assertions ...suite.PredicateAssertion[sign.Signer]) SignerOption {
	return func(c *signerConfig) {
		c.onVerify = append(c.onVerify, assertions...)
	}
}

// SignerOnAll adds cross-method assertions that span multiple methods.
func SignerOnAll(assertions ...suite.CrossMethodAssertion[sign.Signer]) SignerOption {
	return func(c *signerConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type signerCustomSubtest struct {
	name string
	fn   func(*testing.T, sign.Signer)
}

type signerConfig struct {
	prePopulate func(context.Context, sign.Signer)
	custom      []signerCustomSubtest
	onAll       []suite.CrossMethodAssertion[sign.Signer]
	onAlgorithm []suite.PureAssertion[sign.Signer, crypto.Algorithm]
	onKeyID     []suite.PureAssertion[sign.Signer, sign.KeyID]
	onPublicKey []suite.PureAssertion[sign.Signer, []byte]
	onSign      []func(*testing.T, sign.Signer)
	onVerify    []suite.PredicateAssertion[sign.Signer]
}

func newSignerConfig(opts ...SignerOption) signerConfig {
	var cfg signerConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
