// Code generated by testkit stub. DO NOT EDIT.
// Source: sign.go:93-185 (testkit stub Signer)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/core/crypto/sign"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ sign.Signer = (*SignerStub)(nil)

// --- Call types ---

// SignerAlgorithmCall records one invocation of sign.Signer.Algorithm.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type SignerAlgorithmCall struct {
	Result crypto.Algorithm
}

// SignerKeyIDCall records one invocation of sign.Signer.KeyID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type SignerKeyIDCall struct {
	Result sign.KeyID
}

// SignerPublicKeyCall records one invocation of sign.Signer.PublicKey.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type SignerPublicKeyCall struct {
	Result []byte
}

// SignerSignCall records one invocation of sign.Signer.Sign.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type SignerSignCall struct {
	Message []byte
	Result  []byte
	Err     error
}

// SignerVerifyCall records one invocation of sign.Signer.Verify.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type SignerVerifyCall struct {
	Message   []byte
	Signature []byte
	Result    bool
}

// --- Per-method stubs ---

// SignerAlgorithmStub controls behavior and records calls for Algorithm.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type SignerAlgorithmStub struct {
	*stub.MethodStub[SignerAlgorithmCall]
	fn       func() crypto.Algorithm
	fallback *signerAlgorithmReturn
}

type signerAlgorithmReturn struct {
	Result crypto.Algorithm
}

// Returns sets a fixed return value for Algorithm.
func (s *SignerAlgorithmStub) Returns(result crypto.Algorithm) *SignerAlgorithmStub {
	s.fallback = &signerAlgorithmReturn{Result: result}
	return s
}

// Func sets a function override for Algorithm.
func (s *SignerAlgorithmStub) Func(fn func() crypto.Algorithm) *SignerAlgorithmStub {
	s.fn = fn
	return s
}

// SignerKeyIDStub controls behavior and records calls for KeyID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type SignerKeyIDStub struct {
	*stub.MethodStub[SignerKeyIDCall]
	fn       func() sign.KeyID
	fallback *signerKeyIDReturn
}

type signerKeyIDReturn struct {
	Result sign.KeyID
}

// Returns sets a fixed return value for KeyID.
func (s *SignerKeyIDStub) Returns(result sign.KeyID) *SignerKeyIDStub {
	s.fallback = &signerKeyIDReturn{Result: result}
	return s
}

// Func sets a function override for KeyID.
func (s *SignerKeyIDStub) Func(fn func() sign.KeyID) *SignerKeyIDStub {
	s.fn = fn
	return s
}

// SignerPublicKeyStub controls behavior and records calls for PublicKey.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type SignerPublicKeyStub struct {
	*stub.MethodStub[SignerPublicKeyCall]
	fn       func() []byte
	fallback *signerPublicKeyReturn
}

type signerPublicKeyReturn struct {
	Result []byte
}

// Returns sets a fixed return value for PublicKey.
func (s *SignerPublicKeyStub) Returns(result []byte) *SignerPublicKeyStub {
	s.fallback = &signerPublicKeyReturn{Result: result}
	return s
}

// Func sets a function override for PublicKey.
func (s *SignerPublicKeyStub) Func(fn func() []byte) *SignerPublicKeyStub {
	s.fn = fn
	return s
}

// SignerSignStub controls behavior and records calls for Sign.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type SignerSignStub struct {
	*stub.MethodStub[SignerSignCall]
	fn       func([]byte) ([]byte, error)
	fallback *signerSignReturn
}

type signerSignReturn struct {
	Result []byte
	Err    error
}

// Returns sets a fixed return value for Sign.
func (s *SignerSignStub) Returns(result []byte, err error) *SignerSignStub {
	s.fallback = &signerSignReturn{Result: result, Err: err}
	return s
}

// Func sets a function override for Sign.
func (s *SignerSignStub) Func(fn func([]byte) ([]byte, error)) *SignerSignStub {
	s.fn = fn
	return s
}

// SignerVerifyStub controls behavior and records calls for Verify.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type SignerVerifyStub struct {
	*stub.MethodStub[SignerVerifyCall]
	fn       func([]byte, []byte) bool
	fallback *signerVerifyReturn
}

type signerVerifyReturn struct {
	Result bool
}

// Returns sets a fixed return value for Verify.
func (s *SignerVerifyStub) Returns(result bool) *SignerVerifyStub {
	s.fallback = &signerVerifyReturn{Result: result}
	return s
}

// Func sets a function override for Verify.
func (s *SignerVerifyStub) Func(fn func([]byte, []byte) bool) *SignerVerifyStub {
	s.fn = fn
	return s
}

// --- SignerStub ---

// SignerStubOption configures a [SignerStub] at construction time.
type SignerStubOption func(*SignerStub)

// SignerStubStrict enables strict mode — unconfigured methods fail the test.
func SignerStubStrict() SignerStubOption {
	return func(s *SignerStub) { s.strict = true }
}

// SignerStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func SignerStubDelegateTo(impl sign.Signer) SignerStubOption {
	return func(s *SignerStub) {
		s.OnAlgorithm.Func(impl.Algorithm)
		s.OnKeyID.Func(impl.KeyID)
		s.OnPublicKey.Func(impl.PublicKey)
		s.OnSign.Func(impl.Sign)
		s.OnVerify.Func(impl.Verify)
	}
}

// SignerStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func SignerStubWithClock(clk clock.Clock) SignerStubOption {
	return func(s *SignerStub) {
		s.OnAlgorithm.WithClock(clk)
		s.OnKeyID.WithClock(clk)
		s.OnPublicKey.WithClock(clk)
		s.OnSign.WithClock(clk)
		s.OnVerify.WithClock(clk)
	}
}

// SignerStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func SignerStubWithRandSource(src rand.Source) SignerStubOption {
	return func(s *SignerStub) {
		s.OnAlgorithm.WithRandSource(src)
		s.OnKeyID.WithRandSource(src)
		s.OnPublicKey.WithRandSource(src)
		s.OnSign.WithRandSource(src)
		s.OnVerify.WithRandSource(src)
	}
}

// SignerStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func SignerStubBenchMode() SignerStubOption {
	return func(s *SignerStub) {
		s.OnAlgorithm.BenchMode()
		s.OnKeyID.BenchMode()
		s.OnPublicKey.BenchMode()
		s.OnSign.BenchMode()
		s.OnVerify.BenchMode()
	}
}

// WithSignerAlgorithm sets a function override at construction time.
func WithSignerAlgorithm(fn func() crypto.Algorithm) SignerStubOption {
	return func(s *SignerStub) { s.OnAlgorithm.Func(fn) }
}

// WithSignerKeyID sets a function override at construction time.
func WithSignerKeyID(fn func() sign.KeyID) SignerStubOption {
	return func(s *SignerStub) { s.OnKeyID.Func(fn) }
}

// WithSignerPublicKey sets a function override at construction time.
func WithSignerPublicKey(fn func() []byte) SignerStubOption {
	return func(s *SignerStub) { s.OnPublicKey.Func(fn) }
}

// WithSignerSign sets a function override at construction time.
func WithSignerSign(fn func([]byte) ([]byte, error)) SignerStubOption {
	return func(s *SignerStub) { s.OnSign.Func(fn) }
}

// WithSignerVerify sets a function override at construction time.
func WithSignerVerify(fn func([]byte, []byte) bool) SignerStubOption {
	return func(s *SignerStub) { s.OnVerify.Func(fn) }
}

// SignerStub is a configurable test double for [sign.Signer].
type SignerStub struct {
	OnAlgorithm *SignerAlgorithmStub
	OnKeyID     *SignerKeyIDStub
	OnPublicKey *SignerPublicKeyStub
	OnSign      *SignerSignStub
	OnVerify    *SignerVerifyStub
	strict      bool
}

// NewSignerStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewSignerStub(tb testing.TB, opts ...SignerStubOption) *SignerStub {
	s := &SignerStub{
		OnAlgorithm: &SignerAlgorithmStub{MethodStub: stub.NewMethodStub[SignerAlgorithmCall](tb, "Signer.Algorithm")},
		OnKeyID:     &SignerKeyIDStub{MethodStub: stub.NewMethodStub[SignerKeyIDCall](tb, "Signer.KeyID")},
		OnPublicKey: &SignerPublicKeyStub{MethodStub: stub.NewMethodStub[SignerPublicKeyCall](tb, "Signer.PublicKey")},
		OnSign:      &SignerSignStub{MethodStub: stub.NewMethodStub[SignerSignCall](tb, "Signer.Sign")},
		OnVerify:    &SignerVerifyStub{MethodStub: stub.NewMethodStub[SignerVerifyCall](tb, "Signer.Verify")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnAlgorithm.Strict()
		s.OnKeyID.Strict()
		s.OnPublicKey.Strict()
		s.OnSign.Strict()
		s.OnVerify.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnAlgorithm.Verify()
				s.OnKeyID.Verify()
				s.OnPublicKey.Verify()
				s.OnSign.Verify()
				s.OnVerify.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *SignerStub) ResetCalls() {
	s.OnAlgorithm.Reset()
	s.OnKeyID.Reset()
	s.OnPublicKey.Reset()
	s.OnSign.Reset()
	s.OnVerify.Reset()
}

// --- Interface method implementations ---

func (s *SignerStub) Algorithm() crypto.Algorithm {
	s.OnAlgorithm.SleepLatency()
	call := SignerAlgorithmCall{}
	if s.OnAlgorithm.fn != nil {
		r0 := s.OnAlgorithm.fn()
		call.Result = r0
		s.OnAlgorithm.Record(call)
		return r0
	}
	if s.OnAlgorithm.fallback != nil {
		f := s.OnAlgorithm.fallback
		call.Result = f.Result
		s.OnAlgorithm.Record(call)
		return f.Result
	}
	s.OnAlgorithm.FailUnexpectedCall(call)
	s.OnAlgorithm.Record(call)
	return ""
}

func (s *SignerStub) KeyID() sign.KeyID {
	s.OnKeyID.SleepLatency()
	call := SignerKeyIDCall{}
	if s.OnKeyID.fn != nil {
		r0 := s.OnKeyID.fn()
		call.Result = r0
		s.OnKeyID.Record(call)
		return r0
	}
	if s.OnKeyID.fallback != nil {
		f := s.OnKeyID.fallback
		call.Result = f.Result
		s.OnKeyID.Record(call)
		return f.Result
	}
	s.OnKeyID.FailUnexpectedCall(call)
	s.OnKeyID.Record(call)
	return sign.KeyID{}
}

func (s *SignerStub) PublicKey() []byte {
	s.OnPublicKey.SleepLatency()
	call := SignerPublicKeyCall{}
	if s.OnPublicKey.fn != nil {
		r0 := s.OnPublicKey.fn()
		call.Result = r0
		s.OnPublicKey.Record(call)
		return r0
	}
	if s.OnPublicKey.fallback != nil {
		f := s.OnPublicKey.fallback
		call.Result = f.Result
		s.OnPublicKey.Record(call)
		return f.Result
	}
	s.OnPublicKey.FailUnexpectedCall(call)
	s.OnPublicKey.Record(call)
	return nil
}

func (s *SignerStub) Sign(message []byte) ([]byte, error) {
	s.OnSign.SleepLatency()
	call := SignerSignCall{Message: message}
	if fired, faultErr := s.OnSign.ShouldFaultFor(call); fired {
		call.Err = faultErr
		s.OnSign.Record(call)
		return nil, faultErr
	}
	if s.OnSign.fn != nil {
		r0, r1 := s.OnSign.fn(message)
		call.Result = r0
		call.Err = r1
		s.OnSign.Record(call)
		return r0, r1
	}
	if s.OnSign.fallback != nil {
		f := s.OnSign.fallback
		call.Result = f.Result
		call.Err = f.Err
		s.OnSign.Record(call)
		return f.Result, f.Err
	}
	s.OnSign.FailUnexpectedCall(call)
	s.OnSign.Record(call)
	return nil, nil
}

func (s *SignerStub) Verify(message []byte, signature []byte) bool {
	s.OnVerify.SleepLatency()
	call := SignerVerifyCall{Message: message, Signature: signature}
	if s.OnVerify.fn != nil {
		r0 := s.OnVerify.fn(message, signature)
		call.Result = r0
		s.OnVerify.Record(call)
		return r0
	}
	if s.OnVerify.fallback != nil {
		f := s.OnVerify.fallback
		call.Result = f.Result
		s.OnVerify.Record(call)
		return f.Result
	}
	s.OnVerify.FailUnexpectedCall(call)
	s.OnVerify.Record(call)
	return false
}
