// Code generated by testkit suite. DO NOT EDIT.
// Source: sign.go:100-243 (testkit suite SignStream)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto/sign"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertSignStreamContract runs conformance assertions against
// implementations of [sign.SignStream] produced by factory.
//
//	Default subtests: 3 across 2 methods
//	Shapes detected:  Unknown (SignAndReset, Write)
//	Directives:       none
//	Plug-in points:   SignStreamOnSignAndReset, SignStreamOnWrite, SignStreamOnAll, SignStreamCustom
func AssertSignStreamContract(
	t *testing.T,
	factory func() sign.SignStream,
	opts ...SignStreamOption,
) {
	t.Helper()
	cfg := newSignStreamConfig(opts...)

	runSignStreamSignAndReset(t, factory, &cfg)
	runSignStreamWrite(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[sign.SignStream]{
			T:             t,
			CrossBindings: bindings.CrossBindings[sign.SignStream]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runSignStreamSignAndReset(t *testing.T, factory func() sign.SignStream, cfg *signStreamConfig) {
	t.Helper()

	t.Run("SignAndReset/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: SignAndReset panicked on zero-value args (%v) — supply sample values via SignStreamOnSignAndReset", r)
			}
		}()
		s := factory()
		_, _ = s.SignAndReset()
	})
	if len(cfg.onSignAndReset) > 0 {
		t.Run("SignAndReset", func(t *testing.T) {
			for _, fn := range cfg.onSignAndReset {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runSignStreamWrite(t *testing.T, factory func() sign.SignStream, cfg *signStreamConfig) {
	t.Helper()

	t.Run("Write/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Write panicked on zero-value args (%v) — supply sample values via SignStreamOnWrite", r)
			}
		}()
		s := factory()
		_, _ = s.Write(nil)
	})

	t.Run("Write/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Write(nil)
		})
	})
	if len(cfg.onWrite) > 0 {
		t.Run("Write", func(t *testing.T) {
			for _, fn := range cfg.onWrite {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

// SignStreamOption configures [AssertSignStreamContract].
type SignStreamOption func(*signStreamConfig)

// SignStreamPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func SignStreamPrePopulate(fn func(ctx context.Context, s sign.SignStream)) SignStreamOption {
	return func(c *signStreamConfig) { c.prePopulate = fn }
}

// SignStreamCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func SignStreamCustom(name string, fn func(*testing.T, sign.SignStream)) SignStreamOption {
	return func(c *signStreamConfig) {
		c.custom = append(c.custom, signStreamCustomSubtest{name: name, fn: fn})
	}
}

// SignStreamOnSignAndReset adds plug-in assertions for the SignAndReset method.
func SignStreamOnSignAndReset(assertions ...func(*testing.T, sign.SignStream)) SignStreamOption {
	return func(c *signStreamConfig) {
		c.onSignAndReset = append(c.onSignAndReset, assertions...)
	}
}

// SignStreamOnWrite adds plug-in assertions for the Write method.
func SignStreamOnWrite(assertions ...func(*testing.T, sign.SignStream)) SignStreamOption {
	return func(c *signStreamConfig) {
		c.onWrite = append(c.onWrite, assertions...)
	}
}

// SignStreamOnAll adds cross-method assertions that span multiple methods.
func SignStreamOnAll(assertions ...suite.CrossMethodAssertion[sign.SignStream]) SignStreamOption {
	return func(c *signStreamConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type signStreamCustomSubtest struct {
	name string
	fn   func(*testing.T, sign.SignStream)
}

type signStreamConfig struct {
	prePopulate    func(context.Context, sign.SignStream)
	custom         []signStreamCustomSubtest
	onAll          []suite.CrossMethodAssertion[sign.SignStream]
	onSignAndReset []func(*testing.T, sign.SignStream)
	onWrite        []func(*testing.T, sign.SignStream)
}

func newSignStreamConfig(opts ...SignStreamOption) signStreamConfig {
	var cfg signStreamConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
