// Code generated by testkit stub. DO NOT EDIT.
// Source: sign.go:100-243 (testkit stub SignStream)

package cryptotest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestSignStreamStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("SignStream-stub-test")

	t.Run("SignAndReset default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		result, err := s.SignAndReset()
		testkit.Equal(t, result, nil, "SignAndReset must return zero")
		testkit.NoError(t, err, "SignAndReset must not error")
	})

	t.Run("SignAndReset fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnSignAndReset.Faults(errTest, 1)
		_, err := s.SignAndReset()
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("SignAndReset Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnSignAndReset.Func(func() ([]byte, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnSignAndReset.Faults(errTest, 1)
		_, err := s.SignAndReset()
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("SignAndReset counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnSignAndReset.Faults(errTest, 3)
		_, err1 := s.SignAndReset()
		_, err2 := s.SignAndReset()
		_, err3 := s.SignAndReset()
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("SignAndReset Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		called := false
		s.OnSignAndReset.Func(func() ([]byte, error) {
			called = true
			return []byte{42}, nil
		})
		result, err := s.SignAndReset()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, []byte{42}, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("SignAndReset Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnSignAndReset.Returns([]byte{42}, nil)
		result, err := s.SignAndReset()
		testkit.Equal(t, result, []byte{42}, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("SignAndReset records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		_, _ = s.SignAndReset()
		s.OnSignAndReset.AssertCalledOnce(t, "must record SignAndReset call")
	})

	t.Run("WithSignStreamSignAndReset constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewSignStreamStub(t, cryptotest.WithSignStreamSignAndReset(func() ([]byte, error) {
			called = true
			return nil, nil
		}))
		_, _ = s.SignAndReset()
		testkit.True(t, called, "WithSignStreamSignAndReset must be called")
	})

	t.Run("SignAndReset OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		var observed []cryptotest.SignStreamSignAndResetCall
		s.OnSignAndReset.OnRecord(func(c cryptotest.SignStreamSignAndResetCall) {
			observed = append(observed, c)
		})
		_, _ = s.SignAndReset()
		_, _ = s.SignAndReset()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every SignAndReset call")
	})

	t.Run("Write default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 0, "Write must return zero")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("Write fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Write Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnWrite.Func(func([]byte) (int, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Write counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnWrite.Faults(errTest, 3)
		_, err1 := s.Write(nil)
		_, err2 := s.Write(nil)
		_, err3 := s.Write(nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Write Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		called := false
		s.OnWrite.Func(func([]byte) (int, error) {
			called = true
			return 42, nil
		})
		n, err := s.Write(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, n, 42, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Write Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnWrite.Returns(42, nil)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Write records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		_, _ = s.Write(nil)
		s.OnWrite.AssertCalledOnce(t, "must record Write call")
	})

	t.Run("WithSignStreamWrite constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewSignStreamStub(t, cryptotest.WithSignStreamWrite(func([]byte) (int, error) {
			called = true
			return 0, nil
		}))
		_, _ = s.Write(nil)
		testkit.True(t, called, "WithSignStreamWrite must be called")
	})

	t.Run("Write records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		_, _ = s.Write([]byte{42})
		call := s.OnWrite.LastCall(t)
		testkit.Equal(t, call.P, []byte{42}, "P must be recorded")
	})

	t.Run("Write OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		var observed []cryptotest.SignStreamWriteCall
		s.OnWrite.OnRecord(func(c cryptotest.SignStreamWriteCall) {
			observed = append(observed, c)
		})
		_, _ = s.Write(nil)
		_, _ = s.Write(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Write call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubBenchMode())
		_, _ = s.SignAndReset()
		testkit.Equal(t, s.OnSignAndReset.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewSignStreamStub(f)
		s.OnSignAndReset.Times(2)
		_, _ = s.SignAndReset()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewSignStreamStub(f)
		s.OnSignAndReset.TimesAtLeast(3)
		_, _ = s.SignAndReset()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		_, _ = s.SignAndReset()
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnSignAndReset.AssertNotCalled(t, "SignAndReset must be cleared after ResetCalls")
		s.OnWrite.AssertNotCalled(t, "Write must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured SignAndReset", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewSignStreamStub(f, cryptotest.SignStreamStubStrict())
		_, _ = s.SignAndReset()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured SignAndReset")
	})

	t.Run("Strict mode fails on unconfigured Write", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewSignStreamStub(f, cryptotest.SignStreamStubStrict())
		_, _ = s.Write(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Write")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewSignStreamStub(t)
		inner.OnSignAndReset.Returns(nil, nil)
		inner.OnWrite.Returns(0, nil)
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubDelegateTo(inner))
		_, _ = s.SignAndReset()
		_, _ = s.Write(nil)
		s.OnSignAndReset.AssertCalledOnce(t, "SignAndReset must delegate")
		s.OnWrite.AssertCalledOnce(t, "Write must delegate")
	})

	t.Run("DelegateTo surfaces SignAndReset return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewSignStreamStub(t)
		inner.OnSignAndReset.Returns([]byte{42}, nil)
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubDelegateTo(inner))
		result, err := s.SignAndReset()
		testkit.Equal(t, result, []byte{42}, "SignAndReset must return configured value")
		testkit.NoError(t, err, "SignAndReset must not error")
	})

	t.Run("DelegateTo surfaces Write return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewSignStreamStub(t)
		inner.OnWrite.Returns(42, nil)
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubDelegateTo(inner))
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls preserves SignAndReset Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnSignAndReset.Returns([]byte{42}, nil)
		_, _ = s.SignAndReset()
		s.ResetCalls()
		s.OnSignAndReset.AssertNotCalled(t, "ResetCalls must clear recordings")
		result, err := s.SignAndReset()
		testkit.Equal(t, result, []byte{42}, "SignAndReset must return configured value")
		testkit.NoError(t, err, "SignAndReset must not error")
	})

	t.Run("ResetCalls preserves Write Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		s.OnWrite.Returns(42, nil)
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnWrite.AssertNotCalled(t, "ResetCalls must clear recordings")
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewSignStreamStub(t)
		_, _ = s.SignAndReset()
		testkit.Len(t, s.OnSignAndReset.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnSignAndReset.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("SignAndReset FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewSignStreamStub(t, cryptotest.SignStreamStubWithClock(clk))
		s.OnSignAndReset.FaultsFor(5*time.Second, errTest)

		_, err := s.SignAndReset()
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, err = s.SignAndReset()
		testkit.NoError(t, err, "SignAndReset must succeed after window expires")
	})
}

func TestSignStreamStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewSignStreamStub(nil, cryptotest.SignStreamStubBenchMode())
	s.OnSignAndReset.Returns(nil, nil)
	s.OnWrite.Returns(0, nil)

	t.Run("SignAndReset", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.SignAndReset()
		})
		testkit.Equal(t, int(avgAllocs), 0, "SignAndReset in BenchMode must be 0 alloc")
	})

	t.Run("Write", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Write(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Write in BenchMode must be 0 alloc")
	})

}
