// Code generated by testkit suite. DO NOT EDIT.
// Source: hasher.go:100-171 (testkit suite Stream)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertStreamContract runs conformance assertions against
// implementations of [crypto.Stream] produced by factory.
//
//	Default subtests: 5 across 4 methods
//	Shapes detected:  Pure (Sum), Unknown (Close, Reset, Write)
//	Directives:       none
//	Plug-in points:   StreamOnClose, StreamOnReset, StreamOnSum, StreamOnWrite, StreamOnAll, StreamCustom
func AssertStreamContract(
	t *testing.T,
	factory func() crypto.Stream,
	opts ...StreamOption,
) {
	t.Helper()
	cfg := newStreamConfig(opts...)

	runStreamClose(t, factory, &cfg)
	runStreamReset(t, factory, &cfg)
	runStreamSum(t, factory, &cfg)
	runStreamWrite(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[crypto.Stream]{
			T:             t,
			CrossBindings: bindings.CrossBindings[crypto.Stream]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runStreamClose(t *testing.T, factory func() crypto.Stream, cfg *streamConfig) {
	t.Helper()

	t.Run("Close/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Close panicked on zero-value args (%v) — supply sample values via StreamOnClose", r)
			}
		}()
		s := factory()
		s.Close()
	})
	if len(cfg.onClose) > 0 {
		t.Run("Close", func(t *testing.T) {
			for _, fn := range cfg.onClose {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runStreamReset(t *testing.T, factory func() crypto.Stream, cfg *streamConfig) {
	t.Helper()

	t.Run("Reset/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Reset panicked on zero-value args (%v) — supply sample values via StreamOnReset", r)
			}
		}()
		s := factory()
		s.Reset()
	})
	if len(cfg.onReset) > 0 {
		t.Run("Reset", func(t *testing.T) {
			for _, fn := range cfg.onReset {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runStreamSum(t *testing.T, factory func() crypto.Stream, cfg *streamConfig) {
	t.Helper()

	t.Run("Sum/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Sum panicked on zero-value args (%v) — supply sample values via StreamOnSum", r)
			}
		}()
		s := factory()
		_ = s.Sum()
	})
	if len(cfg.onSum) > 0 {
		t.Run("Sum", func(t *testing.T) {
			prePopFactory := func() crypto.Stream {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.Stream, crypto.Digest]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.Stream, crypto.Digest]{
					Factory: prePopFactory,
					Call: func(impl crypto.Stream) crypto.Digest {
						return impl.Sum()
					},
				},
			}
			for _, a := range cfg.onSum {
				a(pctx)
			}
		})
	}
}

func runStreamWrite(t *testing.T, factory func() crypto.Stream, cfg *streamConfig) {
	t.Helper()

	t.Run("Write/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Write panicked on zero-value args (%v) — supply sample values via StreamOnWrite", r)
			}
		}()
		s := factory()
		_, _ = s.Write(nil)
	})

	t.Run("Write/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Write(nil)
		})
	})
	if len(cfg.onWrite) > 0 {
		t.Run("Write", func(t *testing.T) {
			for _, fn := range cfg.onWrite {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

// StreamOption configures [AssertStreamContract].
type StreamOption func(*streamConfig)

// StreamPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func StreamPrePopulate(fn func(ctx context.Context, s crypto.Stream)) StreamOption {
	return func(c *streamConfig) { c.prePopulate = fn }
}

// StreamCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func StreamCustom(name string, fn func(*testing.T, crypto.Stream)) StreamOption {
	return func(c *streamConfig) {
		c.custom = append(c.custom, streamCustomSubtest{name: name, fn: fn})
	}
}

// StreamOnClose adds plug-in assertions for the Close method.
func StreamOnClose(assertions ...func(*testing.T, crypto.Stream)) StreamOption {
	return func(c *streamConfig) {
		c.onClose = append(c.onClose, assertions...)
	}
}

// StreamOnReset adds plug-in assertions for the Reset method.
func StreamOnReset(assertions ...func(*testing.T, crypto.Stream)) StreamOption {
	return func(c *streamConfig) {
		c.onReset = append(c.onReset, assertions...)
	}
}

// StreamOnSum adds plug-in assertions for the Sum method.
func StreamOnSum(assertions ...suite.PureAssertion[crypto.Stream, crypto.Digest]) StreamOption {
	return func(c *streamConfig) {
		c.onSum = append(c.onSum, assertions...)
	}
}

// StreamOnWrite adds plug-in assertions for the Write method.
func StreamOnWrite(assertions ...func(*testing.T, crypto.Stream)) StreamOption {
	return func(c *streamConfig) {
		c.onWrite = append(c.onWrite, assertions...)
	}
}

// StreamOnAll adds cross-method assertions that span multiple methods.
func StreamOnAll(assertions ...suite.CrossMethodAssertion[crypto.Stream]) StreamOption {
	return func(c *streamConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type streamCustomSubtest struct {
	name string
	fn   func(*testing.T, crypto.Stream)
}

type streamConfig struct {
	prePopulate func(context.Context, crypto.Stream)
	custom      []streamCustomSubtest
	onAll       []suite.CrossMethodAssertion[crypto.Stream]
	onClose     []func(*testing.T, crypto.Stream)
	onReset     []func(*testing.T, crypto.Stream)
	onSum       []suite.PureAssertion[crypto.Stream, crypto.Digest]
	onWrite     []func(*testing.T, crypto.Stream)
}

func newStreamConfig(opts ...StreamOption) streamConfig {
	var cfg streamConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
