// Code generated by testkit suite. DO NOT EDIT.
// Source: sign.go:100-287 (testkit suite VerifyStream)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto/sign"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertVerifyStreamContract runs conformance assertions against
// implementations of [sign.VerifyStream] produced by factory.
//
//	Default subtests: 4 across 2 methods
//	Shapes detected:  Predicate (Verify), Unknown (Write)
//	Directives:       none
//	Plug-in points:   VerifyStreamOnVerify, VerifyStreamOnWrite, VerifyStreamOnAll, VerifyStreamCustom
func AssertVerifyStreamContract(
	t *testing.T,
	factory func() sign.VerifyStream,
	opts ...VerifyStreamOption,
) {
	t.Helper()
	cfg := newVerifyStreamConfig(opts...)

	runVerifyStreamVerify(t, factory, &cfg)
	runVerifyStreamWrite(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[sign.VerifyStream]{
			T:             t,
			CrossBindings: bindings.CrossBindings[sign.VerifyStream]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runVerifyStreamVerify(t *testing.T, factory func() sign.VerifyStream, cfg *verifyStreamConfig) {
	t.Helper()

	t.Run("Verify/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Verify panicked on zero-value args (%v) — supply sample values via VerifyStreamOnVerify", r)
			}
		}()
		s := factory()
		_ = s.Verify(nil)
	})

	t.Run("Verify/nil sig", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().Verify(nil)
		})
	})
	if len(cfg.onVerify) > 0 {
		t.Run("Verify", func(t *testing.T) {
			prePopFactory := func() sign.VerifyStream {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PredicateContext[sign.VerifyStream]{
				T: t,
				PredicateBindings: bindings.PredicateBindings[sign.VerifyStream]{
					Factory: prePopFactory,
					Call: func(impl sign.VerifyStream) bool {
						return impl.Verify(nil)
					},
				},
			}
			for _, a := range cfg.onVerify {
				a(pctx)
			}
		})
	}
}

func runVerifyStreamWrite(t *testing.T, factory func() sign.VerifyStream, cfg *verifyStreamConfig) {
	t.Helper()

	t.Run("Write/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Write panicked on zero-value args (%v) — supply sample values via VerifyStreamOnWrite", r)
			}
		}()
		s := factory()
		_, _ = s.Write(nil)
	})

	t.Run("Write/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Write(nil)
		})
	})
	if len(cfg.onWrite) > 0 {
		t.Run("Write", func(t *testing.T) {
			for _, fn := range cfg.onWrite {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

// VerifyStreamOption configures [AssertVerifyStreamContract].
type VerifyStreamOption func(*verifyStreamConfig)

// VerifyStreamPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func VerifyStreamPrePopulate(fn func(ctx context.Context, s sign.VerifyStream)) VerifyStreamOption {
	return func(c *verifyStreamConfig) { c.prePopulate = fn }
}

// VerifyStreamCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func VerifyStreamCustom(name string, fn func(*testing.T, sign.VerifyStream)) VerifyStreamOption {
	return func(c *verifyStreamConfig) {
		c.custom = append(c.custom, verifyStreamCustomSubtest{name: name, fn: fn})
	}
}

// VerifyStreamOnVerify adds plug-in assertions for the Verify method.
func VerifyStreamOnVerify(assertions ...suite.PredicateAssertion[sign.VerifyStream]) VerifyStreamOption {
	return func(c *verifyStreamConfig) {
		c.onVerify = append(c.onVerify, assertions...)
	}
}

// VerifyStreamOnWrite adds plug-in assertions for the Write method.
func VerifyStreamOnWrite(assertions ...func(*testing.T, sign.VerifyStream)) VerifyStreamOption {
	return func(c *verifyStreamConfig) {
		c.onWrite = append(c.onWrite, assertions...)
	}
}

// VerifyStreamOnAll adds cross-method assertions that span multiple methods.
func VerifyStreamOnAll(assertions ...suite.CrossMethodAssertion[sign.VerifyStream]) VerifyStreamOption {
	return func(c *verifyStreamConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type verifyStreamCustomSubtest struct {
	name string
	fn   func(*testing.T, sign.VerifyStream)
}

type verifyStreamConfig struct {
	prePopulate func(context.Context, sign.VerifyStream)
	custom      []verifyStreamCustomSubtest
	onAll       []suite.CrossMethodAssertion[sign.VerifyStream]
	onVerify    []suite.PredicateAssertion[sign.VerifyStream]
	onWrite     []func(*testing.T, sign.VerifyStream)
}

func newVerifyStreamConfig(opts ...VerifyStreamOption) verifyStreamConfig {
	var cfg verifyStreamConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
