// Code generated by testkit stub. DO NOT EDIT.
// Source: sign.go:93-115 (testkit stub Verifier)

package cryptotest

import (
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/core/crypto/sign"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ sign.Verifier = (*VerifierStub)(nil)

// --- Call types ---

// VerifierAlgorithmCall records one invocation of sign.Verifier.Algorithm.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type VerifierAlgorithmCall struct {
	Result crypto.Algorithm
}

// VerifierKeyIDCall records one invocation of sign.Verifier.KeyID.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type VerifierKeyIDCall struct {
	Result sign.KeyID
}

// VerifierPublicKeyCall records one invocation of sign.Verifier.PublicKey.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type VerifierPublicKeyCall struct {
	Result []byte
}

// VerifierVerifyCall records one invocation of sign.Verifier.Verify.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type VerifierVerifyCall struct {
	Message   []byte
	Signature []byte
	Result    bool
}

// --- Per-method stubs ---

// VerifierAlgorithmStub controls behavior and records calls for Algorithm.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type VerifierAlgorithmStub struct {
	*stub.MethodStub[VerifierAlgorithmCall]
	fn       func() crypto.Algorithm
	fallback *verifierAlgorithmReturn
}

type verifierAlgorithmReturn struct {
	Result crypto.Algorithm
}

// Returns sets a fixed return value for Algorithm.
func (s *VerifierAlgorithmStub) Returns(result crypto.Algorithm) *VerifierAlgorithmStub {
	s.fallback = &verifierAlgorithmReturn{Result: result}
	return s
}

// Func sets a function override for Algorithm.
func (s *VerifierAlgorithmStub) Func(fn func() crypto.Algorithm) *VerifierAlgorithmStub {
	s.fn = fn
	return s
}

// VerifierKeyIDStub controls behavior and records calls for KeyID.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type VerifierKeyIDStub struct {
	*stub.MethodStub[VerifierKeyIDCall]
	fn       func() sign.KeyID
	fallback *verifierKeyIDReturn
}

type verifierKeyIDReturn struct {
	Result sign.KeyID
}

// Returns sets a fixed return value for KeyID.
func (s *VerifierKeyIDStub) Returns(result sign.KeyID) *VerifierKeyIDStub {
	s.fallback = &verifierKeyIDReturn{Result: result}
	return s
}

// Func sets a function override for KeyID.
func (s *VerifierKeyIDStub) Func(fn func() sign.KeyID) *VerifierKeyIDStub {
	s.fn = fn
	return s
}

// VerifierPublicKeyStub controls behavior and records calls for PublicKey.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type VerifierPublicKeyStub struct {
	*stub.MethodStub[VerifierPublicKeyCall]
	fn       func() []byte
	fallback *verifierPublicKeyReturn
}

type verifierPublicKeyReturn struct {
	Result []byte
}

// Returns sets a fixed return value for PublicKey.
func (s *VerifierPublicKeyStub) Returns(result []byte) *VerifierPublicKeyStub {
	s.fallback = &verifierPublicKeyReturn{Result: result}
	return s
}

// Func sets a function override for PublicKey.
func (s *VerifierPublicKeyStub) Func(fn func() []byte) *VerifierPublicKeyStub {
	s.fn = fn
	return s
}

// VerifierVerifyStub controls behavior and records calls for Verify.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type VerifierVerifyStub struct {
	*stub.MethodStub[VerifierVerifyCall]
	fn       func([]byte, []byte) bool
	fallback *verifierVerifyReturn
}

type verifierVerifyReturn struct {
	Result bool
}

// Returns sets a fixed return value for Verify.
func (s *VerifierVerifyStub) Returns(result bool) *VerifierVerifyStub {
	s.fallback = &verifierVerifyReturn{Result: result}
	return s
}

// Func sets a function override for Verify.
func (s *VerifierVerifyStub) Func(fn func([]byte, []byte) bool) *VerifierVerifyStub {
	s.fn = fn
	return s
}

// --- VerifierStub ---

// VerifierStubOption configures a [VerifierStub] at construction time.
type VerifierStubOption func(*VerifierStub)

// VerifierStubStrict enables strict mode — unconfigured methods fail the test.
func VerifierStubStrict() VerifierStubOption {
	return func(s *VerifierStub) { s.strict = true }
}

// VerifierStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func VerifierStubDelegateTo(impl sign.Verifier) VerifierStubOption {
	return func(s *VerifierStub) {
		s.OnAlgorithm.Func(impl.Algorithm)
		s.OnKeyID.Func(impl.KeyID)
		s.OnPublicKey.Func(impl.PublicKey)
		s.OnVerify.Func(impl.Verify)
	}
}

// VerifierStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func VerifierStubWithClock(clk clock.Clock) VerifierStubOption {
	return func(s *VerifierStub) {
		s.OnAlgorithm.WithClock(clk)
		s.OnKeyID.WithClock(clk)
		s.OnPublicKey.WithClock(clk)
		s.OnVerify.WithClock(clk)
	}
}

// VerifierStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func VerifierStubWithRandSource(src rand.Source) VerifierStubOption {
	return func(s *VerifierStub) {
		s.OnAlgorithm.WithRandSource(src)
		s.OnKeyID.WithRandSource(src)
		s.OnPublicKey.WithRandSource(src)
		s.OnVerify.WithRandSource(src)
	}
}

// VerifierStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func VerifierStubBenchMode() VerifierStubOption {
	return func(s *VerifierStub) {
		s.OnAlgorithm.BenchMode()
		s.OnKeyID.BenchMode()
		s.OnPublicKey.BenchMode()
		s.OnVerify.BenchMode()
	}
}

// WithVerifierAlgorithm sets a function override at construction time.
func WithVerifierAlgorithm(fn func() crypto.Algorithm) VerifierStubOption {
	return func(s *VerifierStub) { s.OnAlgorithm.Func(fn) }
}

// WithVerifierKeyID sets a function override at construction time.
func WithVerifierKeyID(fn func() sign.KeyID) VerifierStubOption {
	return func(s *VerifierStub) { s.OnKeyID.Func(fn) }
}

// WithVerifierPublicKey sets a function override at construction time.
func WithVerifierPublicKey(fn func() []byte) VerifierStubOption {
	return func(s *VerifierStub) { s.OnPublicKey.Func(fn) }
}

// WithVerifierVerify sets a function override at construction time.
func WithVerifierVerify(fn func([]byte, []byte) bool) VerifierStubOption {
	return func(s *VerifierStub) { s.OnVerify.Func(fn) }
}

// VerifierStub is a configurable test double for [sign.Verifier].
type VerifierStub struct {
	OnAlgorithm *VerifierAlgorithmStub
	OnKeyID     *VerifierKeyIDStub
	OnPublicKey *VerifierPublicKeyStub
	OnVerify    *VerifierVerifyStub
	strict      bool
}

// NewVerifierStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewVerifierStub(tb testing.TB, opts ...VerifierStubOption) *VerifierStub {
	s := &VerifierStub{
		OnAlgorithm: &VerifierAlgorithmStub{MethodStub: stub.NewMethodStub[VerifierAlgorithmCall](tb, "Verifier.Algorithm")},
		OnKeyID:     &VerifierKeyIDStub{MethodStub: stub.NewMethodStub[VerifierKeyIDCall](tb, "Verifier.KeyID")},
		OnPublicKey: &VerifierPublicKeyStub{MethodStub: stub.NewMethodStub[VerifierPublicKeyCall](tb, "Verifier.PublicKey")},
		OnVerify:    &VerifierVerifyStub{MethodStub: stub.NewMethodStub[VerifierVerifyCall](tb, "Verifier.Verify")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnAlgorithm.Strict()
		s.OnKeyID.Strict()
		s.OnPublicKey.Strict()
		s.OnVerify.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnAlgorithm.Verify()
				s.OnKeyID.Verify()
				s.OnPublicKey.Verify()
				s.OnVerify.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *VerifierStub) ResetCalls() {
	s.OnAlgorithm.Reset()
	s.OnKeyID.Reset()
	s.OnPublicKey.Reset()
	s.OnVerify.Reset()
}

// --- Interface method implementations ---

func (s *VerifierStub) Algorithm() crypto.Algorithm {
	s.OnAlgorithm.SleepLatency()
	call := VerifierAlgorithmCall{}
	if s.OnAlgorithm.fn != nil {
		r0 := s.OnAlgorithm.fn()
		call.Result = r0
		s.OnAlgorithm.Record(call)
		return r0
	}
	if s.OnAlgorithm.fallback != nil {
		f := s.OnAlgorithm.fallback
		call.Result = f.Result
		s.OnAlgorithm.Record(call)
		return f.Result
	}
	s.OnAlgorithm.FailUnexpectedCall(call)
	s.OnAlgorithm.Record(call)
	return ""
}

func (s *VerifierStub) KeyID() sign.KeyID {
	s.OnKeyID.SleepLatency()
	call := VerifierKeyIDCall{}
	if s.OnKeyID.fn != nil {
		r0 := s.OnKeyID.fn()
		call.Result = r0
		s.OnKeyID.Record(call)
		return r0
	}
	if s.OnKeyID.fallback != nil {
		f := s.OnKeyID.fallback
		call.Result = f.Result
		s.OnKeyID.Record(call)
		return f.Result
	}
	s.OnKeyID.FailUnexpectedCall(call)
	s.OnKeyID.Record(call)
	return sign.KeyID{}
}

func (s *VerifierStub) PublicKey() []byte {
	s.OnPublicKey.SleepLatency()
	call := VerifierPublicKeyCall{}
	if s.OnPublicKey.fn != nil {
		r0 := s.OnPublicKey.fn()
		call.Result = r0
		s.OnPublicKey.Record(call)
		return r0
	}
	if s.OnPublicKey.fallback != nil {
		f := s.OnPublicKey.fallback
		call.Result = f.Result
		s.OnPublicKey.Record(call)
		return f.Result
	}
	s.OnPublicKey.FailUnexpectedCall(call)
	s.OnPublicKey.Record(call)
	return nil
}

func (s *VerifierStub) Verify(message []byte, signature []byte) bool {
	s.OnVerify.SleepLatency()
	call := VerifierVerifyCall{Message: message, Signature: signature}
	if s.OnVerify.fn != nil {
		r0 := s.OnVerify.fn(message, signature)
		call.Result = r0
		s.OnVerify.Record(call)
		return r0
	}
	if s.OnVerify.fallback != nil {
		f := s.OnVerify.fallback
		call.Result = f.Result
		s.OnVerify.Record(call)
		return f.Result
	}
	s.OnVerify.FailUnexpectedCall(call)
	s.OnVerify.Record(call)
	return false
}
