// Code generated by testkit stub. DO NOT EDIT.
// Source: sign.go:100-287 (testkit stub VerifyStream)

package cryptotest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestVerifyStreamStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("VerifyStream-stub-test")

	t.Run("Verify default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		result := s.Verify(nil)
		testkit.Equal(t, result, false, "Verify must return zero")
	})

	t.Run("Verify Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		called := false
		s.OnVerify.Func(func([]byte) bool {
			called = true
			return true
		})
		result := s.Verify(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, true, "Func must return set value")
	})

	t.Run("Verify Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnVerify.Returns(true)
		result := s.Verify(nil)
		testkit.Equal(t, result, true, "Returns must return set value")
	})

	t.Run("Verify records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_ = s.Verify(nil)
		s.OnVerify.AssertCalledOnce(t, "must record Verify call")
	})

	t.Run("WithVerifyStreamVerify constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.WithVerifyStreamVerify(func([]byte) bool {
			called = true
			return false
		}))
		_ = s.Verify(nil)
		testkit.True(t, called, "WithVerifyStreamVerify must be called")
	})

	t.Run("Verify records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_ = s.Verify([]byte{42})
		call := s.OnVerify.LastCall(t)
		testkit.Equal(t, call.Sig, []byte{42}, "Sig must be recorded")
	})

	t.Run("Verify OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		var observed []cryptotest.VerifyStreamVerifyCall
		s.OnVerify.OnRecord(func(c cryptotest.VerifyStreamVerifyCall) {
			observed = append(observed, c)
		})
		_ = s.Verify(nil)
		_ = s.Verify(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Verify call")
	})

	t.Run("Write default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 0, "Write must return zero")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("Write fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Write Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnWrite.Func(func([]byte) (int, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Write counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnWrite.Faults(errTest, 3)
		_, err1 := s.Write(nil)
		_, err2 := s.Write(nil)
		_, err3 := s.Write(nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Write Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		called := false
		s.OnWrite.Func(func([]byte) (int, error) {
			called = true
			return 42, nil
		})
		n, err := s.Write(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, n, 42, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Write Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnWrite.Returns(42, nil)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Write records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_, _ = s.Write(nil)
		s.OnWrite.AssertCalledOnce(t, "must record Write call")
	})

	t.Run("WithVerifyStreamWrite constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.WithVerifyStreamWrite(func([]byte) (int, error) {
			called = true
			return 0, nil
		}))
		_, _ = s.Write(nil)
		testkit.True(t, called, "WithVerifyStreamWrite must be called")
	})

	t.Run("Write records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_, _ = s.Write([]byte{42})
		call := s.OnWrite.LastCall(t)
		testkit.Equal(t, call.P, []byte{42}, "P must be recorded")
	})

	t.Run("Write OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		var observed []cryptotest.VerifyStreamWriteCall
		s.OnWrite.OnRecord(func(c cryptotest.VerifyStreamWriteCall) {
			observed = append(observed, c)
		})
		_, _ = s.Write(nil)
		_, _ = s.Write(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Write call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubBenchMode())
		_ = s.Verify(nil)
		testkit.Equal(t, s.OnVerify.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewVerifyStreamStub(f)
		s.OnVerify.Times(2)
		_ = s.Verify(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewVerifyStreamStub(f)
		s.OnVerify.TimesAtLeast(3)
		_ = s.Verify(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_ = s.Verify(nil)
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnVerify.AssertNotCalled(t, "Verify must be cleared after ResetCalls")
		s.OnWrite.AssertNotCalled(t, "Write must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Verify", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewVerifyStreamStub(f, cryptotest.VerifyStreamStubStrict())
		_ = s.Verify(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Verify")
	})

	t.Run("Strict mode fails on unconfigured Write", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewVerifyStreamStub(f, cryptotest.VerifyStreamStubStrict())
		_, _ = s.Write(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Write")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewVerifyStreamStub(t)
		inner.OnVerify.Returns(false)
		inner.OnWrite.Returns(0, nil)
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubDelegateTo(inner))
		_ = s.Verify(nil)
		_, _ = s.Write(nil)
		s.OnVerify.AssertCalledOnce(t, "Verify must delegate")
		s.OnWrite.AssertCalledOnce(t, "Write must delegate")
	})

	t.Run("DelegateTo surfaces Verify return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewVerifyStreamStub(t)
		inner.OnVerify.Returns(true)
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubDelegateTo(inner))
		result := s.Verify(nil)
		testkit.Equal(t, result, true, "Verify must return configured value")
	})

	t.Run("DelegateTo surfaces Write return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewVerifyStreamStub(t)
		inner.OnWrite.Returns(42, nil)
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubDelegateTo(inner))
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls preserves Verify Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnVerify.Returns(true)
		_ = s.Verify(nil)
		s.ResetCalls()
		s.OnVerify.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Verify(nil)
		testkit.Equal(t, result, true, "Verify must return configured value")
	})

	t.Run("ResetCalls preserves Write Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		s.OnWrite.Returns(42, nil)
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnWrite.AssertNotCalled(t, "ResetCalls must clear recordings")
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewVerifyStreamStub(t)
		_ = s.Verify(nil)
		testkit.Len(t, s.OnVerify.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnVerify.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("Write FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewVerifyStreamStub(t, cryptotest.VerifyStreamStubWithClock(clk))
		s.OnWrite.FaultsFor(5*time.Second, errTest)

		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, err = s.Write(nil)
		testkit.NoError(t, err, "Write must succeed after window expires")
	})
}

func TestVerifyStreamStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewVerifyStreamStub(nil, cryptotest.VerifyStreamStubBenchMode())
	s.OnVerify.Returns(false)
	s.OnWrite.Returns(0, nil)

	t.Run("Verify", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Verify(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Verify in BenchMode must be 0 alloc")
	})

	t.Run("Write", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Write(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Write in BenchMode must be 0 alloc")
	})

}
