// Code generated by testkit stub. DO NOT EDIT.
// Source: xof.go:32-41 (testkit stub XOF)

package cryptotest_test

import (
	"testing"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestXOFStub(t *testing.T) {
	t.Parallel()

	t.Run("Algorithm default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		result := s.Algorithm()
		testkit.Equal(t, result, "", "Algorithm must return zero")
	})

	t.Run("Algorithm Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		called := false
		s.OnAlgorithm.Func(func() crypto.Algorithm {
			called = true
			return crypto.Algorithm("test-result")
		})
		result := s.Algorithm()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Func must return set value")
	})

	t.Run("Algorithm Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Returns must return set value")
	})

	t.Run("Algorithm records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		_ = s.Algorithm()
		s.OnAlgorithm.AssertCalledOnce(t, "must record Algorithm call")
	})

	t.Run("WithXOFAlgorithm constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStub(t, cryptotest.WithXOFAlgorithm(func() crypto.Algorithm {
			called = true
			return ""
		}))
		_ = s.Algorithm()
		testkit.True(t, called, "WithXOFAlgorithm must be called")
	})

	t.Run("Algorithm OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		var observed []cryptotest.XOFAlgorithmCall
		s.OnAlgorithm.OnRecord(func(c cryptotest.XOFAlgorithmCall) {
			observed = append(observed, c)
		})
		_ = s.Algorithm()
		_ = s.Algorithm()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Algorithm call")
	})

	t.Run("ID default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		result := s.ID()
		testkit.Equal(t, result, crypto.ID{}, "ID must return zero")
	})

	t.Run("ID Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		called := false
		s.OnID.Func(func() crypto.ID {
			called = true
			return [16]byte{1}
		})
		result := s.ID()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, [16]byte{1}, "Func must return set value")
	})

	t.Run("ID Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnID.Returns([16]byte{1})
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "Returns must return set value")
	})

	t.Run("ID records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		_ = s.ID()
		s.OnID.AssertCalledOnce(t, "must record ID call")
	})

	t.Run("WithXOFID constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStub(t, cryptotest.WithXOFID(func() crypto.ID {
			called = true
			return crypto.ID{}
		}))
		_ = s.ID()
		testkit.True(t, called, "WithXOFID must be called")
	})

	t.Run("ID OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		var observed []cryptotest.XOFIDCall
		s.OnID.OnRecord(func(c cryptotest.XOFIDCall) {
			observed = append(observed, c)
		})
		_ = s.ID()
		_ = s.ID()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every ID call")
	})

	t.Run("NewXOFStream default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		result := s.NewXOFStream()
		testkit.Equal(t, result, nil, "NewXOFStream must return zero")
	})

	t.Run("NewXOFStream Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		called := false
		s.OnNewXOFStream.Func(func() crypto.XOFStream {
			called = true
			return nil
		})
		result := s.NewXOFStream()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("NewXOFStream Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnNewXOFStream.Returns(nil)
		result := s.NewXOFStream()
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("NewXOFStream records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		_ = s.NewXOFStream()
		s.OnNewXOFStream.AssertCalledOnce(t, "must record NewXOFStream call")
	})

	t.Run("WithXOFNewXOFStream constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStub(t, cryptotest.WithXOFNewXOFStream(func() crypto.XOFStream {
			called = true
			return nil
		}))
		_ = s.NewXOFStream()
		testkit.True(t, called, "WithXOFNewXOFStream must be called")
	})

	t.Run("NewXOFStream OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		var observed []cryptotest.XOFNewXOFStreamCall
		s.OnNewXOFStream.OnRecord(func(c cryptotest.XOFNewXOFStreamCall) {
			observed = append(observed, c)
		})
		_ = s.NewXOFStream()
		_ = s.NewXOFStream()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every NewXOFStream call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubBenchMode())
		_ = s.Algorithm()
		testkit.Equal(t, s.OnAlgorithm.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStub(f)
		s.OnAlgorithm.Times(2)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStub(f)
		s.OnAlgorithm.TimesAtLeast(3)
		_ = s.Algorithm()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		_ = s.Algorithm()
		_ = s.ID()
		_ = s.NewXOFStream()
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "Algorithm must be cleared after ResetCalls")
		s.OnID.AssertNotCalled(t, "ID must be cleared after ResetCalls")
		s.OnNewXOFStream.AssertNotCalled(t, "NewXOFStream must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Algorithm", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStub(f, cryptotest.XOFStubStrict())
		_ = s.Algorithm()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Algorithm")
	})

	t.Run("Strict mode fails on unconfigured ID", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStub(f, cryptotest.XOFStubStrict())
		_ = s.ID()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured ID")
	})

	t.Run("Strict mode fails on unconfigured NewXOFStream", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStub(f, cryptotest.XOFStubStrict())
		_ = s.NewXOFStream()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured NewXOFStream")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStub(t)
		inner.OnAlgorithm.Returns("")
		inner.OnID.Returns(crypto.ID{})
		inner.OnNewXOFStream.Returns(nil)
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubDelegateTo(inner))
		_ = s.Algorithm()
		_ = s.ID()
		_ = s.NewXOFStream()
		s.OnAlgorithm.AssertCalledOnce(t, "Algorithm must delegate")
		s.OnID.AssertCalledOnce(t, "ID must delegate")
		s.OnNewXOFStream.AssertCalledOnce(t, "NewXOFStream must delegate")
	})

	t.Run("DelegateTo surfaces Algorithm return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStub(t)
		inner.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubDelegateTo(inner))
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("DelegateTo surfaces ID return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStub(t)
		inner.OnID.Returns([16]byte{1})
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubDelegateTo(inner))
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("DelegateTo surfaces NewXOFStream return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStub(t)
		inner.OnNewXOFStream.Returns(nil)
		s := cryptotest.NewXOFStub(t, cryptotest.XOFStubDelegateTo(inner))
		result := s.NewXOFStream()
		testkit.Equal(t, result, nil, "NewXOFStream must return configured value")
	})

	t.Run("ResetCalls preserves Algorithm Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnAlgorithm.Returns(crypto.Algorithm("test-result"))
		_ = s.Algorithm()
		s.ResetCalls()
		s.OnAlgorithm.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Algorithm()
		testkit.Equal(t, result, crypto.Algorithm("test-result"), "Algorithm must return configured value")
	})

	t.Run("ResetCalls preserves ID Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnID.Returns([16]byte{1})
		_ = s.ID()
		s.ResetCalls()
		s.OnID.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.ID()
		testkit.Equal(t, result, [16]byte{1}, "ID must return configured value")
	})

	t.Run("ResetCalls preserves NewXOFStream Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		s.OnNewXOFStream.Returns(nil)
		_ = s.NewXOFStream()
		s.ResetCalls()
		s.OnNewXOFStream.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.NewXOFStream()
		testkit.Equal(t, result, nil, "NewXOFStream must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStub(t)
		_ = s.Algorithm()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnAlgorithm.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestXOFStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewXOFStub(nil, cryptotest.XOFStubBenchMode())
	s.OnAlgorithm.Returns("")
	s.OnID.Returns(crypto.ID{})
	s.OnNewXOFStream.Returns(nil)

	t.Run("Algorithm", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Algorithm()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Algorithm in BenchMode must be 0 alloc")
	})

	t.Run("ID", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.ID()
		})
		testkit.Equal(t, int(avgAllocs), 0, "ID in BenchMode must be 0 alloc")
	})

	t.Run("NewXOFStream", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.NewXOFStream()
		})
		testkit.Equal(t, int(avgAllocs), 0, "NewXOFStream in BenchMode must be 0 alloc")
	})

}
