// Code generated by testkit suite. DO NOT EDIT.
// Source: xof.go:32-41 (testkit suite XOF)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertXOFContract runs conformance assertions against
// implementations of [crypto.XOF] produced by factory.
//
//	Default subtests: 3 across 3 methods
//	Shapes detected:  Pure (Algorithm, ID, NewXOFStream)
//	Directives:       none
//	Plug-in points:   XOFOnAlgorithm, XOFOnID, XOFOnNewXOFStream, XOFOnAll, XOFCustom
func AssertXOFContract(
	t *testing.T,
	factory func() crypto.XOF,
	opts ...XOFOption,
) {
	t.Helper()
	cfg := newXOFConfig(opts...)

	runXOFAlgorithm(t, factory, &cfg)
	runXOFID(t, factory, &cfg)
	runXOFNewXOFStream(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[crypto.XOF]{
			T:             t,
			CrossBindings: bindings.CrossBindings[crypto.XOF]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runXOFAlgorithm(t *testing.T, factory func() crypto.XOF, cfg *xOFConfig) {
	t.Helper()

	t.Run("Algorithm/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Algorithm panicked on zero-value args (%v) — supply sample values via XOFOnAlgorithm", r)
			}
		}()
		s := factory()
		_ = s.Algorithm()
	})
	if len(cfg.onAlgorithm) > 0 {
		t.Run("Algorithm", func(t *testing.T) {
			prePopFactory := func() crypto.XOF {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.XOF, crypto.Algorithm]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.XOF, crypto.Algorithm]{
					Factory: prePopFactory,
					Call: func(impl crypto.XOF) crypto.Algorithm {
						return impl.Algorithm()
					},
				},
			}
			for _, a := range cfg.onAlgorithm {
				a(pctx)
			}
		})
	}
}

func runXOFID(t *testing.T, factory func() crypto.XOF, cfg *xOFConfig) {
	t.Helper()

	t.Run("ID/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: ID panicked on zero-value args (%v) — supply sample values via XOFOnID", r)
			}
		}()
		s := factory()
		_ = s.ID()
	})
	if len(cfg.onID) > 0 {
		t.Run("ID", func(t *testing.T) {
			prePopFactory := func() crypto.XOF {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.XOF, crypto.ID]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.XOF, crypto.ID]{
					Factory: prePopFactory,
					Call: func(impl crypto.XOF) crypto.ID {
						return impl.ID()
					},
				},
			}
			for _, a := range cfg.onID {
				a(pctx)
			}
		})
	}
}

func runXOFNewXOFStream(t *testing.T, factory func() crypto.XOF, cfg *xOFConfig) {
	t.Helper()

	t.Run("NewXOFStream/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: NewXOFStream panicked on zero-value args (%v) — supply sample values via XOFOnNewXOFStream", r)
			}
		}()
		s := factory()
		_ = s.NewXOFStream()
	})
	if len(cfg.onNewXOFStream) > 0 {
		t.Run("NewXOFStream", func(t *testing.T) {
			prePopFactory := func() crypto.XOF {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[crypto.XOF, crypto.XOFStream]{
				T: t,
				PureBindings: bindings.PureBindings[crypto.XOF, crypto.XOFStream]{
					Factory: prePopFactory,
					Call: func(impl crypto.XOF) crypto.XOFStream {
						return impl.NewXOFStream()
					},
				},
			}
			for _, a := range cfg.onNewXOFStream {
				a(pctx)
			}
		})
	}
}

// XOFOption configures [AssertXOFContract].
type XOFOption func(*xOFConfig)

// XOFPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func XOFPrePopulate(fn func(ctx context.Context, s crypto.XOF)) XOFOption {
	return func(c *xOFConfig) { c.prePopulate = fn }
}

// XOFCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func XOFCustom(name string, fn func(*testing.T, crypto.XOF)) XOFOption {
	return func(c *xOFConfig) {
		c.custom = append(c.custom, xOFCustomSubtest{name: name, fn: fn})
	}
}

// XOFOnAlgorithm adds plug-in assertions for the Algorithm method.
func XOFOnAlgorithm(assertions ...suite.PureAssertion[crypto.XOF, crypto.Algorithm]) XOFOption {
	return func(c *xOFConfig) {
		c.onAlgorithm = append(c.onAlgorithm, assertions...)
	}
}

// XOFOnID adds plug-in assertions for the ID method.
func XOFOnID(assertions ...suite.PureAssertion[crypto.XOF, crypto.ID]) XOFOption {
	return func(c *xOFConfig) {
		c.onID = append(c.onID, assertions...)
	}
}

// XOFOnNewXOFStream adds plug-in assertions for the NewXOFStream method.
func XOFOnNewXOFStream(assertions ...suite.PureAssertion[crypto.XOF, crypto.XOFStream]) XOFOption {
	return func(c *xOFConfig) {
		c.onNewXOFStream = append(c.onNewXOFStream, assertions...)
	}
}

// XOFOnAll adds cross-method assertions that span multiple methods.
func XOFOnAll(assertions ...suite.CrossMethodAssertion[crypto.XOF]) XOFOption {
	return func(c *xOFConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type xOFCustomSubtest struct {
	name string
	fn   func(*testing.T, crypto.XOF)
}

type xOFConfig struct {
	prePopulate    func(context.Context, crypto.XOF)
	custom         []xOFCustomSubtest
	onAll          []suite.CrossMethodAssertion[crypto.XOF]
	onAlgorithm    []suite.PureAssertion[crypto.XOF, crypto.Algorithm]
	onID           []suite.PureAssertion[crypto.XOF, crypto.ID]
	onNewXOFStream []suite.PureAssertion[crypto.XOF, crypto.XOFStream]
}

func newXOFConfig(opts ...XOFOption) xOFConfig {
	var cfg xOFConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
