// Code generated by testkit stub. DO NOT EDIT.
// Source: io.go:80-100 (testkit stub XOFStream)

package cryptotest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/cryptotest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestXOFStreamStub(t *testing.T) {
	t.Parallel()

	errTest := testkit.TestError("XOFStream-stub-test")

	t.Run("Read default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		n, err := s.Read(nil)
		testkit.Equal(t, n, 0, "Read must return zero")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("Read fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnRead.Faults(errTest, 1)
		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Read Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnRead.Func(func([]byte) (int, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnRead.Faults(errTest, 1)
		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Read counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnRead.Faults(errTest, 3)
		_, err1 := s.Read(nil)
		_, err2 := s.Read(nil)
		_, err3 := s.Read(nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Read Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		called := false
		s.OnRead.Func(func([]byte) (int, error) {
			called = true
			return 42, nil
		})
		n, err := s.Read(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, n, 42, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Read Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnRead.Returns(42, nil)
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Read records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Read(nil)
		s.OnRead.AssertCalledOnce(t, "must record Read call")
	})

	t.Run("WithXOFStreamRead constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStreamStub(t, cryptotest.WithXOFStreamRead(func([]byte) (int, error) {
			called = true
			return 0, nil
		}))
		_, _ = s.Read(nil)
		testkit.True(t, called, "WithXOFStreamRead must be called")
	})

	t.Run("Read records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Read([]byte{42})
		call := s.OnRead.LastCall(t)
		testkit.Equal(t, call.P, []byte{42}, "P must be recorded")
	})

	t.Run("Read OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		var observed []cryptotest.XOFStreamReadCall
		s.OnRead.OnRecord(func(c cryptotest.XOFStreamReadCall) {
			observed = append(observed, c)
		})
		_, _ = s.Read(nil)
		_, _ = s.Read(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Read call")
	})

	t.Run("Reset default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.Reset()
	})

	t.Run("Reset Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		called := false
		s.OnReset.Func(func() {
			called = true
		})
		s.Reset()
		testkit.True(t, called, "Func must be called")
	})

	t.Run("Reset records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.Reset()
		s.OnReset.AssertCalledOnce(t, "must record Reset call")
	})

	t.Run("WithXOFStreamReset constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStreamStub(t, cryptotest.WithXOFStreamReset(func() {
			called = true
		}))
		s.Reset()
		testkit.True(t, called, "WithXOFStreamReset must be called")
	})

	t.Run("Reset OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		var observed []cryptotest.XOFStreamResetCall
		s.OnReset.OnRecord(func(c cryptotest.XOFStreamResetCall) {
			observed = append(observed, c)
		})
		s.Reset()
		s.Reset()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Reset call")
	})

	t.Run("Write default returns zero", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 0, "Write must return zero")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("Write fault injection fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")
	})

	t.Run("Write Faults wins over Func", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnWrite.Func(func([]byte) (int, error) {
			panic("Func must not be called when Faults is configured")
		})
		s.OnWrite.Faults(errTest, 1)
		_, err := s.Write(nil)
		testkit.ErrorIs(t, err, errTest, "Faults must win over Func")
	})

	t.Run("Write counted fault fires on Nth call", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnWrite.Faults(errTest, 3)
		_, err1 := s.Write(nil)
		_, err2 := s.Write(nil)
		_, err3 := s.Write(nil)
		testkit.NoError(t, err1, "call 1 must succeed")
		testkit.NoError(t, err2, "call 2 must succeed")
		testkit.ErrorIs(t, err3, errTest, "call 3 must fault")
	})

	t.Run("Write Func override", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		called := false
		s.OnWrite.Func(func([]byte) (int, error) {
			called = true
			return 42, nil
		})
		n, err := s.Write(nil)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, n, 42, "Func must return set value")
		testkit.NoError(t, err, "Func must not error")
	})

	t.Run("Write Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnWrite.Returns(42, nil)
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Returns must return set value")
		testkit.NoError(t, err, "Returns must not error")
	})

	t.Run("Write records calls", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Write(nil)
		s.OnWrite.AssertCalledOnce(t, "must record Write call")
	})

	t.Run("WithXOFStreamWrite constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := cryptotest.NewXOFStreamStub(t, cryptotest.WithXOFStreamWrite(func([]byte) (int, error) {
			called = true
			return 0, nil
		}))
		_, _ = s.Write(nil)
		testkit.True(t, called, "WithXOFStreamWrite must be called")
	})

	t.Run("Write records call args", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Write([]byte{42})
		call := s.OnWrite.LastCall(t)
		testkit.Equal(t, call.P, []byte{42}, "P must be recorded")
	})

	t.Run("Write OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		var observed []cryptotest.XOFStreamWriteCall
		s.OnWrite.OnRecord(func(c cryptotest.XOFStreamWriteCall) {
			observed = append(observed, c)
		})
		_, _ = s.Write(nil)
		_, _ = s.Write(nil)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Write call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubBenchMode())
		_, _ = s.Read(nil)
		testkit.Equal(t, s.OnRead.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStreamStub(f)
		s.OnRead.Times(2)
		_, _ = s.Read(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStreamStub(f)
		s.OnRead.TimesAtLeast(3)
		_, _ = s.Read(nil)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Read(nil)
		s.Reset()
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnRead.AssertNotCalled(t, "Read must be cleared after ResetCalls")
		s.OnReset.AssertNotCalled(t, "Reset must be cleared after ResetCalls")
		s.OnWrite.AssertNotCalled(t, "Write must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Read", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStreamStub(f, cryptotest.XOFStreamStubStrict())
		_, _ = s.Read(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Read")
	})

	t.Run("Strict mode fails on unconfigured Reset", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStreamStub(f, cryptotest.XOFStreamStubStrict())
		s.Reset()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Reset")
	})

	t.Run("Strict mode fails on unconfigured Write", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := cryptotest.NewXOFStreamStub(f, cryptotest.XOFStreamStubStrict())
		_, _ = s.Write(nil)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Write")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStreamStub(t)
		inner.OnRead.Returns(0, nil)
		inner.OnWrite.Returns(0, nil)
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubDelegateTo(inner))
		_, _ = s.Read(nil)
		s.Reset()
		_, _ = s.Write(nil)
		s.OnRead.AssertCalledOnce(t, "Read must delegate")
		s.OnReset.AssertCalledOnce(t, "Reset must delegate")
		s.OnWrite.AssertCalledOnce(t, "Write must delegate")
	})

	t.Run("DelegateTo surfaces Read return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStreamStub(t)
		inner.OnRead.Returns(42, nil)
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubDelegateTo(inner))
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Read must return configured value")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("DelegateTo surfaces Write return values", func(t *testing.T) {
		t.Parallel()
		inner := cryptotest.NewXOFStreamStub(t)
		inner.OnWrite.Returns(42, nil)
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubDelegateTo(inner))
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls preserves Read Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnRead.Returns(42, nil)
		_, _ = s.Read(nil)
		s.ResetCalls()
		s.OnRead.AssertNotCalled(t, "ResetCalls must clear recordings")
		n, err := s.Read(nil)
		testkit.Equal(t, n, 42, "Read must return configured value")
		testkit.NoError(t, err, "Read must not error")
	})

	t.Run("ResetCalls preserves Write Returns config", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		s.OnWrite.Returns(42, nil)
		_, _ = s.Write(nil)
		s.ResetCalls()
		s.OnWrite.AssertNotCalled(t, "ResetCalls must clear recordings")
		n, err := s.Write(nil)
		testkit.Equal(t, n, 42, "Write must return configured value")
		testkit.NoError(t, err, "Write must not error")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := cryptotest.NewXOFStreamStub(t)
		_, _ = s.Read(nil)
		testkit.Len(t, s.OnRead.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnRead.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("Read FaultsFor window expires", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := cryptotest.NewXOFStreamStub(t, cryptotest.XOFStreamStubWithClock(clk))
		s.OnRead.FaultsFor(5*time.Second, errTest)

		_, err := s.Read(nil)
		testkit.ErrorIs(t, err, errTest, "must return injected fault")

		clk.Advance(6 * time.Second)
		s.ResetCalls()
		_, err = s.Read(nil)
		testkit.NoError(t, err, "Read must succeed after window expires")
	})
}

func TestXOFStreamStubBenchModeZeroAlloc(t *testing.T) {
	s := cryptotest.NewXOFStreamStub(nil, cryptotest.XOFStreamStubBenchMode())
	s.OnRead.Returns(0, nil)
	s.OnWrite.Returns(0, nil)

	t.Run("Read", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Read(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Read in BenchMode must be 0 alloc")
	})

	t.Run("Reset", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			s.Reset()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Reset in BenchMode must be 0 alloc")
	})

	t.Run("Write", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Write(nil)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Write in BenchMode must be 0 alloc")
	})

}
