// Code generated by testkit suite. DO NOT EDIT.
// Source: io.go:80-100 (testkit suite XOFStream)

package cryptotest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/crypto"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertXOFStreamContract runs conformance assertions against
// implementations of [crypto.XOFStream] produced by factory.
//
//	Default subtests: 5 across 3 methods
//	Shapes detected:  Unknown (Read, Reset, Write)
//	Directives:       none
//	Plug-in points:   XOFStreamOnRead, XOFStreamOnReset, XOFStreamOnWrite, XOFStreamOnAll, XOFStreamCustom
func AssertXOFStreamContract(
	t *testing.T,
	factory func() crypto.XOFStream,
	opts ...XOFStreamOption,
) {
	t.Helper()
	cfg := newXOFStreamConfig(opts...)

	runXOFStreamRead(t, factory, &cfg)
	runXOFStreamReset(t, factory, &cfg)
	runXOFStreamWrite(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[crypto.XOFStream]{
			T:             t,
			CrossBindings: bindings.CrossBindings[crypto.XOFStream]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runXOFStreamRead(t *testing.T, factory func() crypto.XOFStream, cfg *xOFStreamConfig) {
	t.Helper()

	t.Run("Read/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Read panicked on zero-value args (%v) — supply sample values via XOFStreamOnRead", r)
			}
		}()
		s := factory()
		_, _ = s.Read(nil)
	})

	t.Run("Read/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Read(nil)
		})
	})
	if len(cfg.onRead) > 0 {
		t.Run("Read", func(t *testing.T) {
			for _, fn := range cfg.onRead {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runXOFStreamReset(t *testing.T, factory func() crypto.XOFStream, cfg *xOFStreamConfig) {
	t.Helper()

	t.Run("Reset/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Reset panicked on zero-value args (%v) — supply sample values via XOFStreamOnReset", r)
			}
		}()
		s := factory()
		s.Reset()
	})
	if len(cfg.onReset) > 0 {
		t.Run("Reset", func(t *testing.T) {
			for _, fn := range cfg.onReset {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

func runXOFStreamWrite(t *testing.T, factory func() crypto.XOFStream, cfg *xOFStreamConfig) {
	t.Helper()

	t.Run("Write/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Write panicked on zero-value args (%v) — supply sample values via XOFStreamOnWrite", r)
			}
		}()
		s := factory()
		_, _ = s.Write(nil)
	})

	t.Run("Write/nil p", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_, _ = factory().Write(nil)
		})
	})
	if len(cfg.onWrite) > 0 {
		t.Run("Write", func(t *testing.T) {
			for _, fn := range cfg.onWrite {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

// XOFStreamOption configures [AssertXOFStreamContract].
type XOFStreamOption func(*xOFStreamConfig)

// XOFStreamPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func XOFStreamPrePopulate(fn func(ctx context.Context, s crypto.XOFStream)) XOFStreamOption {
	return func(c *xOFStreamConfig) { c.prePopulate = fn }
}

// XOFStreamCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func XOFStreamCustom(name string, fn func(*testing.T, crypto.XOFStream)) XOFStreamOption {
	return func(c *xOFStreamConfig) {
		c.custom = append(c.custom, xOFStreamCustomSubtest{name: name, fn: fn})
	}
}

// XOFStreamOnRead adds plug-in assertions for the Read method.
func XOFStreamOnRead(assertions ...func(*testing.T, crypto.XOFStream)) XOFStreamOption {
	return func(c *xOFStreamConfig) {
		c.onRead = append(c.onRead, assertions...)
	}
}

// XOFStreamOnReset adds plug-in assertions for the Reset method.
func XOFStreamOnReset(assertions ...func(*testing.T, crypto.XOFStream)) XOFStreamOption {
	return func(c *xOFStreamConfig) {
		c.onReset = append(c.onReset, assertions...)
	}
}

// XOFStreamOnWrite adds plug-in assertions for the Write method.
func XOFStreamOnWrite(assertions ...func(*testing.T, crypto.XOFStream)) XOFStreamOption {
	return func(c *xOFStreamConfig) {
		c.onWrite = append(c.onWrite, assertions...)
	}
}

// XOFStreamOnAll adds cross-method assertions that span multiple methods.
func XOFStreamOnAll(assertions ...suite.CrossMethodAssertion[crypto.XOFStream]) XOFStreamOption {
	return func(c *xOFStreamConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type xOFStreamCustomSubtest struct {
	name string
	fn   func(*testing.T, crypto.XOFStream)
}

type xOFStreamConfig struct {
	prePopulate func(context.Context, crypto.XOFStream)
	custom      []xOFStreamCustomSubtest
	onAll       []suite.CrossMethodAssertion[crypto.XOFStream]
	onRead      []func(*testing.T, crypto.XOFStream)
	onReset     []func(*testing.T, crypto.XOFStream)
	onWrite     []func(*testing.T, crypto.XOFStream)
}

func newXOFStreamConfig(opts ...XOFStreamOption) xOFStreamConfig {
	var cfg xOFStreamConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
