// Code generated by testkit suite. DO NOT EDIT.
// Source: gauge.go:27-37 (testkit suite Gauge)

package telemetrytest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertGaugeContract runs conformance assertions against
// implementations of [telemetry.Gauge] produced by factory.
//
//	Default subtests: 4 across 3 methods
//	Shapes detected:  Mutator (Add, Set), Pure (With)
//	Directives:       none
//	Plug-in points:   GaugeOnAdd, GaugeOnSet, GaugeOnWith, GaugeOnAll, GaugeCustom
func AssertGaugeContract(
	t *testing.T,
	factory func() telemetry.Gauge,
	opts ...GaugeOption,
) {
	t.Helper()
	cfg := newGaugeConfig(opts...)

	runGaugeAdd(t, factory, &cfg)
	runGaugeSet(t, factory, &cfg)
	runGaugeWith(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[telemetry.Gauge]{
			T:             t,
			CrossBindings: bindings.CrossBindings[telemetry.Gauge]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runGaugeAdd(t *testing.T, factory func() telemetry.Gauge, cfg *gaugeConfig) {
	t.Helper()

	t.Run("Add/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Add panicked on zero-value args (%v) — supply sample values via GaugeOnAdd", r)
			}
		}()
		s := factory()
		s.Add(t.Context(), 0)
	})
	if len(cfg.onAdd) > 0 {
		t.Run("Add", func(t *testing.T) {
			prePopFactory := func() telemetry.Gauge {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			mctx := suite.MutatorContext[telemetry.Gauge, float64]{
				T: t,
				MutatorBindings: bindings.MutatorBindings[telemetry.Gauge, float64]{
					Factory: prePopFactory,
					Call: func(ctx context.Context, impl telemetry.Gauge, v float64) {
						impl.Add(ctx, v)
					},
				},
			}
			for _, a := range cfg.onAdd {
				a(mctx)
			}
		})
	}
}

func runGaugeSet(t *testing.T, factory func() telemetry.Gauge, cfg *gaugeConfig) {
	t.Helper()

	t.Run("Set/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Set panicked on zero-value args (%v) — supply sample values via GaugeOnSet", r)
			}
		}()
		s := factory()
		s.Set(t.Context(), 0)
	})
	if len(cfg.onSet) > 0 {
		t.Run("Set", func(t *testing.T) {
			prePopFactory := func() telemetry.Gauge {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			mctx := suite.MutatorContext[telemetry.Gauge, float64]{
				T: t,
				MutatorBindings: bindings.MutatorBindings[telemetry.Gauge, float64]{
					Factory: prePopFactory,
					Call: func(ctx context.Context, impl telemetry.Gauge, v float64) {
						impl.Set(ctx, v)
					},
				},
			}
			for _, a := range cfg.onSet {
				a(mctx)
			}
		})
	}
}

func runGaugeWith(t *testing.T, factory func() telemetry.Gauge, cfg *gaugeConfig) {
	t.Helper()

	t.Run("With/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: With panicked on zero-value args (%v) — supply sample values via GaugeOnWith", r)
			}
		}()
		s := factory()
		_ = s.With(nil)
	})

	t.Run("With/nil attrs", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().With(nil)
		})
	})
	if len(cfg.onWith) > 0 {
		t.Run("With", func(t *testing.T) {
			prePopFactory := func() telemetry.Gauge {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[telemetry.Gauge, telemetry.Gauge]{
				T: t,
				PureBindings: bindings.PureBindings[telemetry.Gauge, telemetry.Gauge]{
					Factory: prePopFactory,
					Call: func(impl telemetry.Gauge) telemetry.Gauge {
						return impl.With(nil)
					},
				},
			}
			for _, a := range cfg.onWith {
				a(pctx)
			}
		})
	}
}

// GaugeOption configures [AssertGaugeContract].
type GaugeOption func(*gaugeConfig)

// GaugePrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func GaugePrePopulate(fn func(ctx context.Context, s telemetry.Gauge)) GaugeOption {
	return func(c *gaugeConfig) { c.prePopulate = fn }
}

// GaugeCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func GaugeCustom(name string, fn func(*testing.T, telemetry.Gauge)) GaugeOption {
	return func(c *gaugeConfig) {
		c.custom = append(c.custom, gaugeCustomSubtest{name: name, fn: fn})
	}
}

// GaugeOnAdd adds plug-in assertions for the Add method.
func GaugeOnAdd(assertions ...suite.MutatorAssertion[telemetry.Gauge, float64]) GaugeOption {
	return func(c *gaugeConfig) {
		c.onAdd = append(c.onAdd, assertions...)
	}
}

// GaugeOnSet adds plug-in assertions for the Set method.
func GaugeOnSet(assertions ...suite.MutatorAssertion[telemetry.Gauge, float64]) GaugeOption {
	return func(c *gaugeConfig) {
		c.onSet = append(c.onSet, assertions...)
	}
}

// GaugeOnWith adds plug-in assertions for the With method.
func GaugeOnWith(assertions ...suite.PureAssertion[telemetry.Gauge, telemetry.Gauge]) GaugeOption {
	return func(c *gaugeConfig) {
		c.onWith = append(c.onWith, assertions...)
	}
}

// GaugeOnAll adds cross-method assertions that span multiple methods.
func GaugeOnAll(assertions ...suite.CrossMethodAssertion[telemetry.Gauge]) GaugeOption {
	return func(c *gaugeConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type gaugeCustomSubtest struct {
	name string
	fn   func(*testing.T, telemetry.Gauge)
}

type gaugeConfig struct {
	prePopulate func(context.Context, telemetry.Gauge)
	custom      []gaugeCustomSubtest
	onAll       []suite.CrossMethodAssertion[telemetry.Gauge]
	onAdd       []suite.MutatorAssertion[telemetry.Gauge, float64]
	onSet       []suite.MutatorAssertion[telemetry.Gauge, float64]
	onWith      []suite.PureAssertion[telemetry.Gauge, telemetry.Gauge]
}

func newGaugeConfig(opts ...GaugeOption) gaugeConfig {
	var cfg gaugeConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
