// Code generated by testkit suite. DO NOT EDIT.
// Source: histogram.go:19-23 (testkit suite Histogram)

package telemetrytest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertHistogramContract runs conformance assertions against
// implementations of [telemetry.Histogram] produced by factory.
//
//	Default subtests: 3 across 2 methods
//	Shapes detected:  Mutator (Record), Pure (With)
//	Directives:       none
//	Plug-in points:   HistogramOnRecord, HistogramOnWith, HistogramOnAll, HistogramCustom
func AssertHistogramContract(
	t *testing.T,
	factory func() telemetry.Histogram,
	opts ...HistogramOption,
) {
	t.Helper()
	cfg := newHistogramConfig(opts...)

	runHistogramRecord(t, factory, &cfg)
	runHistogramWith(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[telemetry.Histogram]{
			T:             t,
			CrossBindings: bindings.CrossBindings[telemetry.Histogram]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runHistogramRecord(t *testing.T, factory func() telemetry.Histogram, cfg *histogramConfig) {
	t.Helper()

	t.Run("Record/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Record panicked on zero-value args (%v) — supply sample values via HistogramOnRecord", r)
			}
		}()
		s := factory()
		s.Record(t.Context(), 0)
	})
	if len(cfg.onRecord) > 0 {
		t.Run("Record", func(t *testing.T) {
			prePopFactory := func() telemetry.Histogram {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			mctx := suite.MutatorContext[telemetry.Histogram, float64]{
				T: t,
				MutatorBindings: bindings.MutatorBindings[telemetry.Histogram, float64]{
					Factory: prePopFactory,
					Call: func(ctx context.Context, impl telemetry.Histogram, v float64) {
						impl.Record(ctx, v)
					},
				},
			}
			for _, a := range cfg.onRecord {
				a(mctx)
			}
		})
	}
}

func runHistogramWith(t *testing.T, factory func() telemetry.Histogram, cfg *histogramConfig) {
	t.Helper()

	t.Run("With/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: With panicked on zero-value args (%v) — supply sample values via HistogramOnWith", r)
			}
		}()
		s := factory()
		_ = s.With(nil)
	})

	t.Run("With/nil attrs", func(t *testing.T) {
		t.Parallel()
		testkit.AssertNilSafe(t, func() {
			_ = factory().With(nil)
		})
	})
	if len(cfg.onWith) > 0 {
		t.Run("With", func(t *testing.T) {
			prePopFactory := func() telemetry.Histogram {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[telemetry.Histogram, telemetry.Histogram]{
				T: t,
				PureBindings: bindings.PureBindings[telemetry.Histogram, telemetry.Histogram]{
					Factory: prePopFactory,
					Call: func(impl telemetry.Histogram) telemetry.Histogram {
						return impl.With(nil)
					},
				},
			}
			for _, a := range cfg.onWith {
				a(pctx)
			}
		})
	}
}

// HistogramOption configures [AssertHistogramContract].
type HistogramOption func(*histogramConfig)

// HistogramPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func HistogramPrePopulate(fn func(ctx context.Context, s telemetry.Histogram)) HistogramOption {
	return func(c *histogramConfig) { c.prePopulate = fn }
}

// HistogramCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func HistogramCustom(name string, fn func(*testing.T, telemetry.Histogram)) HistogramOption {
	return func(c *histogramConfig) {
		c.custom = append(c.custom, histogramCustomSubtest{name: name, fn: fn})
	}
}

// HistogramOnRecord adds plug-in assertions for the Record method.
func HistogramOnRecord(assertions ...suite.MutatorAssertion[telemetry.Histogram, float64]) HistogramOption {
	return func(c *histogramConfig) {
		c.onRecord = append(c.onRecord, assertions...)
	}
}

// HistogramOnWith adds plug-in assertions for the With method.
func HistogramOnWith(assertions ...suite.PureAssertion[telemetry.Histogram, telemetry.Histogram]) HistogramOption {
	return func(c *histogramConfig) {
		c.onWith = append(c.onWith, assertions...)
	}
}

// HistogramOnAll adds cross-method assertions that span multiple methods.
func HistogramOnAll(assertions ...suite.CrossMethodAssertion[telemetry.Histogram]) HistogramOption {
	return func(c *histogramConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type histogramCustomSubtest struct {
	name string
	fn   func(*testing.T, telemetry.Histogram)
}

type histogramConfig struct {
	prePopulate func(context.Context, telemetry.Histogram)
	custom      []histogramCustomSubtest
	onAll       []suite.CrossMethodAssertion[telemetry.Histogram]
	onRecord    []suite.MutatorAssertion[telemetry.Histogram, float64]
	onWith      []suite.PureAssertion[telemetry.Histogram, telemetry.Histogram]
}

func newHistogramConfig(opts ...HistogramOption) histogramConfig {
	var cfg histogramConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
