// Code generated by testkit stub. DO NOT EDIT.
// Source: reporter.go:44-59 (testkit stub Reporter)

package telemetrytest_test

import (
	"testing"

	"go.thesmos.sh/core/coretest/telemetrytest"
	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestReporterStub(t *testing.T) {
	t.Parallel()

	t.Run("Counter default returns zero", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		result := s.Counter(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Counter must return zero")
	})

	t.Run("Counter Func override", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		called := false
		s.OnCounter.Func(func(telemetry.InstrumentSpec) telemetry.Counter {
			called = true
			return nil
		})
		result := s.Counter(telemetry.InstrumentSpec{})
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("Counter Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnCounter.Returns(nil)
		result := s.Counter(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("Counter records calls", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Counter(telemetry.InstrumentSpec{})
		s.OnCounter.AssertCalledOnce(t, "must record Counter call")
	})

	t.Run("WithReporterCounter constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := telemetrytest.NewReporterStub(t, telemetrytest.WithReporterCounter(func(telemetry.InstrumentSpec) telemetry.Counter {
			called = true
			return nil
		}))
		_ = s.Counter(telemetry.InstrumentSpec{})
		testkit.True(t, called, "WithReporterCounter must be called")
	})

	t.Run("Counter records call args", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Counter(telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")})
		call := s.OnCounter.LastCall(t)
		testkit.Equal(t, call.Spec, telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")}, "Spec must be recorded")
	})

	t.Run("Counter OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		var observed []telemetrytest.ReporterCounterCall
		s.OnCounter.OnRecord(func(c telemetrytest.ReporterCounterCall) {
			observed = append(observed, c)
		})
		_ = s.Counter(telemetry.InstrumentSpec{})
		_ = s.Counter(telemetry.InstrumentSpec{})
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Counter call")
	})

	t.Run("Gauge default returns zero", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		result := s.Gauge(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Gauge must return zero")
	})

	t.Run("Gauge Func override", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		called := false
		s.OnGauge.Func(func(telemetry.InstrumentSpec) telemetry.Gauge {
			called = true
			return nil
		})
		result := s.Gauge(telemetry.InstrumentSpec{})
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("Gauge Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnGauge.Returns(nil)
		result := s.Gauge(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("Gauge records calls", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Gauge(telemetry.InstrumentSpec{})
		s.OnGauge.AssertCalledOnce(t, "must record Gauge call")
	})

	t.Run("WithReporterGauge constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := telemetrytest.NewReporterStub(t, telemetrytest.WithReporterGauge(func(telemetry.InstrumentSpec) telemetry.Gauge {
			called = true
			return nil
		}))
		_ = s.Gauge(telemetry.InstrumentSpec{})
		testkit.True(t, called, "WithReporterGauge must be called")
	})

	t.Run("Gauge records call args", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Gauge(telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")})
		call := s.OnGauge.LastCall(t)
		testkit.Equal(t, call.Spec, telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")}, "Spec must be recorded")
	})

	t.Run("Gauge OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		var observed []telemetrytest.ReporterGaugeCall
		s.OnGauge.OnRecord(func(c telemetrytest.ReporterGaugeCall) {
			observed = append(observed, c)
		})
		_ = s.Gauge(telemetry.InstrumentSpec{})
		_ = s.Gauge(telemetry.InstrumentSpec{})
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Gauge call")
	})

	t.Run("Histogram default returns zero", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		result := s.Histogram(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Histogram must return zero")
	})

	t.Run("Histogram Func override", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		called := false
		s.OnHistogram.Func(func(telemetry.InstrumentSpec) telemetry.Histogram {
			called = true
			return nil
		})
		result := s.Histogram(telemetry.InstrumentSpec{})
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("Histogram Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnHistogram.Returns(nil)
		result := s.Histogram(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("Histogram records calls", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Histogram(telemetry.InstrumentSpec{})
		s.OnHistogram.AssertCalledOnce(t, "must record Histogram call")
	})

	t.Run("WithReporterHistogram constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := telemetrytest.NewReporterStub(t, telemetrytest.WithReporterHistogram(func(telemetry.InstrumentSpec) telemetry.Histogram {
			called = true
			return nil
		}))
		_ = s.Histogram(telemetry.InstrumentSpec{})
		testkit.True(t, called, "WithReporterHistogram must be called")
	})

	t.Run("Histogram records call args", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Histogram(telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")})
		call := s.OnHistogram.LastCall(t)
		testkit.Equal(t, call.Spec, telemetry.InstrumentSpec{Name: telemetry.InstrumentName("test-name")}, "Spec must be recorded")
	})

	t.Run("Histogram OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		var observed []telemetrytest.ReporterHistogramCall
		s.OnHistogram.OnRecord(func(c telemetrytest.ReporterHistogramCall) {
			observed = append(observed, c)
		})
		_ = s.Histogram(telemetry.InstrumentSpec{})
		_ = s.Histogram(telemetry.InstrumentSpec{})
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Histogram call")
	})

	t.Run("Tracer default returns zero", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		result := s.Tracer("")
		testkit.Equal(t, result, nil, "Tracer must return zero")
	})

	t.Run("Tracer Func override", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		called := false
		s.OnTracer.Func(func(telemetry.InstrumentName) telemetry.Tracer {
			called = true
			return nil
		})
		result := s.Tracer("")
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("Tracer Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnTracer.Returns(nil)
		result := s.Tracer("")
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("Tracer records calls", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Tracer("")
		s.OnTracer.AssertCalledOnce(t, "must record Tracer call")
	})

	t.Run("WithReporterTracer constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := telemetrytest.NewReporterStub(t, telemetrytest.WithReporterTracer(func(telemetry.InstrumentName) telemetry.Tracer {
			called = true
			return nil
		}))
		_ = s.Tracer("")
		testkit.True(t, called, "WithReporterTracer must be called")
	})

	t.Run("Tracer records call args", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Tracer(telemetry.InstrumentName("test-name"))
		call := s.OnTracer.LastCall(t)
		testkit.Equal(t, call.Name, telemetry.InstrumentName("test-name"), "Name must be recorded")
	})

	t.Run("Tracer OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		var observed []telemetrytest.ReporterTracerCall
		s.OnTracer.OnRecord(func(c telemetrytest.ReporterTracerCall) {
			observed = append(observed, c)
		})
		_ = s.Tracer("")
		_ = s.Tracer("")
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Tracer call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubBenchMode())
		_ = s.Counter(telemetry.InstrumentSpec{})
		testkit.Equal(t, s.OnCounter.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f)
		s.OnCounter.Times(2)
		_ = s.Counter(telemetry.InstrumentSpec{})
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f)
		s.OnCounter.TimesAtLeast(3)
		_ = s.Counter(telemetry.InstrumentSpec{})
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Counter(telemetry.InstrumentSpec{})
		_ = s.Gauge(telemetry.InstrumentSpec{})
		_ = s.Histogram(telemetry.InstrumentSpec{})
		_ = s.Tracer("")
		s.ResetCalls()
		s.OnCounter.AssertNotCalled(t, "Counter must be cleared after ResetCalls")
		s.OnGauge.AssertNotCalled(t, "Gauge must be cleared after ResetCalls")
		s.OnHistogram.AssertNotCalled(t, "Histogram must be cleared after ResetCalls")
		s.OnTracer.AssertNotCalled(t, "Tracer must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Counter", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f, telemetrytest.ReporterStubStrict())
		_ = s.Counter(telemetry.InstrumentSpec{})
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Counter")
	})

	t.Run("Strict mode fails on unconfigured Gauge", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f, telemetrytest.ReporterStubStrict())
		_ = s.Gauge(telemetry.InstrumentSpec{})
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Gauge")
	})

	t.Run("Strict mode fails on unconfigured Histogram", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f, telemetrytest.ReporterStubStrict())
		_ = s.Histogram(telemetry.InstrumentSpec{})
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Histogram")
	})

	t.Run("Strict mode fails on unconfigured Tracer", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewReporterStub(f, telemetrytest.ReporterStubStrict())
		_ = s.Tracer("")
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Tracer")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewReporterStub(t)
		inner.OnCounter.Returns(nil)
		inner.OnGauge.Returns(nil)
		inner.OnHistogram.Returns(nil)
		inner.OnTracer.Returns(nil)
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubDelegateTo(inner))
		_ = s.Counter(telemetry.InstrumentSpec{})
		_ = s.Gauge(telemetry.InstrumentSpec{})
		_ = s.Histogram(telemetry.InstrumentSpec{})
		_ = s.Tracer("")
		s.OnCounter.AssertCalledOnce(t, "Counter must delegate")
		s.OnGauge.AssertCalledOnce(t, "Gauge must delegate")
		s.OnHistogram.AssertCalledOnce(t, "Histogram must delegate")
		s.OnTracer.AssertCalledOnce(t, "Tracer must delegate")
	})

	t.Run("DelegateTo surfaces Counter return values", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewReporterStub(t)
		inner.OnCounter.Returns(nil)
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubDelegateTo(inner))
		result := s.Counter(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Counter must return configured value")
	})

	t.Run("DelegateTo surfaces Gauge return values", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewReporterStub(t)
		inner.OnGauge.Returns(nil)
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubDelegateTo(inner))
		result := s.Gauge(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Gauge must return configured value")
	})

	t.Run("DelegateTo surfaces Histogram return values", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewReporterStub(t)
		inner.OnHistogram.Returns(nil)
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubDelegateTo(inner))
		result := s.Histogram(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Histogram must return configured value")
	})

	t.Run("DelegateTo surfaces Tracer return values", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewReporterStub(t)
		inner.OnTracer.Returns(nil)
		s := telemetrytest.NewReporterStub(t, telemetrytest.ReporterStubDelegateTo(inner))
		result := s.Tracer("")
		testkit.Equal(t, result, nil, "Tracer must return configured value")
	})

	t.Run("ResetCalls preserves Counter Returns config", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnCounter.Returns(nil)
		_ = s.Counter(telemetry.InstrumentSpec{})
		s.ResetCalls()
		s.OnCounter.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Counter(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Counter must return configured value")
	})

	t.Run("ResetCalls preserves Gauge Returns config", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnGauge.Returns(nil)
		_ = s.Gauge(telemetry.InstrumentSpec{})
		s.ResetCalls()
		s.OnGauge.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Gauge(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Gauge must return configured value")
	})

	t.Run("ResetCalls preserves Histogram Returns config", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnHistogram.Returns(nil)
		_ = s.Histogram(telemetry.InstrumentSpec{})
		s.ResetCalls()
		s.OnHistogram.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Histogram(telemetry.InstrumentSpec{})
		testkit.Equal(t, result, nil, "Histogram must return configured value")
	})

	t.Run("ResetCalls preserves Tracer Returns config", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		s.OnTracer.Returns(nil)
		_ = s.Tracer("")
		s.ResetCalls()
		s.OnTracer.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Tracer("")
		testkit.Equal(t, result, nil, "Tracer must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewReporterStub(t)
		_ = s.Counter(telemetry.InstrumentSpec{})
		testkit.Len(t, s.OnCounter.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnCounter.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestReporterStubBenchModeZeroAlloc(t *testing.T) {
	s := telemetrytest.NewReporterStub(nil, telemetrytest.ReporterStubBenchMode())
	s.OnCounter.Returns(nil)
	s.OnGauge.Returns(nil)
	s.OnHistogram.Returns(nil)
	s.OnTracer.Returns(nil)

	t.Run("Counter", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Counter(telemetry.InstrumentSpec{})
		})
		testkit.Equal(t, int(avgAllocs), 0, "Counter in BenchMode must be 0 alloc")
	})

	t.Run("Gauge", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Gauge(telemetry.InstrumentSpec{})
		})
		testkit.Equal(t, int(avgAllocs), 0, "Gauge in BenchMode must be 0 alloc")
	})

	t.Run("Histogram", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Histogram(telemetry.InstrumentSpec{})
		})
		testkit.Equal(t, int(avgAllocs), 0, "Histogram in BenchMode must be 0 alloc")
	})

	t.Run("Tracer", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Tracer("")
		})
		testkit.Equal(t, int(avgAllocs), 0, "Tracer in BenchMode must be 0 alloc")
	})

}
