// Code generated by testkit stub. DO NOT EDIT.
// Source: reporter.go:44-59 (testkit stub Reporter)

package telemetrytest

import (
	"testing"

	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ telemetry.Reporter = (*ReporterStub)(nil)

// --- Call types ---

// ReporterCounterCall records one invocation of telemetry.Reporter.Counter.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ReporterCounterCall struct {
	Spec   telemetry.InstrumentSpec
	Result telemetry.Counter
}

// ReporterGaugeCall records one invocation of telemetry.Reporter.Gauge.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ReporterGaugeCall struct {
	Spec   telemetry.InstrumentSpec
	Result telemetry.Gauge
}

// ReporterHistogramCall records one invocation of telemetry.Reporter.Histogram.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ReporterHistogramCall struct {
	Spec   telemetry.InstrumentSpec
	Result telemetry.Histogram
}

// ReporterTracerCall records one invocation of telemetry.Reporter.Tracer.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ReporterTracerCall struct {
	Name   telemetry.InstrumentName
	Result telemetry.Tracer
}

// --- Per-method stubs ---

// ReporterCounterStub controls behavior and records calls for Counter.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ReporterCounterStub struct {
	*stub.MethodStub[ReporterCounterCall]
	fn       func(telemetry.InstrumentSpec) telemetry.Counter
	fallback *reporterCounterReturn
}

type reporterCounterReturn struct {
	Result telemetry.Counter
}

// Returns sets a fixed return value for Counter.
func (s *ReporterCounterStub) Returns(result telemetry.Counter) *ReporterCounterStub {
	s.fallback = &reporterCounterReturn{Result: result}
	return s
}

// Func sets a function override for Counter.
func (s *ReporterCounterStub) Func(fn func(telemetry.InstrumentSpec) telemetry.Counter) *ReporterCounterStub {
	s.fn = fn
	return s
}

// ReporterGaugeStub controls behavior and records calls for Gauge.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ReporterGaugeStub struct {
	*stub.MethodStub[ReporterGaugeCall]
	fn       func(telemetry.InstrumentSpec) telemetry.Gauge
	fallback *reporterGaugeReturn
}

type reporterGaugeReturn struct {
	Result telemetry.Gauge
}

// Returns sets a fixed return value for Gauge.
func (s *ReporterGaugeStub) Returns(result telemetry.Gauge) *ReporterGaugeStub {
	s.fallback = &reporterGaugeReturn{Result: result}
	return s
}

// Func sets a function override for Gauge.
func (s *ReporterGaugeStub) Func(fn func(telemetry.InstrumentSpec) telemetry.Gauge) *ReporterGaugeStub {
	s.fn = fn
	return s
}

// ReporterHistogramStub controls behavior and records calls for Histogram.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ReporterHistogramStub struct {
	*stub.MethodStub[ReporterHistogramCall]
	fn       func(telemetry.InstrumentSpec) telemetry.Histogram
	fallback *reporterHistogramReturn
}

type reporterHistogramReturn struct {
	Result telemetry.Histogram
}

// Returns sets a fixed return value for Histogram.
func (s *ReporterHistogramStub) Returns(result telemetry.Histogram) *ReporterHistogramStub {
	s.fallback = &reporterHistogramReturn{Result: result}
	return s
}

// Func sets a function override for Histogram.
func (s *ReporterHistogramStub) Func(fn func(telemetry.InstrumentSpec) telemetry.Histogram) *ReporterHistogramStub {
	s.fn = fn
	return s
}

// ReporterTracerStub controls behavior and records calls for Tracer.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ReporterTracerStub struct {
	*stub.MethodStub[ReporterTracerCall]
	fn       func(telemetry.InstrumentName) telemetry.Tracer
	fallback *reporterTracerReturn
}

type reporterTracerReturn struct {
	Result telemetry.Tracer
}

// Returns sets a fixed return value for Tracer.
func (s *ReporterTracerStub) Returns(result telemetry.Tracer) *ReporterTracerStub {
	s.fallback = &reporterTracerReturn{Result: result}
	return s
}

// Func sets a function override for Tracer.
func (s *ReporterTracerStub) Func(fn func(telemetry.InstrumentName) telemetry.Tracer) *ReporterTracerStub {
	s.fn = fn
	return s
}

// --- ReporterStub ---

// ReporterStubOption configures a [ReporterStub] at construction time.
type ReporterStubOption func(*ReporterStub)

// ReporterStubStrict enables strict mode — unconfigured methods fail the test.
func ReporterStubStrict() ReporterStubOption {
	return func(s *ReporterStub) { s.strict = true }
}

// ReporterStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func ReporterStubDelegateTo(impl telemetry.Reporter) ReporterStubOption {
	return func(s *ReporterStub) {
		s.OnCounter.Func(impl.Counter)
		s.OnGauge.Func(impl.Gauge)
		s.OnHistogram.Func(impl.Histogram)
		s.OnTracer.Func(impl.Tracer)
	}
}

// ReporterStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func ReporterStubWithClock(clk clock.Clock) ReporterStubOption {
	return func(s *ReporterStub) {
		s.OnCounter.WithClock(clk)
		s.OnGauge.WithClock(clk)
		s.OnHistogram.WithClock(clk)
		s.OnTracer.WithClock(clk)
	}
}

// ReporterStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func ReporterStubWithRandSource(src rand.Source) ReporterStubOption {
	return func(s *ReporterStub) {
		s.OnCounter.WithRandSource(src)
		s.OnGauge.WithRandSource(src)
		s.OnHistogram.WithRandSource(src)
		s.OnTracer.WithRandSource(src)
	}
}

// ReporterStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func ReporterStubBenchMode() ReporterStubOption {
	return func(s *ReporterStub) {
		s.OnCounter.BenchMode()
		s.OnGauge.BenchMode()
		s.OnHistogram.BenchMode()
		s.OnTracer.BenchMode()
	}
}

// WithReporterCounter sets a function override at construction time.
func WithReporterCounter(fn func(telemetry.InstrumentSpec) telemetry.Counter) ReporterStubOption {
	return func(s *ReporterStub) { s.OnCounter.Func(fn) }
}

// WithReporterGauge sets a function override at construction time.
func WithReporterGauge(fn func(telemetry.InstrumentSpec) telemetry.Gauge) ReporterStubOption {
	return func(s *ReporterStub) { s.OnGauge.Func(fn) }
}

// WithReporterHistogram sets a function override at construction time.
func WithReporterHistogram(fn func(telemetry.InstrumentSpec) telemetry.Histogram) ReporterStubOption {
	return func(s *ReporterStub) { s.OnHistogram.Func(fn) }
}

// WithReporterTracer sets a function override at construction time.
func WithReporterTracer(fn func(telemetry.InstrumentName) telemetry.Tracer) ReporterStubOption {
	return func(s *ReporterStub) { s.OnTracer.Func(fn) }
}

// ReporterStub is a configurable test double for [telemetry.Reporter].
type ReporterStub struct {
	OnCounter   *ReporterCounterStub
	OnGauge     *ReporterGaugeStub
	OnHistogram *ReporterHistogramStub
	OnTracer    *ReporterTracerStub
	strict      bool
}

// NewReporterStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewReporterStub(tb testing.TB, opts ...ReporterStubOption) *ReporterStub {
	s := &ReporterStub{
		OnCounter:   &ReporterCounterStub{MethodStub: stub.NewMethodStub[ReporterCounterCall](tb, "Reporter.Counter")},
		OnGauge:     &ReporterGaugeStub{MethodStub: stub.NewMethodStub[ReporterGaugeCall](tb, "Reporter.Gauge")},
		OnHistogram: &ReporterHistogramStub{MethodStub: stub.NewMethodStub[ReporterHistogramCall](tb, "Reporter.Histogram")},
		OnTracer:    &ReporterTracerStub{MethodStub: stub.NewMethodStub[ReporterTracerCall](tb, "Reporter.Tracer")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnCounter.Strict()
		s.OnGauge.Strict()
		s.OnHistogram.Strict()
		s.OnTracer.Strict()
	}
	if tb != nil {
		if _, isFuzz := tb.(*testing.F); !isFuzz {
			tb.Cleanup(func() {
				s.OnCounter.Verify()
				s.OnGauge.Verify()
				s.OnHistogram.Verify()
				s.OnTracer.Verify()
			})
		}
	}
	return s
}

// ResetCalls clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *ReporterStub) ResetCalls() {
	s.OnCounter.Reset()
	s.OnGauge.Reset()
	s.OnHistogram.Reset()
	s.OnTracer.Reset()
}

// --- Interface method implementations ---

func (s *ReporterStub) Counter(spec telemetry.InstrumentSpec) telemetry.Counter {
	s.OnCounter.SleepLatency()
	call := ReporterCounterCall{Spec: spec}
	if s.OnCounter.fn != nil {
		r0 := s.OnCounter.fn(spec)
		call.Result = r0
		s.OnCounter.Record(call)
		return r0
	}
	if s.OnCounter.fallback != nil {
		f := s.OnCounter.fallback
		call.Result = f.Result
		s.OnCounter.Record(call)
		return f.Result
	}
	s.OnCounter.FailUnexpectedCall(call)
	s.OnCounter.Record(call)
	return nil
}

func (s *ReporterStub) Gauge(spec telemetry.InstrumentSpec) telemetry.Gauge {
	s.OnGauge.SleepLatency()
	call := ReporterGaugeCall{Spec: spec}
	if s.OnGauge.fn != nil {
		r0 := s.OnGauge.fn(spec)
		call.Result = r0
		s.OnGauge.Record(call)
		return r0
	}
	if s.OnGauge.fallback != nil {
		f := s.OnGauge.fallback
		call.Result = f.Result
		s.OnGauge.Record(call)
		return f.Result
	}
	s.OnGauge.FailUnexpectedCall(call)
	s.OnGauge.Record(call)
	return nil
}

func (s *ReporterStub) Histogram(spec telemetry.InstrumentSpec) telemetry.Histogram {
	s.OnHistogram.SleepLatency()
	call := ReporterHistogramCall{Spec: spec}
	if s.OnHistogram.fn != nil {
		r0 := s.OnHistogram.fn(spec)
		call.Result = r0
		s.OnHistogram.Record(call)
		return r0
	}
	if s.OnHistogram.fallback != nil {
		f := s.OnHistogram.fallback
		call.Result = f.Result
		s.OnHistogram.Record(call)
		return f.Result
	}
	s.OnHistogram.FailUnexpectedCall(call)
	s.OnHistogram.Record(call)
	return nil
}

func (s *ReporterStub) Tracer(name telemetry.InstrumentName) telemetry.Tracer {
	s.OnTracer.SleepLatency()
	call := ReporterTracerCall{Name: name}
	if s.OnTracer.fn != nil {
		r0 := s.OnTracer.fn(name)
		call.Result = r0
		s.OnTracer.Record(call)
		return r0
	}
	if s.OnTracer.fallback != nil {
		f := s.OnTracer.fallback
		call.Result = f.Result
		s.OnTracer.Record(call)
		return f.Result
	}
	s.OnTracer.FailUnexpectedCall(call)
	s.OnTracer.Record(call)
	return nil
}
