// Code generated by testkit stub. DO NOT EDIT.
// Source: tracer.go:37-37 (testkit stub Tracer)

package telemetrytest_test

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/telemetrytest"
	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
)

func TestTracerStub(t *testing.T) {
	t.Parallel()

	t.Run("Start default returns zero", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		result0, result1 := s.Start(t.Context(), "")
		testkit.Equal(t, result0, nil, "Start must return zero")
		testkit.Equal(t, result1, nil, "Start must return zero")
	})

	t.Run("Start Func override", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		called := false
		s.OnStart.Func(func(context.Context, telemetry.SpanName, ...telemetry.SpanOption) (context.Context, telemetry.Span) {
			called = true
			return nil, nil
		})
		result0, result1 := s.Start(t.Context(), "")
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result0, nil, "Func must return set value")
		testkit.Equal(t, result1, nil, "Func must return set value")
	})

	t.Run("Start Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		s.OnStart.Returns(nil, nil)
		result0, result1 := s.Start(t.Context(), "")
		testkit.Equal(t, result0, nil, "Returns must return set value")
		testkit.Equal(t, result1, nil, "Returns must return set value")
	})

	t.Run("Start records calls", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		_, _ = s.Start(t.Context(), "")
		s.OnStart.AssertCalledOnce(t, "must record Start call")
	})

	t.Run("WithTracerStart constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := telemetrytest.NewTracerStub(t, telemetrytest.WithTracerStart(func(context.Context, telemetry.SpanName, ...telemetry.SpanOption) (context.Context, telemetry.Span) {
			called = true
			return nil, nil
		}))
		_, _ = s.Start(t.Context(), "")
		testkit.True(t, called, "WithTracerStart must be called")
	})

	t.Run("Start records call args", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		_, _ = s.Start(t.Context(), telemetry.SpanName("test-name"))
		call := s.OnStart.LastCall(t)
		testkit.Equal(t, call.Name, telemetry.SpanName("test-name"), "Name must be recorded")
	})

	t.Run("Start OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		var observed []telemetrytest.TracerStartCall
		s.OnStart.OnRecord(func(c telemetrytest.TracerStartCall) {
			observed = append(observed, c)
		})
		_, _ = s.Start(t.Context(), "")
		_, _ = s.Start(t.Context(), "")
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Start call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubBenchMode())
		_, _ = s.Start(t.Context(), "")
		testkit.Equal(t, s.OnStart.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewTracerStub(f)
		s.OnStart.Times(2)
		_, _ = s.Start(t.Context(), "")
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewTracerStub(f)
		s.OnStart.TimesAtLeast(3)
		_, _ = s.Start(t.Context(), "")
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		_, _ = s.Start(t.Context(), "")
		s.ResetCalls()
		s.OnStart.AssertNotCalled(t, "Start must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured Start", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := telemetrytest.NewTracerStub(f, telemetrytest.TracerStubStrict())
		_, _ = s.Start(t.Context(), "")
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Start")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewTracerStub(t)
		inner.OnStart.Returns(nil, nil)
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubDelegateTo(inner))
		_, _ = s.Start(t.Context(), "")
		s.OnStart.AssertCalledOnce(t, "Start must delegate")
	})

	t.Run("DelegateTo surfaces Start return values", func(t *testing.T) {
		t.Parallel()
		inner := telemetrytest.NewTracerStub(t)
		inner.OnStart.Returns(nil, nil)
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubDelegateTo(inner))
		result0, result1 := s.Start(t.Context(), "")
		testkit.Equal(t, result0, nil, "Start must return configured value")
		testkit.Equal(t, result1, nil, "Start must return configured value")
	})

	t.Run("ResetCalls preserves Start Returns config", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		s.OnStart.Returns(nil, nil)
		_, _ = s.Start(t.Context(), "")
		s.ResetCalls()
		s.OnStart.AssertNotCalled(t, "ResetCalls must clear recordings")
		result0, result1 := s.Start(t.Context(), "")
		testkit.Equal(t, result0, nil, "Start must return configured value")
		testkit.Equal(t, result1, nil, "Start must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := telemetrytest.NewTracerStub(t)
		_, _ = s.Start(t.Context(), "")
		testkit.Len(t, s.OnStart.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnStart.Timestamped(), 0, "ResetCalls must clear timestamps")
	})

	t.Run("Start Latency honors virtual clock", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubWithClock(clk))
		s.OnStart.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _ = s.Start(t.Context(), "")
			close(done)
		}()

		clk.AwaitWaiters(1)
		start := time.Now()
		clk.Advance(6 * time.Second)
		<-done
		testkit.True(t, time.Since(start) < 100*time.Millisecond,
			"Latency must use virtual clock, not real time")
	})

	t.Run("Start Latency happens before Record", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		s := telemetrytest.NewTracerStub(t, telemetrytest.TracerStubWithClock(clk))
		s.OnStart.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _ = s.Start(t.Context(), "")
			close(done)
		}()

		clk.AwaitWaiters(1)
		testkit.Equal(t, s.OnStart.CallCount(), 0,
			"call must not record until latency completes")
		clk.Advance(6 * time.Second)
		<-done
		testkit.Equal(t, s.OnStart.CallCount(), 1,
			"call records after latency")
	})

	t.Run("Start Latency applies on DelegateTo path", func(t *testing.T) {
		t.Parallel()
		clk := clock.NewTestClock(time.Unix(0, 0))
		inner := telemetrytest.NewTracerStub(t)
		inner.OnStart.Returns(nil, nil)
		s := telemetrytest.NewTracerStub(t,
			telemetrytest.TracerStubWithClock(clk),
			telemetrytest.TracerStubDelegateTo(inner))
		s.OnStart.Latency(5 * time.Second)

		done := make(chan struct{})
		go func() {
			_, _ = s.Start(t.Context(), "")
			close(done)
		}()

		clk.AwaitWaiters(1)
		start := time.Now()
		clk.Advance(6 * time.Second)
		<-done
		testkit.True(t, time.Since(start) < 100*time.Millisecond,
			"DelegateTo path must honor Latency with virtual clock")
	})
}

func TestTracerStubBenchModeZeroAlloc(t *testing.T) {
	s := telemetrytest.NewTracerStub(nil, telemetrytest.TracerStubBenchMode())
	s.OnStart.Returns(nil, nil)

	t.Run("Start", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_, _ = s.Start(t.Context(), "")
		})
		testkit.Equal(t, int(avgAllocs), 0, "Start in BenchMode must be 0 alloc")
	})

}
