// Code generated by testkit suite. DO NOT EDIT.
// Source: tracer.go:37-37 (testkit suite Tracer)

package telemetrytest

import (
	"context"
	"testing"

	"go.thesmos.sh/core/telemetry"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertTracerContract runs conformance assertions against
// implementations of [telemetry.Tracer] produced by factory.
//
//	Default subtests: 1 across 1 methods
//	Shapes detected:  Unknown (Start)
//	Directives:       none
//	Plug-in points:   TracerOnStart, TracerOnAll, TracerCustom
func AssertTracerContract(
	t *testing.T,
	factory func() telemetry.Tracer,
	opts ...TracerOption,
) {
	t.Helper()
	cfg := newTracerConfig(opts...)

	runTracerStart(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[telemetry.Tracer]{
			T:             t,
			CrossBindings: bindings.CrossBindings[telemetry.Tracer]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runTracerStart(t *testing.T, factory func() telemetry.Tracer, cfg *tracerConfig) {
	t.Helper()

	t.Run("Start/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Start panicked on zero-value args (%v) — supply sample values via TracerOnStart", r)
			}
		}()
		s := factory()
		_, _ = s.Start(t.Context(), "")
	})
	if len(cfg.onStart) > 0 {
		t.Run("Start", func(t *testing.T) {
			for _, fn := range cfg.onStart {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				fn(t, impl)
			}
		})
	}
}

// TracerOption configures [AssertTracerContract].
type TracerOption func(*tracerConfig)

// TracerPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func TracerPrePopulate(fn func(ctx context.Context, s telemetry.Tracer)) TracerOption {
	return func(c *tracerConfig) { c.prePopulate = fn }
}

// TracerCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func TracerCustom(name string, fn func(*testing.T, telemetry.Tracer)) TracerOption {
	return func(c *tracerConfig) {
		c.custom = append(c.custom, tracerCustomSubtest{name: name, fn: fn})
	}
}

// TracerOnStart adds plug-in assertions for the Start method.
func TracerOnStart(assertions ...func(*testing.T, telemetry.Tracer)) TracerOption {
	return func(c *tracerConfig) {
		c.onStart = append(c.onStart, assertions...)
	}
}

// TracerOnAll adds cross-method assertions that span multiple methods.
func TracerOnAll(assertions ...suite.CrossMethodAssertion[telemetry.Tracer]) TracerOption {
	return func(c *tracerConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type tracerCustomSubtest struct {
	name string
	fn   func(*testing.T, telemetry.Tracer)
}

type tracerConfig struct {
	prePopulate func(context.Context, telemetry.Tracer)
	custom      []tracerCustomSubtest
	onAll       []suite.CrossMethodAssertion[telemetry.Tracer]
	onStart     []func(*testing.T, telemetry.Tracer)
}

func newTracerConfig(opts ...TracerOption) tracerConfig {
	var cfg tracerConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
