// Code generated by kanon. DO NOT EDIT.
// source: signature.go

package sign

import (
	"testing"

	"go.thesmos.sh/kanon/kanontest"
)

// kanonSpecSignature describes Signature to the conformance suite.
var kanonSpecSignature = kanontest.Spec[Signature]{
	Fields: []kanontest.Field{
		{Name: "Algorithm", Number: 1},
		{Name: "Value", Number: 2},
		{Name: "KeyID", Number: 3},
	},
}

// TestKanonSignature runs the conformance suite on Signature.
func TestKanonSignature(t *testing.T) {
	kanontest.Run(t, kanonSpecSignature)
}

// BenchmarkKanonSignature measures the codec of Signature.
func BenchmarkKanonSignature(b *testing.B) {
	kanontest.Bench(b, kanonSpecSignature)
}

// FuzzKanonSignature fuzzes the decode of Signature.
func FuzzKanonSignature(f *testing.F) {
	kanontest.Fuzz(f, kanonSpecSignature)
}
