// Code generated by testkit stub. DO NOT EDIT.
// Source: clock.go:48-62 (testkit stub Clock)

package clocktest

import (
	"testing"
	"time"

	clock2 "go.thesmos.sh/core/clock"
	"go.thesmos.sh/testkit/clock"
	"go.thesmos.sh/testkit/rand"
	"go.thesmos.sh/testkit/stub"
)

// Compile-time interface check.
var _ clock2.Clock = (*ClockStub)(nil)

// --- Call types ---

// ClockNewTimerCall records one invocation of clock2.Clock.NewTimer.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ClockNewTimerCall struct {
	D      time.Duration
	Result clock2.Timer
}

// ClockNowCall records one invocation of clock2.Clock.Now.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ClockNowCall struct {
	Result clock2.Instant
}

// ClockTimeCall records one invocation of clock2.Clock.Time.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ClockTimeCall struct {
	Result time.Time
}

// ClockUpdateCall records one invocation of clock2.Clock.Update.
// Result fields use the return-value names from the source interface when
// available; unnamed returns produce positional names (Result0, Result1, ...).
type ClockUpdateCall struct {
	Observed clock2.Instant
	Result   clock2.Instant
}

// --- Per-method stubs ---

// ClockNewTimerStub controls behavior and records calls for NewTimer.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ClockNewTimerStub struct {
	*stub.MethodStub[ClockNewTimerCall]
	fn       func(time.Duration) clock2.Timer
	fallback *clockNewTimerReturn
}

type clockNewTimerReturn struct {
	Result clock2.Timer
}

// Returns sets a fixed return value for NewTimer.
func (s *ClockNewTimerStub) Returns(result clock2.Timer) *ClockNewTimerStub {
	s.fallback = &clockNewTimerReturn{Result: result}
	return s
}

// Func sets a function override for NewTimer.
func (s *ClockNewTimerStub) Func(fn func(time.Duration) clock2.Timer) *ClockNewTimerStub {
	s.fn = fn
	return s
}

// ClockNowStub controls behavior and records calls for Now.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ClockNowStub struct {
	*stub.MethodStub[ClockNowCall]
	fn       func() clock2.Instant
	fallback *clockNowReturn
}

type clockNowReturn struct {
	Result clock2.Instant
}

// Returns sets a fixed return value for Now.
func (s *ClockNowStub) Returns(result clock2.Instant) *ClockNowStub {
	s.fallback = &clockNowReturn{Result: result}
	return s
}

// Func sets a function override for Now.
func (s *ClockNowStub) Func(fn func() clock2.Instant) *ClockNowStub {
	s.fn = fn
	return s
}

// ClockTimeStub controls behavior and records calls for Time.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ClockTimeStub struct {
	*stub.MethodStub[ClockTimeCall]
	fn       func() time.Time
	fallback *clockTimeReturn
}

type clockTimeReturn struct {
	Result time.Time
}

// Returns sets a fixed return value for Time.
func (s *ClockTimeStub) Returns(result time.Time) *ClockTimeStub {
	s.fallback = &clockTimeReturn{Result: result}
	return s
}

// Func sets a function override for Time.
func (s *ClockTimeStub) Func(fn func() time.Time) *ClockTimeStub {
	s.fn = fn
	return s
}

// ClockUpdateStub controls behavior and records calls for Update.
//
// Concurrent-test primitives inherited from [stub.MethodStub]:
//   - [stub.Recorder.WaitForN] / [stub.Recorder.WaitFor] — block until calls arrive (cond-variable, no polling)
//   - [stub.Recorder.NewGate] / [stub.Gate.Release] / [stub.Gate.ReleaseOne] — deterministic race control
//   - [stub.Recorder.OnRecord] — streaming hook fired synchronously on every call
type ClockUpdateStub struct {
	*stub.MethodStub[ClockUpdateCall]
	fn       func(clock2.Instant) clock2.Instant
	fallback *clockUpdateReturn
}

type clockUpdateReturn struct {
	Result clock2.Instant
}

// Returns sets a fixed return value for Update.
func (s *ClockUpdateStub) Returns(result clock2.Instant) *ClockUpdateStub {
	s.fallback = &clockUpdateReturn{Result: result}
	return s
}

// Func sets a function override for Update.
func (s *ClockUpdateStub) Func(fn func(clock2.Instant) clock2.Instant) *ClockUpdateStub {
	s.fn = fn
	return s
}

// --- ClockStub ---

// ClockStubOption configures a [ClockStub] at construction time.
type ClockStubOption func(*ClockStub)

// ClockStubStrict enables strict mode — unconfigured methods fail the test.
func ClockStubStrict() ClockStubOption {
	return func(s *ClockStub) { s.strict = true }
}

// ClockStubDelegateTo wraps a real implementation — all calls delegate to
// impl and are recorded on the outer stub.
func ClockStubDelegateTo(impl clock2.Clock) ClockStubOption {
	return func(s *ClockStub) {
		s.OnNewTimer.Func(impl.NewTimer)
		s.OnNow.Func(impl.Now)
		s.OnTime.Func(impl.Time)
		s.OnUpdate.Func(impl.Update)
	}
}

// ClockStubWithClock injects a [clock.Clock] into all per-method stubs.
// Use [clock.NewTestClock] for deterministic virtual time or a consumer's
// own clock implementation. Default is real wall-clock time.
func ClockStubWithClock(clk clock.Clock) ClockStubOption {
	return func(s *ClockStub) {
		s.OnNewTimer.WithClock(clk)
		s.OnNow.WithClock(clk)
		s.OnTime.WithClock(clk)
		s.OnUpdate.WithClock(clk)
	}
}

// ClockStubWithRandSource injects a [rand.Source] into all per-method
// stubs. Use [rand.FixedRandSource] for deterministic testing or a consumer's
// own seeded RNG. Default is [rand.DefaultRandSource] (math/rand/v2).
func ClockStubWithRandSource(src rand.Source) ClockStubOption {
	return func(s *ClockStub) {
		s.OnNewTimer.WithRandSource(src)
		s.OnNow.WithRandSource(src)
		s.OnTime.WithRandSource(src)
		s.OnUpdate.WithRandSource(src)
	}
}

// ClockStubBenchMode disables call recording on all per-method stubs. Use
// this in benchmarks to avoid allocation overhead from accumulated call logs.
// Dispatch (Func, Returns, Faults) still works normally.
func ClockStubBenchMode() ClockStubOption {
	return func(s *ClockStub) {
		s.OnNewTimer.BenchMode()
		s.OnNow.BenchMode()
		s.OnTime.BenchMode()
		s.OnUpdate.BenchMode()
	}
}

// WithClockNewTimer sets a function override at construction time.
func WithClockNewTimer(fn func(time.Duration) clock2.Timer) ClockStubOption {
	return func(s *ClockStub) { s.OnNewTimer.Func(fn) }
}

// WithClockNow sets a function override at construction time.
func WithClockNow(fn func() clock2.Instant) ClockStubOption {
	return func(s *ClockStub) { s.OnNow.Func(fn) }
}

// WithClockTime sets a function override at construction time.
func WithClockTime(fn func() time.Time) ClockStubOption {
	return func(s *ClockStub) { s.OnTime.Func(fn) }
}

// WithClockUpdate sets a function override at construction time.
func WithClockUpdate(fn func(clock2.Instant) clock2.Instant) ClockStubOption {
	return func(s *ClockStub) { s.OnUpdate.Func(fn) }
}

// ClockStub is a configurable test double for [clock2.Clock].
type ClockStub struct {
	OnNewTimer *ClockNewTimerStub
	OnNow      *ClockNowStub
	OnTime     *ClockTimeStub
	OnUpdate   *ClockUpdateStub
	strict     bool
}

// NewClockStub creates a stub. Pass tb for auto-verification of
// expectations at test cleanup. Pass nil for a pure stub.
func NewClockStub(tb testing.TB, opts ...ClockStubOption) *ClockStub {
	s := &ClockStub{
		OnNewTimer: &ClockNewTimerStub{MethodStub: stub.NewMethodStub[ClockNewTimerCall](tb, "Clock.NewTimer")},
		OnNow:      &ClockNowStub{MethodStub: stub.NewMethodStub[ClockNowCall](tb, "Clock.Now")},
		OnTime:     &ClockTimeStub{MethodStub: stub.NewMethodStub[ClockTimeCall](tb, "Clock.Time")},
		OnUpdate:   &ClockUpdateStub{MethodStub: stub.NewMethodStub[ClockUpdateCall](tb, "Clock.Update")},
	}
	for _, opt := range opts {
		opt(s)
	}
	if s.strict {
		s.OnNewTimer.Strict()
		s.OnNow.Strict()
		s.OnTime.Strict()
		s.OnUpdate.Strict()
	}
	if tb != nil {
		tb.Cleanup(func() {
			s.OnNewTimer.Verify()
			s.OnNow.Verify()
			s.OnTime.Verify()
			s.OnUpdate.Verify()
		})
	}
	return s
}

// Reset clears recorded calls, fault counters, and call-count expectations.
// Func, Returns, and Faults configuration is preserved.
func (s *ClockStub) Reset() {
	s.OnNewTimer.Reset()
	s.OnNow.Reset()
	s.OnTime.Reset()
	s.OnUpdate.Reset()
}

// --- Interface method implementations ---

func (s *ClockStub) NewTimer(d time.Duration) clock2.Timer {
	s.OnNewTimer.SleepLatency()
	call := ClockNewTimerCall{D: d}
	if s.OnNewTimer.fn != nil {
		r0 := s.OnNewTimer.fn(d)
		call.Result = r0
		s.OnNewTimer.Record(call)
		return r0
	}
	if s.OnNewTimer.fallback != nil {
		f := s.OnNewTimer.fallback
		call.Result = f.Result
		s.OnNewTimer.Record(call)
		return f.Result
	}
	s.OnNewTimer.FailUnexpectedCall(call)
	s.OnNewTimer.Record(call)
	return nil
}

func (s *ClockStub) Now() clock2.Instant {
	s.OnNow.SleepLatency()
	call := ClockNowCall{}
	if s.OnNow.fn != nil {
		r0 := s.OnNow.fn()
		call.Result = r0
		s.OnNow.Record(call)
		return r0
	}
	if s.OnNow.fallback != nil {
		f := s.OnNow.fallback
		call.Result = f.Result
		s.OnNow.Record(call)
		return f.Result
	}
	s.OnNow.FailUnexpectedCall(call)
	s.OnNow.Record(call)
	return clock2.Instant{}
}

func (s *ClockStub) Time() time.Time {
	s.OnTime.SleepLatency()
	call := ClockTimeCall{}
	if s.OnTime.fn != nil {
		r0 := s.OnTime.fn()
		call.Result = r0
		s.OnTime.Record(call)
		return r0
	}
	if s.OnTime.fallback != nil {
		f := s.OnTime.fallback
		call.Result = f.Result
		s.OnTime.Record(call)
		return f.Result
	}
	s.OnTime.FailUnexpectedCall(call)
	s.OnTime.Record(call)
	return time.Time{}
}

func (s *ClockStub) Update(observed clock2.Instant) clock2.Instant {
	s.OnUpdate.SleepLatency()
	call := ClockUpdateCall{Observed: observed}
	if s.OnUpdate.fn != nil {
		r0 := s.OnUpdate.fn(observed)
		call.Result = r0
		s.OnUpdate.Record(call)
		return r0
	}
	if s.OnUpdate.fallback != nil {
		f := s.OnUpdate.fallback
		call.Result = f.Result
		s.OnUpdate.Record(call)
		return f.Result
	}
	s.OnUpdate.FailUnexpectedCall(call)
	s.OnUpdate.Record(call)
	return clock2.Instant{}
}
