// Code generated by testkit builder. DO NOT EDIT.
// Source: testkit builder Instant InstantRange

package clocktest_test

import (
	"testing"

	"go.thesmos.sh/core/clock"
	"go.thesmos.sh/core/coretest/clocktest"
	"go.thesmos.sh/testkit"
)

func TestInstantBuilder(t *testing.T) {
	t.Parallel()
	t.Run("NewInstant builds without panic", func(t *testing.T) {
		t.Parallel()
		_ = clocktest.NewInstant().Build()
	})

	t.Run("NewInstantFrom zero value round-trips", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantFrom(clock.Instant{}).Build()
		testkit.Equal(t, got, clock.Instant{}, "must return zero value")
	})

	t.Run("WithLogical sets field", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantFrom(clock.Instant{}).
			WithLogical(42).
			Build()
		testkit.Equal(t, got.Logical, 42, "must set Logical")
	})

	t.Run("WithNode sets field", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantFrom(clock.Instant{}).
			WithNode(clock.NodeID(42)).
			Build()
		testkit.Equal(t, got.Node, clock.NodeID(42), "must set Node")
	})

	t.Run("WithWall sets field", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantFrom(clock.Instant{}).
			WithWall(42).
			Build()
		testkit.Equal(t, got.Wall, 42, "must set Wall")
	})

	t.Run("Clone forks independent scalar", func(t *testing.T) {
		t.Parallel()
		base := clocktest.NewInstantFrom(clock.Instant{})
		clone := base.Clone()
		clone.WithLogical(42)
		original := base.Build()
		modified := clone.Build()
		testkit.NotEqual(t, original.Logical, modified.Logical,
			"Clone must produce independent copy")
	})

	t.Run("Mutate modifies value", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantFrom(clock.Instant{}).
			Mutate(func(v *clock.Instant) {
				v.Logical = 42
			}).
			Build()
		testkit.Equal(t, got.Logical, 42, "Mutate must modify")
	})
}

func TestInstantRangeBuilder(t *testing.T) {
	t.Parallel()
	t.Run("NewInstantRange builds without panic", func(t *testing.T) {
		t.Parallel()
		_ = clocktest.NewInstantRange().Build()
	})

	t.Run("NewInstantRangeFrom zero value round-trips", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantRangeFrom(clock.InstantRange{}).Build()
		testkit.Equal(t, got, clock.InstantRange{}, "must return zero value")
	})

	t.Run("WithSince sets field", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantRangeFrom(clock.InstantRange{}).
			WithSince(clock.Instant{Wall: 42}).
			Build()
		testkit.Equal(t, got.Since, clock.Instant{Wall: 42}, "must set Since")
	})

	t.Run("WithUntil sets field", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantRangeFrom(clock.InstantRange{}).
			WithUntil(clock.Instant{Wall: 42}).
			Build()
		testkit.Equal(t, got.Until, clock.Instant{Wall: 42}, "must set Until")
	})

	t.Run("Clone forks independent scalar", func(t *testing.T) {
		t.Parallel()
		base := clocktest.NewInstantRangeFrom(clock.InstantRange{})
		clone := base.Clone()
		clone.WithSince(clock.Instant{Wall: 42})
		original := base.Build()
		modified := clone.Build()
		testkit.NotEqual(t, original.Since, modified.Since,
			"Clone must produce independent copy")
	})

	t.Run("Mutate modifies value", func(t *testing.T) {
		t.Parallel()
		got := clocktest.NewInstantRangeFrom(clock.InstantRange{}).
			Mutate(func(v *clock.InstantRange) {
				v.Since = clock.Instant{Wall: 42}
			}).
			Build()
		testkit.Equal(t, got.Since, clock.Instant{Wall: 42}, "Mutate must modify")
	})
}
