// Code generated by testkit suite. DO NOT EDIT.
// Source: clock.go:50-68 (testkit suite Clock)

package clocktest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/core/clock"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertClockContract runs conformance assertions against
// implementations of [clock.Clock] produced by factory.
//
//	Default subtests: 4 across 4 methods
//	Shapes detected:  Pure (NewTimer, Now, Time, Update)
//	Directives:       none
//	Plug-in points:   ClockOnNewTimer, ClockOnNow, ClockOnTime, ClockOnUpdate, ClockOnAll, ClockCustom
func AssertClockContract(
	t *testing.T,
	factory func() clock.Clock,
	opts ...ClockOption,
) {
	t.Helper()
	cfg := newClockConfig(opts...)

	runClockNewTimer(t, factory, &cfg)
	runClockNow(t, factory, &cfg)
	runClockTime(t, factory, &cfg)
	runClockUpdate(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[clock.Clock]{
			T:             t,
			CrossBindings: bindings.CrossBindings[clock.Clock]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runClockNewTimer(t *testing.T, factory func() clock.Clock, cfg *clockConfig) {
	t.Helper()

	t.Run("NewTimer/smoke", func(t *testing.T) {
		t.Parallel()
		s := factory()
		_ = s.NewTimer(0)
	})
	if len(cfg.onNewTimer) > 0 {
		t.Run("NewTimer", func(t *testing.T) {
			prePopFactory := func() clock.Clock {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[clock.Clock, clock.Timer]{
				T: t,
				PureBindings: bindings.PureBindings[clock.Clock, clock.Timer]{
					Factory: prePopFactory,
					Call: func(impl clock.Clock) clock.Timer {
						return impl.NewTimer(0)
					},
				},
			}
			for _, a := range cfg.onNewTimer {
				a(pctx)
			}
		})
	}
}

func runClockNow(t *testing.T, factory func() clock.Clock, cfg *clockConfig) {
	t.Helper()

	t.Run("Now/smoke", func(t *testing.T) {
		t.Parallel()
		s := factory()
		_ = s.Now()
	})
	if len(cfg.onNow) > 0 {
		t.Run("Now", func(t *testing.T) {
			prePopFactory := func() clock.Clock {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[clock.Clock, clock.Instant]{
				T: t,
				PureBindings: bindings.PureBindings[clock.Clock, clock.Instant]{
					Factory: prePopFactory,
					Call: func(impl clock.Clock) clock.Instant {
						return impl.Now()
					},
				},
			}
			for _, a := range cfg.onNow {
				a(pctx)
			}
		})
	}
}

func runClockTime(t *testing.T, factory func() clock.Clock, cfg *clockConfig) {
	t.Helper()

	t.Run("Time/smoke", func(t *testing.T) {
		t.Parallel()
		s := factory()
		_ = s.Time()
	})
	if len(cfg.onTime) > 0 {
		t.Run("Time", func(t *testing.T) {
			prePopFactory := func() clock.Clock {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[clock.Clock, time.Time]{
				T: t,
				PureBindings: bindings.PureBindings[clock.Clock, time.Time]{
					Factory: prePopFactory,
					Call: func(impl clock.Clock) time.Time {
						return impl.Time()
					},
				},
			}
			for _, a := range cfg.onTime {
				a(pctx)
			}
		})
	}
}

func runClockUpdate(t *testing.T, factory func() clock.Clock, cfg *clockConfig) {
	t.Helper()

	t.Run("Update/smoke", func(t *testing.T) {
		t.Parallel()
		s := factory()
		_ = s.Update(clock.Instant{})
	})
	if len(cfg.onUpdate) > 0 {
		t.Run("Update", func(t *testing.T) {
			prePopFactory := func() clock.Clock {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[clock.Clock, clock.Instant]{
				T: t,
				PureBindings: bindings.PureBindings[clock.Clock, clock.Instant]{
					Factory: prePopFactory,
					Call: func(impl clock.Clock) clock.Instant {
						return impl.Update(clock.Instant{})
					},
				},
			}
			for _, a := range cfg.onUpdate {
				a(pctx)
			}
		})
	}
}

// ClockOption configures [AssertClockContract].
type ClockOption func(*clockConfig)

// ClockPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func ClockPrePopulate(fn func(ctx context.Context, s clock.Clock)) ClockOption {
	return func(c *clockConfig) { c.prePopulate = fn }
}

// ClockCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func ClockCustom(name string, fn func(*testing.T, clock.Clock)) ClockOption {
	return func(c *clockConfig) {
		c.custom = append(c.custom, clockCustomSubtest{name: name, fn: fn})
	}
}

// ClockOnNewTimer adds plug-in assertions for the NewTimer method.
func ClockOnNewTimer(assertions ...suite.PureAssertion[clock.Clock, clock.Timer]) ClockOption {
	return func(c *clockConfig) {
		c.onNewTimer = append(c.onNewTimer, assertions...)
	}
}

// ClockOnNow adds plug-in assertions for the Now method.
func ClockOnNow(assertions ...suite.PureAssertion[clock.Clock, clock.Instant]) ClockOption {
	return func(c *clockConfig) {
		c.onNow = append(c.onNow, assertions...)
	}
}

// ClockOnTime adds plug-in assertions for the Time method.
func ClockOnTime(assertions ...suite.PureAssertion[clock.Clock, time.Time]) ClockOption {
	return func(c *clockConfig) {
		c.onTime = append(c.onTime, assertions...)
	}
}

// ClockOnUpdate adds plug-in assertions for the Update method.
func ClockOnUpdate(assertions ...suite.PureAssertion[clock.Clock, clock.Instant]) ClockOption {
	return func(c *clockConfig) {
		c.onUpdate = append(c.onUpdate, assertions...)
	}
}

// ClockOnAll adds cross-method assertions that span multiple methods.
func ClockOnAll(assertions ...suite.CrossMethodAssertion[clock.Clock]) ClockOption {
	return func(c *clockConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type clockCustomSubtest struct {
	name string
	fn   func(*testing.T, clock.Clock)
}

type clockConfig struct {
	prePopulate func(context.Context, clock.Clock)
	custom      []clockCustomSubtest
	onAll       []suite.CrossMethodAssertion[clock.Clock]
	onNewTimer  []suite.PureAssertion[clock.Clock, clock.Timer]
	onNow       []suite.PureAssertion[clock.Clock, clock.Instant]
	onTime      []suite.PureAssertion[clock.Clock, time.Time]
	onUpdate    []suite.PureAssertion[clock.Clock, clock.Instant]
}

func newClockConfig(opts ...ClockOption) clockConfig {
	var cfg clockConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
