// Code generated by testkit stub. DO NOT EDIT.
// Source: clock.go:50-68 (testkit stub Clock)

package clocktest_test

import (
	"testing"
	"time"

	clock2 "go.thesmos.sh/core/clock"
	"go.thesmos.sh/core/coretest/clocktest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestClockStub(t *testing.T) {
	t.Parallel()

	t.Run("NewTimer default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		result := s.NewTimer(0)
		testkit.Equal(t, result, nil, "NewTimer must return zero")
	})

	t.Run("NewTimer Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		called := false
		s.OnNewTimer.Func(func(time.Duration) clock2.Timer {
			called = true
			return nil
		})
		result := s.NewTimer(0)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("NewTimer Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnNewTimer.Returns(nil)
		result := s.NewTimer(0)
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("NewTimer records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.NewTimer(0)
		s.OnNewTimer.AssertCalledOnce(t, "must record NewTimer call")
	})

	t.Run("WithClockNewTimer constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewClockStub(t, clocktest.WithClockNewTimer(func(time.Duration) clock2.Timer {
			called = true
			return nil
		}))
		_ = s.NewTimer(0)
		testkit.True(t, called, "WithClockNewTimer must be called")
	})

	t.Run("NewTimer records call args", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.NewTimer(time.Duration(42))
		call := s.OnNewTimer.LastCall(t)
		testkit.Equal(t, call.D, time.Duration(42), "D must be recorded")
	})

	t.Run("NewTimer OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		var observed []clocktest.ClockNewTimerCall
		s.OnNewTimer.OnRecord(func(c clocktest.ClockNewTimerCall) {
			observed = append(observed, c)
		})
		_ = s.NewTimer(0)
		_ = s.NewTimer(0)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every NewTimer call")
	})

	t.Run("Now default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		result := s.Now()
		testkit.Equal(t, result, clock2.Instant{}, "Now must return zero")
	})

	t.Run("Now Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		called := false
		s.OnNow.Func(func() clock2.Instant {
			called = true
			return clock2.Instant{Wall: 42}
		})
		result := s.Now()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Func must return set value")
	})

	t.Run("Now Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnNow.Returns(clock2.Instant{Wall: 42})
		result := s.Now()
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Returns must return set value")
	})

	t.Run("Now records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.Now()
		s.OnNow.AssertCalledOnce(t, "must record Now call")
	})

	t.Run("WithClockNow constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewClockStub(t, clocktest.WithClockNow(func() clock2.Instant {
			called = true
			return clock2.Instant{}
		}))
		_ = s.Now()
		testkit.True(t, called, "WithClockNow must be called")
	})

	t.Run("Now OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		var observed []clocktest.ClockNowCall
		s.OnNow.OnRecord(func(c clocktest.ClockNowCall) {
			observed = append(observed, c)
		})
		_ = s.Now()
		_ = s.Now()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Now call")
	})

	t.Run("Time default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		result := s.Time()
		testkit.Equal(t, result, time.Time{}, "Time must return zero")
	})

	t.Run("Time Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		called := false
		s.OnTime.Func(func() time.Time {
			called = true
			return time.Time{}
		})
		result := s.Time()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, time.Time{}, "Func must return set value")
	})

	t.Run("Time Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnTime.Returns(time.Time{})
		result := s.Time()
		testkit.Equal(t, result, time.Time{}, "Returns must return set value")
	})

	t.Run("Time records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.Time()
		s.OnTime.AssertCalledOnce(t, "must record Time call")
	})

	t.Run("WithClockTime constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewClockStub(t, clocktest.WithClockTime(func() time.Time {
			called = true
			return time.Time{}
		}))
		_ = s.Time()
		testkit.True(t, called, "WithClockTime must be called")
	})

	t.Run("Time OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		var observed []clocktest.ClockTimeCall
		s.OnTime.OnRecord(func(c clocktest.ClockTimeCall) {
			observed = append(observed, c)
		})
		_ = s.Time()
		_ = s.Time()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Time call")
	})

	t.Run("Update default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		result := s.Update(clock2.Instant{})
		testkit.Equal(t, result, clock2.Instant{}, "Update must return zero")
	})

	t.Run("Update Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		called := false
		s.OnUpdate.Func(func(clock2.Instant) clock2.Instant {
			called = true
			return clock2.Instant{Wall: 42}
		})
		result := s.Update(clock2.Instant{})
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Func must return set value")
	})

	t.Run("Update Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnUpdate.Returns(clock2.Instant{Wall: 42})
		result := s.Update(clock2.Instant{})
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Returns must return set value")
	})

	t.Run("Update records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.Update(clock2.Instant{})
		s.OnUpdate.AssertCalledOnce(t, "must record Update call")
	})

	t.Run("WithClockUpdate constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewClockStub(t, clocktest.WithClockUpdate(func(clock2.Instant) clock2.Instant {
			called = true
			return clock2.Instant{}
		}))
		_ = s.Update(clock2.Instant{})
		testkit.True(t, called, "WithClockUpdate must be called")
	})

	t.Run("Update records call args", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.Update(clock2.Instant{Wall: 42})
		call := s.OnUpdate.LastCall(t)
		testkit.Equal(t, call.Observed, clock2.Instant{Wall: 42}, "Observed must be recorded")
	})

	t.Run("Update OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		var observed []clocktest.ClockUpdateCall
		s.OnUpdate.OnRecord(func(c clocktest.ClockUpdateCall) {
			observed = append(observed, c)
		})
		_ = s.Update(clock2.Instant{})
		_ = s.Update(clock2.Instant{})
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Update call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t, clocktest.ClockStubBenchMode())
		_ = s.NewTimer(0)
		testkit.Equal(t, s.OnNewTimer.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t, clocktest.ClockStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f)
		s.OnNewTimer.Times(2)
		_ = s.NewTimer(0)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f)
		s.OnNewTimer.TimesAtLeast(3)
		_ = s.NewTimer(0)
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.NewTimer(0)
		_ = s.Now()
		_ = s.Time()
		_ = s.Update(clock2.Instant{})
		s.ResetCalls()
		s.OnNewTimer.AssertNotCalled(t, "NewTimer must be cleared after ResetCalls")
		s.OnNow.AssertNotCalled(t, "Now must be cleared after ResetCalls")
		s.OnTime.AssertNotCalled(t, "Time must be cleared after ResetCalls")
		s.OnUpdate.AssertNotCalled(t, "Update must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured NewTimer", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f, clocktest.ClockStubStrict())
		_ = s.NewTimer(0)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured NewTimer")
	})

	t.Run("Strict mode fails on unconfigured Now", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f, clocktest.ClockStubStrict())
		_ = s.Now()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Now")
	})

	t.Run("Strict mode fails on unconfigured Time", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f, clocktest.ClockStubStrict())
		_ = s.Time()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Time")
	})

	t.Run("Strict mode fails on unconfigured Update", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewClockStub(f, clocktest.ClockStubStrict())
		_ = s.Update(clock2.Instant{})
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Update")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewClockStub(t)
		inner.OnNewTimer.Returns(nil)
		inner.OnNow.Returns(clock2.Instant{})
		inner.OnTime.Returns(time.Time{})
		inner.OnUpdate.Returns(clock2.Instant{})
		s := clocktest.NewClockStub(t, clocktest.ClockStubDelegateTo(inner))
		_ = s.NewTimer(0)
		_ = s.Now()
		_ = s.Time()
		_ = s.Update(clock2.Instant{})
		s.OnNewTimer.AssertCalledOnce(t, "NewTimer must delegate")
		s.OnNow.AssertCalledOnce(t, "Now must delegate")
		s.OnTime.AssertCalledOnce(t, "Time must delegate")
		s.OnUpdate.AssertCalledOnce(t, "Update must delegate")
	})

	t.Run("DelegateTo surfaces NewTimer return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewClockStub(t)
		inner.OnNewTimer.Returns(nil)
		s := clocktest.NewClockStub(t, clocktest.ClockStubDelegateTo(inner))
		result := s.NewTimer(0)
		testkit.Equal(t, result, nil, "NewTimer must return configured value")
	})

	t.Run("DelegateTo surfaces Now return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewClockStub(t)
		inner.OnNow.Returns(clock2.Instant{Wall: 42})
		s := clocktest.NewClockStub(t, clocktest.ClockStubDelegateTo(inner))
		result := s.Now()
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Now must return configured value")
	})

	t.Run("DelegateTo surfaces Time return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewClockStub(t)
		inner.OnTime.Returns(time.Time{})
		s := clocktest.NewClockStub(t, clocktest.ClockStubDelegateTo(inner))
		result := s.Time()
		testkit.Equal(t, result, time.Time{}, "Time must return configured value")
	})

	t.Run("DelegateTo surfaces Update return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewClockStub(t)
		inner.OnUpdate.Returns(clock2.Instant{Wall: 42})
		s := clocktest.NewClockStub(t, clocktest.ClockStubDelegateTo(inner))
		result := s.Update(clock2.Instant{})
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Update must return configured value")
	})

	t.Run("ResetCalls preserves NewTimer Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnNewTimer.Returns(nil)
		_ = s.NewTimer(0)
		s.ResetCalls()
		s.OnNewTimer.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.NewTimer(0)
		testkit.Equal(t, result, nil, "NewTimer must return configured value")
	})

	t.Run("ResetCalls preserves Now Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnNow.Returns(clock2.Instant{Wall: 42})
		_ = s.Now()
		s.ResetCalls()
		s.OnNow.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Now()
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Now must return configured value")
	})

	t.Run("ResetCalls preserves Time Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnTime.Returns(time.Time{})
		_ = s.Time()
		s.ResetCalls()
		s.OnTime.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Time()
		testkit.Equal(t, result, time.Time{}, "Time must return configured value")
	})

	t.Run("ResetCalls preserves Update Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		s.OnUpdate.Returns(clock2.Instant{Wall: 42})
		_ = s.Update(clock2.Instant{})
		s.ResetCalls()
		s.OnUpdate.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Update(clock2.Instant{})
		testkit.Equal(t, result, clock2.Instant{Wall: 42}, "Update must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewClockStub(t)
		_ = s.NewTimer(0)
		testkit.Len(t, s.OnNewTimer.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnNewTimer.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestClockStubBenchModeZeroAlloc(t *testing.T) {
	s := clocktest.NewClockStub(nil, clocktest.ClockStubBenchMode())
	s.OnNewTimer.Returns(nil)
	s.OnNow.Returns(clock2.Instant{})
	s.OnTime.Returns(time.Time{})
	s.OnUpdate.Returns(clock2.Instant{})

	t.Run("NewTimer", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.NewTimer(0)
		})
		testkit.Equal(t, int(avgAllocs), 0, "NewTimer in BenchMode must be 0 alloc")
	})

	t.Run("Now", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Now()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Now in BenchMode must be 0 alloc")
	})

	t.Run("Time", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Time()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Time in BenchMode must be 0 alloc")
	})

	t.Run("Update", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Update(clock2.Instant{})
		})
		testkit.Equal(t, int(avgAllocs), 0, "Update in BenchMode must be 0 alloc")
	})

}
