// Code generated by testkit suite. DO NOT EDIT.
// Source: clock.go:104-112 (testkit suite Timer)

package clocktest

import (
	"context"
	"testing"
	"time"

	"go.thesmos.sh/core/clock"
	"go.thesmos.sh/testkit/bindings"
	"go.thesmos.sh/testkit/suite"
)

// AssertTimerContract runs conformance assertions against
// implementations of [clock.Timer] produced by factory.
//
//	Default subtests: 3 across 3 methods
//	Shapes detected:  Pure (C), Predicate (Reset, Stop)
//	Directives:       none
//	Plug-in points:   TimerOnC, TimerOnReset, TimerOnStop, TimerOnAll, TimerCustom
func AssertTimerContract(
	t *testing.T,
	factory func() clock.Timer,
	opts ...TimerOption,
) {
	t.Helper()
	cfg := newTimerConfig(opts...)

	runTimerC(t, factory, &cfg)
	runTimerReset(t, factory, &cfg)
	runTimerStop(t, factory, &cfg)

	for _, a := range cfg.onAll {
		cctx := suite.CrossContext[clock.Timer]{
			T:             t,
			CrossBindings: bindings.CrossBindings[clock.Timer]{Factory: factory},
		}
		a(cctx)
	}

	for _, custom := range cfg.custom {
		t.Run(custom.name, func(t *testing.T) {
			t.Parallel()
			custom.fn(t, factory())
		})
	}
}

func runTimerC(t *testing.T, factory func() clock.Timer, cfg *timerConfig) {
	t.Helper()

	t.Run("C/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: C panicked on zero-value args (%v) — supply sample values via TimerOnC", r)
			}
		}()
		s := factory()
		_ = s.C()
	})
	if len(cfg.onC) > 0 {
		t.Run("C", func(t *testing.T) {
			prePopFactory := func() clock.Timer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PureContext[clock.Timer, <-chan time.Time]{
				T: t,
				PureBindings: bindings.PureBindings[clock.Timer, <-chan time.Time]{
					Factory: prePopFactory,
					Call: func(impl clock.Timer) <-chan time.Time {
						return impl.C()
					},
				},
			}
			for _, a := range cfg.onC {
				a(pctx)
			}
		})
	}
}

func runTimerReset(t *testing.T, factory func() clock.Timer, cfg *timerConfig) {
	t.Helper()

	t.Run("Reset/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Reset panicked on zero-value args (%v) — supply sample values via TimerOnReset", r)
			}
		}()
		s := factory()
		_ = s.Reset(0)
	})
	if len(cfg.onReset) > 0 {
		t.Run("Reset", func(t *testing.T) {
			prePopFactory := func() clock.Timer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PredicateContext[clock.Timer]{
				T: t,
				PredicateBindings: bindings.PredicateBindings[clock.Timer]{
					Factory: prePopFactory,
					Call: func(impl clock.Timer) bool {
						return impl.Reset(0)
					},
				},
			}
			for _, a := range cfg.onReset {
				a(pctx)
			}
		})
	}
}

func runTimerStop(t *testing.T, factory func() clock.Timer, cfg *timerConfig) {
	t.Helper()

	t.Run("Stop/smoke", func(t *testing.T) {
		t.Parallel()
		defer func() {
			if r := recover(); r != nil {
				t.Skipf("smoke: Stop panicked on zero-value args (%v) — supply sample values via TimerOnStop", r)
			}
		}()
		s := factory()
		_ = s.Stop()
	})
	if len(cfg.onStop) > 0 {
		t.Run("Stop", func(t *testing.T) {
			prePopFactory := func() clock.Timer {
				impl := factory()
				if cfg.prePopulate != nil {
					cfg.prePopulate(t.Context(), impl)
				}
				return impl
			}
			pctx := suite.PredicateContext[clock.Timer]{
				T: t,
				PredicateBindings: bindings.PredicateBindings[clock.Timer]{
					Factory: prePopFactory,
					Call: func(impl clock.Timer) bool {
						return impl.Stop()
					},
				},
			}
			for _, a := range cfg.onStop {
				a(pctx)
			}
		})
	}
}

// TimerOption configures [AssertTimerContract].
type TimerOption func(*timerConfig)

// TimerPrePopulate runs before subtests that need pre-populated state.
// Called once per subtest against a fresh impl from the factory.
func TimerPrePopulate(fn func(ctx context.Context, s clock.Timer)) TimerOption {
	return func(c *timerConfig) { c.prePopulate = fn }
}

// TimerCustom adds a free-form subtest to the contract. Use this for
// contracts not expressible via shape-specific primitives.
func TimerCustom(name string, fn func(*testing.T, clock.Timer)) TimerOption {
	return func(c *timerConfig) {
		c.custom = append(c.custom, timerCustomSubtest{name: name, fn: fn})
	}
}

// TimerOnC adds plug-in assertions for the C method.
func TimerOnC(assertions ...suite.PureAssertion[clock.Timer, <-chan time.Time]) TimerOption {
	return func(c *timerConfig) {
		c.onC = append(c.onC, assertions...)
	}
}

// TimerOnReset adds plug-in assertions for the Reset method.
func TimerOnReset(assertions ...suite.PredicateAssertion[clock.Timer]) TimerOption {
	return func(c *timerConfig) {
		c.onReset = append(c.onReset, assertions...)
	}
}

// TimerOnStop adds plug-in assertions for the Stop method.
func TimerOnStop(assertions ...suite.PredicateAssertion[clock.Timer]) TimerOption {
	return func(c *timerConfig) {
		c.onStop = append(c.onStop, assertions...)
	}
}

// TimerOnAll adds cross-method assertions that span multiple methods.
func TimerOnAll(assertions ...suite.CrossMethodAssertion[clock.Timer]) TimerOption {
	return func(c *timerConfig) {
		c.onAll = append(c.onAll, assertions...)
	}
}

type timerCustomSubtest struct {
	name string
	fn   func(*testing.T, clock.Timer)
}

type timerConfig struct {
	prePopulate func(context.Context, clock.Timer)
	custom      []timerCustomSubtest
	onAll       []suite.CrossMethodAssertion[clock.Timer]
	onC         []suite.PureAssertion[clock.Timer, <-chan time.Time]
	onReset     []suite.PredicateAssertion[clock.Timer]
	onStop      []suite.PredicateAssertion[clock.Timer]
}

func newTimerConfig(opts ...TimerOption) timerConfig {
	var cfg timerConfig
	for _, opt := range opts {
		opt(&cfg)
	}
	return cfg
}
