// Code generated by testkit stub. DO NOT EDIT.
// Source: clock.go:104-112 (testkit stub Timer)

package clocktest_test

import (
	"testing"
	"time"

	"go.thesmos.sh/core/coretest/clocktest"
	"go.thesmos.sh/testkit"
	"go.thesmos.sh/testkit/rand"
)

func TestTimerStub(t *testing.T) {
	t.Parallel()

	t.Run("C default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		result := s.C()
		testkit.Equal(t, result, nil, "C must return zero")
	})

	t.Run("C Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		called := false
		s.OnC.Func(func() <-chan time.Time {
			called = true
			return nil
		})
		result := s.C()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, nil, "Func must return set value")
	})

	t.Run("C Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnC.Returns(nil)
		result := s.C()
		testkit.Equal(t, result, nil, "Returns must return set value")
	})

	t.Run("C records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.C()
		s.OnC.AssertCalledOnce(t, "must record C call")
	})

	t.Run("WithTimerC constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewTimerStub(t, clocktest.WithTimerC(func() <-chan time.Time {
			called = true
			return nil
		}))
		_ = s.C()
		testkit.True(t, called, "WithTimerC must be called")
	})

	t.Run("C OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		var observed []clocktest.TimerCCall
		s.OnC.OnRecord(func(c clocktest.TimerCCall) {
			observed = append(observed, c)
		})
		_ = s.C()
		_ = s.C()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every C call")
	})

	t.Run("Reset default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		result := s.Reset(0)
		testkit.Equal(t, result, false, "Reset must return zero")
	})

	t.Run("Reset Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		called := false
		s.OnReset.Func(func(time.Duration) bool {
			called = true
			return true
		})
		result := s.Reset(0)
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, true, "Func must return set value")
	})

	t.Run("Reset Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnReset.Returns(true)
		result := s.Reset(0)
		testkit.Equal(t, result, true, "Returns must return set value")
	})

	t.Run("Reset records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.Reset(0)
		s.OnReset.AssertCalledOnce(t, "must record Reset call")
	})

	t.Run("WithTimerReset constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewTimerStub(t, clocktest.WithTimerReset(func(time.Duration) bool {
			called = true
			return false
		}))
		_ = s.Reset(0)
		testkit.True(t, called, "WithTimerReset must be called")
	})

	t.Run("Reset records call args", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.Reset(time.Duration(42))
		call := s.OnReset.LastCall(t)
		testkit.Equal(t, call.D, time.Duration(42), "D must be recorded")
	})

	t.Run("Reset OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		var observed []clocktest.TimerResetCall
		s.OnReset.OnRecord(func(c clocktest.TimerResetCall) {
			observed = append(observed, c)
		})
		_ = s.Reset(0)
		_ = s.Reset(0)
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Reset call")
	})

	t.Run("Stop default returns zero", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		result := s.Stop()
		testkit.Equal(t, result, false, "Stop must return zero")
	})

	t.Run("Stop Func override", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		called := false
		s.OnStop.Func(func() bool {
			called = true
			return true
		})
		result := s.Stop()
		testkit.True(t, called, "Func must be called")
		testkit.Equal(t, result, true, "Func must return set value")
	})

	t.Run("Stop Returns fixed value", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnStop.Returns(true)
		result := s.Stop()
		testkit.Equal(t, result, true, "Returns must return set value")
	})

	t.Run("Stop records calls", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.Stop()
		s.OnStop.AssertCalledOnce(t, "must record Stop call")
	})

	t.Run("WithTimerStop constructor option", func(t *testing.T) {
		t.Parallel()
		called := false
		s := clocktest.NewTimerStub(t, clocktest.WithTimerStop(func() bool {
			called = true
			return false
		}))
		_ = s.Stop()
		testkit.True(t, called, "WithTimerStop must be called")
	})

	t.Run("Stop OnRecord hook fires", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		var observed []clocktest.TimerStopCall
		s.OnStop.OnRecord(func(c clocktest.TimerStopCall) {
			observed = append(observed, c)
		})
		_ = s.Stop()
		_ = s.Stop()
		testkit.Len(t, observed, 2, "OnRecord hook must fire for every Stop call")
	})

	t.Run("BenchMode disables recording", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t, clocktest.TimerStubBenchMode())
		_ = s.C()
		testkit.Equal(t, s.OnC.CallCount(), 0,
			"BenchMode must disable recording")
	})

	t.Run("WithRandSource propagates to all methods", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t, clocktest.TimerStubWithRandSource(rand.FixedRandSource(0.5)))
		_ = s // verify construction succeeds with RandSource
	})

	t.Run("Times mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewTimerStub(f)
		s.OnC.Times(2)
		_ = s.C()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "Times mismatch must fail")
	})

	t.Run("TimesAtLeast mismatch fails", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewTimerStub(f)
		s.OnC.TimesAtLeast(3)
		_ = s.C()
		f.RunCleanups()
		testkit.True(t, f.Failed(), "TimesAtLeast mismatch must fail")
	})

	t.Run("ResetCalls clears all recordings", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.C()
		_ = s.Reset(0)
		_ = s.Stop()
		s.ResetCalls()
		s.OnC.AssertNotCalled(t, "C must be cleared after ResetCalls")
		s.OnReset.AssertNotCalled(t, "Reset must be cleared after ResetCalls")
		s.OnStop.AssertNotCalled(t, "Stop must be cleared after ResetCalls")
	})

	t.Run("Strict mode fails on unconfigured C", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewTimerStub(f, clocktest.TimerStubStrict())
		_ = s.C()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured C")
	})

	t.Run("Strict mode fails on unconfigured Reset", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewTimerStub(f, clocktest.TimerStubStrict())
		_ = s.Reset(0)
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Reset")
	})

	t.Run("Strict mode fails on unconfigured Stop", func(t *testing.T) {
		t.Parallel()
		f := testkit.NewFailableTB()
		s := clocktest.NewTimerStub(f, clocktest.TimerStubStrict())
		_ = s.Stop()
		testkit.True(t, f.Failed(), "strict mode must fail on unconfigured Stop")
	})

	t.Run("DelegateTo forwards to implementation", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewTimerStub(t)
		inner.OnC.Returns(nil)
		inner.OnReset.Returns(false)
		inner.OnStop.Returns(false)
		s := clocktest.NewTimerStub(t, clocktest.TimerStubDelegateTo(inner))
		_ = s.C()
		_ = s.Reset(0)
		_ = s.Stop()
		s.OnC.AssertCalledOnce(t, "C must delegate")
		s.OnReset.AssertCalledOnce(t, "Reset must delegate")
		s.OnStop.AssertCalledOnce(t, "Stop must delegate")
	})

	t.Run("DelegateTo surfaces C return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewTimerStub(t)
		inner.OnC.Returns(nil)
		s := clocktest.NewTimerStub(t, clocktest.TimerStubDelegateTo(inner))
		result := s.C()
		testkit.Equal(t, result, nil, "C must return configured value")
	})

	t.Run("DelegateTo surfaces Reset return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewTimerStub(t)
		inner.OnReset.Returns(true)
		s := clocktest.NewTimerStub(t, clocktest.TimerStubDelegateTo(inner))
		result := s.Reset(0)
		testkit.Equal(t, result, true, "Reset must return configured value")
	})

	t.Run("DelegateTo surfaces Stop return values", func(t *testing.T) {
		t.Parallel()
		inner := clocktest.NewTimerStub(t)
		inner.OnStop.Returns(true)
		s := clocktest.NewTimerStub(t, clocktest.TimerStubDelegateTo(inner))
		result := s.Stop()
		testkit.Equal(t, result, true, "Stop must return configured value")
	})

	t.Run("ResetCalls preserves C Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnC.Returns(nil)
		_ = s.C()
		s.ResetCalls()
		s.OnC.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.C()
		testkit.Equal(t, result, nil, "C must return configured value")
	})

	t.Run("ResetCalls preserves Reset Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnReset.Returns(true)
		_ = s.Reset(0)
		s.ResetCalls()
		s.OnReset.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Reset(0)
		testkit.Equal(t, result, true, "Reset must return configured value")
	})

	t.Run("ResetCalls preserves Stop Returns config", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		s.OnStop.Returns(true)
		_ = s.Stop()
		s.ResetCalls()
		s.OnStop.AssertNotCalled(t, "ResetCalls must clear recordings")
		result := s.Stop()
		testkit.Equal(t, result, true, "Stop must return configured value")
	})

	t.Run("ResetCalls clears timestamps", func(t *testing.T) {
		t.Parallel()
		s := clocktest.NewTimerStub(t)
		_ = s.C()
		testkit.Len(t, s.OnC.Timestamped(), 1, "must record")
		s.ResetCalls()
		testkit.Len(t, s.OnC.Timestamped(), 0, "ResetCalls must clear timestamps")
	})
}

func TestTimerStubBenchModeZeroAlloc(t *testing.T) {
	s := clocktest.NewTimerStub(nil, clocktest.TimerStubBenchMode())
	s.OnC.Returns(nil)
	s.OnReset.Returns(false)
	s.OnStop.Returns(false)

	t.Run("C", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.C()
		})
		testkit.Equal(t, int(avgAllocs), 0, "C in BenchMode must be 0 alloc")
	})

	t.Run("Reset", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Reset(0)
		})
		testkit.Equal(t, int(avgAllocs), 0, "Reset in BenchMode must be 0 alloc")
	})

	t.Run("Stop", func(t *testing.T) {
		const iterations = 100
		avgAllocs := testing.AllocsPerRun(iterations, func() {
			_ = s.Stop()
		})
		testkit.Equal(t, int(avgAllocs), 0, "Stop in BenchMode must be 0 alloc")
	})

}
